program Application;

uses
  Forms,
  AccountingServiceRegistry in 'Accounting\AccountingServiceRegistry.pas',
  BusinessProcessService in 'Business Processes\Common\BusinessProcessService.pas',
  DocumentChargeSheetControlAppService in 'Business Processes\Docs\Common\Charge Sheets\Interfaces\DocumentChargeSheetControlAppService.pas',
  StandardDocumentChargeSheetControlAppService in 'Business Processes\Docs\Common\Charge Sheets\StandardDocumentChargeSheetControlAppService.pas',
  DocumentStorageService in 'Business Processes\Docs\Common\Storage\Interfaces\DocumentStorageService.pas',
  DocumentOperationService in 'Business Processes\Docs\Common\DocumentOperationService.pas',
  EmployeeDocumentOperationService in 'Business Processes\Docs\Common\EmployeeDocumentOperationService.pas',
  DocumentApprovingControlAppService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingControlAppService.pas',
  DocumentApprovingPerformingService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingPerformingService.pas',
  DocumentApprovingRejectingService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingRejectingService.pas',
  DocumentApprovingService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingService.pas',
  DocumentSigningRejectingService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningRejectingService.pas',
  SendingDocumentToApprovingService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToApprovingService.pas',
  SendingDocumentToSigningService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToSigningService.pas',
  StandardDocumentApprovingControlAppService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingControlAppService.pas',
  StandardDocumentApprovingPerformingService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingPerformingService.pas',
  StandardDocumentApprovingRejectingService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingRejectingService.pas',
  StandardDocumentApprovingService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingService.pas',
  StandardDocumentSigningRejectingService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningRejectingService.pas',
  StandardSendingDocumentToApprovingService in 'Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToApprovingService.pas',
  StandardSendingDocumentToSigningService in 'Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToSigningService.pas',
  DocumentChargeSheetCasesNotifier in 'External\Messaging\Documents\Common\Interfaces\DocumentChargeSheetCasesNotifier.pas',
  DocumentChargeSheetNotifyingMessageBuilder in 'External\Messaging\Documents\Common\Interfaces\DocumentChargeSheetNotifyingMessageBuilder.pas',
  EmployeeDocumentNotificationPolicy in 'External\Messaging\Documents\Common\Policies\Interfaces\EmployeeDocumentNotificationPolicy.pas',
  AllEmployeesDocumentNotificationPolicy in 'External\Messaging\Documents\Common\Policies\AllEmployeesDocumentNotificationPolicy.pas',
  ForeignEmployeesDocumentNotificationPolicy in 'External\Messaging\Documents\Common\Policies\ForeignEmployeesDocumentNotificationPolicy.pas',
  NoneEmployeeDocumentNotificationPolicy in 'External\Messaging\Documents\Common\Policies\NoneEmployeeDocumentNotificationPolicy.pas',
  AbstractDocumentChargeSheetNotifyingMessageBuilder in 'External\Messaging\Documents\Common\AbstractDocumentChargeSheetNotifyingMessageBuilder.pas',
  StandardDocumentChargeSheetCasesNotifier in 'External\Messaging\Documents\Common\StandardDocumentChargeSheetCasesNotifier.pas',
  EmailDocumentChargeSheetNotifyingMessageBuilder1 in 'External\Messaging\Documents\Email\EmailDocumentChargeSheetNotifyingMessageBuilder1.pas',
  EmailDocumentChargeSheetNotifyingMessageBuilder2 in 'External\Messaging\Documents\Email\EmailDocumentChargeSheetNotifyingMessageBuilder2.pas',
  IDocumentFileServiceClientUnit in 'External\Storage\Interfaces\IDocumentFileServiceClientUnit.pas',
  DocumentFileServiceClientUnit in 'External\Storage\DocumentFileServiceClientUnit.pas',
  ExternalServiceRegistry in 'External\ExternalServiceRegistry.pas',
  StandardEmployeeDepartmentManagementService in 'Management\Employees\StandardEmployeeDepartmentManagementService.pas',
  EmployeeDepartmentManagementService in 'Management\Employees\Interfaces\EmployeeDepartmentManagementService.pas',
  ManagementServiceRegistry in 'Management\ManagementServiceRegistry.pas',
  PresentationServiceRegistry in 'Presentation\PresentationServiceRegistry.pas',
  ReportingServiceRegistry in 'Reporting\ReportingServiceRegistry.pas',
  NotPerformedDocumentsReportDataService in 'Reporting\Docs\Interfaces\NotPerformedDocumentsReportDataService.pas',
  ApplicationServiceRegistries in 'Service Registries\ApplicationServiceRegistries.pas',
  StatisticsServiceRegistry in 'Statistics\StatisticsServiceRegistry.pas',
  AbstractEmployeeDocumentWorkStatisticsZeosService in 'Statistics\Docs\Zeos-Based\AbstractEmployeeDocumentWorkStatisticsZeosService.pas',
  EmployeeDocumentWorkStatistics in 'Statistics\Docs\Interfaces\EmployeeDocumentWorkStatistics.pas',
  EmployeeDocumentWorkStatisticsService in 'Statistics\Docs\Interfaces\EmployeeDocumentWorkStatisticsService.pas',
  DocumentViewingAccountingService in 'Accounting\Docs\Interfaces\DocumentViewingAccountingService.pas',
  DBWorkingEmployeeUnit in 'Working Employee\DBWorkingEmployeeUnit.pas',
  IWorkingEmployeeUnit in 'Working Employee\IWorkingEmployeeUnit.pas',
  WorkingEmployeeUnit in 'Working Employee\WorkingEmployeeUnit.pas',
  ZeosPostgresWorkingEmployeeUnit in 'Working Employee\ZeosPostgresWorkingEmployeeUnit.pas',
  EmployeeSetReadService in 'Presentation\Employees\References\Interfaces\EmployeeSetReadService.pas',
  BasedOnDatabaseEmployeeSetReadService in 'Presentation\Employees\References\Based-On DB\BasedOnDatabaseEmployeeSetReadService.pas',
  EmployeeDbSchema in 'Presentation\Employees\References\Based-On DB\Common\EmployeeDbSchema.pas',
  DepartmentDbSchema in 'Presentation\Employees\References\Based-On DB\Common\DepartmentDbSchema.pas',
  EmployeeDocumentChargesWorkStatistics in 'Statistics\Docs\Charges\Interfaces\EmployeeDocumentChargesWorkStatistics.pas',
  EmployeeDocumentChargesWorkStatisticsService in 'Statistics\Docs\Charges\Interfaces\EmployeeDocumentChargesWorkStatisticsService.pas',
  EmployeeDocumentChargesWorkStatisticsZeosService in 'Statistics\Docs\Charges\Zeos-Based\EmployeeDocumentChargesWorkStatisticsZeosService.pas',
  EmployeeDocumentChargesWorkStatisticsPostgresService in 'Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeDocumentChargesWorkStatisticsPostgresService.pas',
  EmployeeIncomingServiceNoteChargesWorkStatisticsPostgresService in 'Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeIncomingServiceNoteChargesWorkStatisticsPostgresService.pas',
  EmployeeOutcomingServiceNoteChargesWorkStatisticsPostgresService in 'Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeOutcomingServiceNoteChargesWorkStatisticsPostgresService.pas',
  RoleDbSchema in 'Presentation\Employees\References\Based-On DB\Common\RoleDbSchema.pas',
  SystemServiceRegistry in 'System\SystemServiceRegistry.pas',
  DocumentBusinessProcessServiceRegistry in 'Business Processes\Docs\DocumentBusinessProcessServiceRegistry.pas',
  StandardDocumentApprovingListCreatingAppService in 'Reporting\Docs\Standard\StandardDocumentApprovingListCreatingAppService.pas',
  DocumentApprovingListCreatingAppService in 'Reporting\Docs\Interfaces\DocumentApprovingListCreatingAppService.pas',
  StandardIncomingDocumentApprovingListCreatingAppService in 'Reporting\Docs\Standard\StandardIncomingDocumentApprovingListCreatingAppService.pas',
  EmployeeDocumentKindAccessRightsAppService in 'Business Processes\Docs\Common\Access\Interfaces\EmployeeDocumentKindAccessRightsAppService.pas',
  StandardEmployeeDocumentKindAccessRightsAppService in 'Business Processes\Docs\Common\Access\StandardEmployeeDocumentKindAccessRightsAppService.pas',
  EmployeeWorkGroupAssociationDbSchema in 'Presentation\Employees\References\Based-On DB\Common\EmployeeWorkGroupAssociationDbSchema.pas',
  RelatedDocumentStorageService in 'Business Processes\Docs\Common\Storage\Interfaces\RelatedDocumentStorageService.pas',
  DocumentStorageServiceCommandsAndRespones in 'Business Processes\Docs\Common\Storage\Interfaces\DocumentStorageServiceCommandsAndRespones.pas',
  StandardRelatedDocumentStorageService in 'Business Processes\Docs\Common\Storage\StandardRelatedDocumentStorageService.pas',
  DocumentBusinessProcessServiceRegistryConfigurator in 'Configuration\DocumentBusinessProcessServiceRegistryConfigurator.pas',
  DocumentKindWorkCycleInfoAppService in 'Presentation\Docs\References\Document Kinds\Interfaces\DocumentKindWorkCycleInfoAppService.pas',
  StandardDocumentKindWorkCycleInfoAppService in 'Presentation\Docs\References\Document Kinds\StandardDocumentKindWorkCycleInfoAppService.pas',
  DomainConfigurator in 'Configuration\DomainConfigurator.pas',
  ApplicationRepositoryRegistryConfigurator in 'Configuration\ApplicationRepositoryRegistryConfigurator.pas',
  UserNotificationProfile in 'Management\User Profiles\Dtos\UserNotificationProfile.pas',
  UserNotificationProfileService in 'Management\User Profiles\Interfaces\UserNotificationProfileService.pas',
  BasedOnDatabaseUserNotificationProfileService in 'Management\User Profiles\Based-On DB\BasedOnDatabaseUserNotificationProfileService.pas',
  BasedOnDatabaseSDItemsService in 'External\SD\BasedOnDatabaseSDItemsService.pas',
  SDItem in 'External\SD\SDItem.pas',
  SDItemsService in 'External\SD\SDItemsService.pas',
  NativeDocumentKindsReadService in 'Presentation\Docs\References\Document Kinds\Interfaces\NativeDocumentKindsReadService.pas',
  BasedOnDatabaseNativeDocumentKindsReadService in 'Presentation\Docs\References\Document Kinds\Based-On DB\BasedOnDatabaseNativeDocumentKindsReadService.pas',
  DocumentKindDbSchema in 'Presentation\Docs\References\Document Kinds\Based-On DB\Schemas\DocumentKindDbSchema.pas',
  GlobalDocumentKindsReadService in 'Presentation\Docs\References\Document Kinds\Interfaces\GlobalDocumentKindsReadService.pas',
  StandardGlobalDocumentKindsReadService in 'Presentation\Docs\References\Document Kinds\StandardGlobalDocumentKindsReadService.pas',
  ConfigurationData in 'Configuration\ConfigurationData.pas',
  ExternalServiceRegistryConfigurator in 'Configuration\ExternalServiceRegistryConfigurator.pas',
  PresentationServiceRegistryConfigurator in 'Configuration\PresentationServiceRegistryConfigurator.pas',
  ApplicationConfigurator in 'Configuration\ApplicationConfigurator.pas',
  RespondingDocumentCreatingAppService in 'Business Processes\Docs\Common\Operations\Interfaces\RespondingDocumentCreatingAppService.pas',
  StandardRespondingDocumentCreatingAppService in 'Business Processes\Docs\Common\Operations\StandardRespondingDocumentCreatingAppService.pas',
  BasedOnDatabaseDocumentViewingAccountingService in 'Accounting\Docs\Based-On DB\BasedOnDatabaseDocumentViewingAccountingService.pas',
  BasedOnDatabaseIncomingDocumentViewingAccountingService in 'Accounting\Docs\Based-On DB\BasedOnDatabaseIncomingDocumentViewingAccountingService.pas',
  ProgramChangesNotificationControlService in 'Presentation\Program Changes Notification\Interfaces\ProgramChangesNotificationControlService.pas',
  BasedOnZeosPostgresProgramChangesNotificationControlService in 'Presentation\Program Changes Notification\Based-On DB\BasedOnZeosPostgresProgramChangesNotificationControlService.pas',
  DocumentFlowAdministrationService in 'System\Administration\Interfaces\DocumentFlowAdministrationService.pas',
  DocumentFlowAdminPrivileges in 'System\Administration\DTOs\DocumentFlowAdminPrivileges.pas',
  DocumentFlowAdminPrivilegeServices in 'System\Administration\DTOs\DocumentFlowAdminPrivilegeServices.pas',
  EmployeesAdminPrivilegeServices in 'System\Administration\DTOs\EmployeesAdminPrivilegeServices.pas',
  EmployeesWorkGroupsAdminPrivilegeServices in 'System\Administration\DTOs\EmployeesWorkGroupsAdminPrivilegeServices.pas',
  EmployeesReplacementsAdminPrivilegeServices in 'System\Administration\DTOs\EmployeesReplacementsAdminPrivilegeServices.pas',
  DepartmentsAdminPrivilegeServices in 'System\Administration\DTOs\DepartmentsAdminPrivilegeServices.pas',
  EmployeeStaffsAdminPrivilegeServices in 'System\Administration\DTOs\EmployeeStaffsAdminPrivilegeServices.pas',
  DocumentFlowAuthorizationService in 'System\Authorization\Interfaces\DocumentFlowAuthorizationService.pas',
  BasedOnDatabaseDocumentFlowAuthorizationService in 'System\Authorization\Based-On Databases\BasedOnDatabaseDocumentFlowAuthorizationService.pas',
  AbstractApplicationService in 'Common\Services\AbstractApplicationService.pas',
  ApplicationService in 'Common\Services\ApplicationService.pas',
  _ApplicationServiceRegistry in 'Common\Services\_ApplicationServiceRegistry.pas',
  BasedOnZeosDocumentFlowAuthorizationService in 'System\Authorization\Based-On Databases\Based-On Zeos\BasedOnZeosDocumentFlowAuthorizationService.pas',
  StandardDocumentFlowAdministrationService in 'System\Administration\StandardDocumentFlowAdministrationService.pas',
  AbstractDocumentFlowAuthorizationService in 'System\Authorization\AbstractDocumentFlowAuthorizationService.pas',
  SystemServiceRegistryConfigurator in 'Configuration\SystemServiceRegistryConfigurator.pas',
  DepartmentsAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\DepartmentsAdminReferenceControlService.pas',
  EmployeesAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\EmployeesAdminReferenceControlService.pas',
  EmployeesReplacementsAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\EmployeesReplacementsAdminReferenceControlService.pas',
  EmployeeStaffsAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\EmployeeStaffsAdminReferenceControlService.pas',
  EmployeesWorkGroupsAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\EmployeesWorkGroupsAdminReferenceControlService.pas',
  DocumentsAdminPrivilegeServices in 'System\Administration\DTOs\DocumentsAdminPrivilegeServices.pas',
  DocumentFlowAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Interfaces\DocumentFlowAdminPrivilegeServicesFactory.pas',
  BasedOnVclZeosDepartmentsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosDepartmentsAdminPrivilegeServicesFactory.pas',
  AbstractDocumentFlowAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\AbstractDocumentFlowAdminPrivilegeServicesFactory.pas',
  BasedOnVclZeosEmployeesAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosEmployeesAdminPrivilegeServicesFactory.pas',
  BasedOnVclZeosEmployeesReplacementsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosEmployeesReplacementsAdminPrivilegeServicesFactory.pas',
  BasedOnVclZeosEmployeeStaffsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosEmployeeStaffsAdminPrivilegeServicesFactory.pas',
  BasedOnVclZeosEmployeesWorkGroupsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosEmployeesWorkGroupsAdminPrivilegeServicesFactory.pas',
  StandardDocumentsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Standard\StandardDocumentsAdminPrivilegeServicesFactory.pas',
  DocumentFlowAdminPrivilegeServicesFactories in 'System\Administration\DTOs\Factories\Interfaces\DocumentFlowAdminPrivilegeServicesFactories.pas',
  StandardDocumentFlowAdminPrivilegeServicesFactories in 'System\Administration\DTOs\Factories\Standard\StandardDocumentFlowAdminPrivilegeServicesFactories.pas',
  BasedOnVclZeosDepartmentsAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosDepartmentsAdminReferenceControlService.pas',
  BasedOnVclZeosEmployeesAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosEmployeesAdminReferenceControlService.pas',
  BasedOnVclZeosEmployeesReplacementsAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosEmployeesReplacementsAdminReferenceControlService.pas',
  BasedOnVclZeosEmployeeStaffsAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosEmployeeStaffsAdminReferenceControlService.pas',
  BasedOnVclZeosEmployeesWorkGroupsAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosEmployeesWorkGroupsAdminReferenceControlService.pas',
  DepartmentSetReadService in 'Presentation\Employees\References\Interfaces\DepartmentSetReadService.pas',
  BasedOnDatabaseDepartmentSetReadService in 'Presentation\Employees\References\Based-On DB\BasedOnDatabaseDepartmentSetReadService.pas',
  BasedOnVclZeosSynchronizationDataControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosSynchronizationDataControlService.pas',
  SynchronizationDataControlService in 'System\Administration\Privilege Services\Interfaces\SynchronizationDataControlService.pas',
  BasedOnVclZeosSynchronizationDataAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosSynchronizationDataAdminPrivilegeServicesFactory.pas',
  SynchronizationDataAdminPrivilegeServices in 'System\Administration\DTOs\SynchronizationDataAdminPrivilegeServices.pas',
  DocumentApproverSetReadService in 'Presentation\Docs\References\Document Actors\Interfaces\DocumentApproverSetReadService.pas',
  DocumentChargePerformerSetReadService in 'Presentation\Docs\References\Document Actors\Interfaces\DocumentChargePerformerSetReadService.pas',
  DocumentResponsibleSetReadService in 'Presentation\Docs\References\Document Actors\Interfaces\DocumentResponsibleSetReadService.pas',
  DocumentSignerSetReadService in 'Presentation\Docs\References\Document Actors\Interfaces\DocumentSignerSetReadService.pas',
  DepartmentDocumentSetReadService in 'Presentation\Docs\References\Document List\Interfaces\DepartmentDocumentSetReadService.pas',
  BasedOnDatabaseAbstractDepartmentDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseAbstractDepartmentDocumentSetReadService.pas',
  BasedOnDatabaseDepartmentOutcomingDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseDepartmentOutcomingDocumentSetReadService.pas',
  BasedOnDatabaseDepartmentIncomingDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseDepartmentIncomingDocumentSetReadService.pas',
  EmployeeDocumentSetReadService in 'Presentation\Docs\References\Document List\Interfaces\EmployeeDocumentSetReadService.pas',
  BasedOnDatabaseAbstractDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseAbstractDocumentSetReadService.pas',
  BasedOnDatabaseAbstractEmployeeDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseAbstractEmployeeDocumentSetReadService.pas',
  AbstractDocumentEmployeeSetReadService in 'Presentation\Docs\References\Document Actors\AbstractDocumentEmployeeSetReadService.pas',
  BasedOnDatabaseEmployeeIncomingDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseEmployeeIncomingDocumentSetReadService.pas',
  BasedOnDatabaseEmployeeInternalDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseEmployeeInternalDocumentSetReadService.pas',
  BasedOnDatabaseEmployeeOutcomingDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseEmployeeOutcomingDocumentSetReadService.pas',
  AdminDocumentSetReadService in 'System\Administration\References\Documents\List\Interfaces\AdminDocumentSetReadService.pas',
  StandardAdminDocumentSetReadService in 'System\Administration\References\Documents\List\StandardAdminDocumentSetReadService.pas',
  StandardAdminDocumentStorageService in 'System\Administration\Storage\Documents\StandardAdminDocumentStorageService.pas',
  AdminDocumentStorageService in 'System\Administration\Storage\Documents\Interfaces\AdminDocumentStorageService.pas',
  SendingDocumentToPerformingAppService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToPerformingAppService.pas',
  StandardSendingDocumentToPerformingAppService in 'Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToPerformingAppService.pas',
  BasedOnDBNotPerformedDocumentsReportDataService in 'Reporting\Docs\Based-On DB\BasedOnDBNotPerformedDocumentsReportDataService.pas',
  BasedOnDBNotPerformedIncomingDocumentsReportDataService in 'Reporting\Docs\Based-On DB\BasedOnDBNotPerformedIncomingDocumentsReportDataService.pas',
  BasedOnPostgresNotPerformedIncomingServiceNotesReportDataService in 'Reporting\Docs\Based-On DB\Postgres\BasedOnPostgresNotPerformedIncomingServiceNotesReportDataService.pas',
  StandardOutcomingDocumentStorageService in 'Business Processes\Docs\Common\Storage\StandardOutcomingDocumentStorageService.pas',
  BasedOnDatabaseEmployeePersonnelOrderSetReadService in 'Presentation\Docs\Personnel Orders\References\Document List\Based-On DB\BasedOnDatabaseEmployeePersonnelOrderSetReadService.pas',
  DocumentSigningAppService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningAppService.pas',
  StandardDocumentSigningAppService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningAppService.pas',
  DocumentSigningToPerformingAppService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningToPerformingAppService.pas',
  StandardDocumentSigningToPerformingAppService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningToPerformingAppService.pas',
  DocumentNumeratorsAdminPrivilegeServices in 'System\Administration\DTOs\DocumentNumeratorsAdminPrivilegeServices.pas',
  DocumentNumeratorsAdminReferenceControlService in 'System\Administration\Privilege Services\Interfaces\DocumentNumeratorsAdminReferenceControlService.pas',
  BasedOnVclZeosDocumentNumeratorsAdminReferenceControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosDocumentNumeratorsAdminReferenceControlService.pas',
  BasedOnVclZeosDocumentNumeratorsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosDocumentNumeratorsAdminPrivilegeServicesFactory.pas',
  DocumentApprovingSheetDataCreatingAppService in 'Reporting\Docs\Interfaces\DocumentApprovingSheetDataCreatingAppService.pas',
  StandardDocumentApprovingSheetDataCreatingAppService in 'Reporting\Docs\Standard\StandardDocumentApprovingSheetDataCreatingAppService.pas',
  StandardPersonnelOrderApproverSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Standard\StandardPersonnelOrderApproverSetReadService.pas',
  BasedOnDatabaseEmployeeApproveableDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseEmployeeApproveableDocumentSetReadService.pas',
  BasedOnDatabaseDepartmentApproveableDocumentSetReadService in 'Presentation\Docs\References\Document List\Based-On DB\BasedOnDatabaseDepartmentApproveableDocumentSetReadService.pas',
  StandardPersonnelOrderSignerSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Standard\StandardPersonnelOrderSignerSetReadService.pas',
  PersonnelOrderSignerSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Interfaces\PersonnelOrderSignerSetReadService.pas',
  PersonnelOrderApproverSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Interfaces\PersonnelOrderApproverSetReadService.pas',
  PersonnelOrderSubKindEmployeeSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Interfaces\PersonnelOrderSubKindEmployeeSetReadService.pas',
  PersonnelOrderSubKindSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Kinds\Interfaces\PersonnelOrderSubKindSetReadService.pas',
  PersonnelOrderEmployeeSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\Interfaces\PersonnelOrderEmployeeSetReadService.pas',
  AbstractPersonnelOrderEmployeeSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\AbstractPersonnelOrderEmployeeSetReadService.pas',
  AbstractPersonnelOrderSubKindEmployeeSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Actors\AbstractPersonnelOrderSubKindEmployeeSetReadService.pas',
  BasedOnDBPersonnelOrderSubKindSetReadService in 'Presentation\Docs\Personnel Orders\References\Document Kinds\Based-On DB\BasedOnDBPersonnelOrderSubKindSetReadService.pas',
  DocumentSigningMarkingAppService in 'Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningMarkingAppService.pas',
  StandardDocumentSigningMarkingAppService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningMarkingAppService.pas',
  PersonnelOrderPresentationServiceRegistry in 'Presentation\Docs\Personnel Orders\PersonnelOrderPresentationServiceRegistry.pas',
  DocumentInfoReadService in 'Presentation\Docs\Cards\Doc Full Info\Interfaces\DocumentInfoReadService.pas',
  BasedOnDatabaseDocumentInfoReadService in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\BasedOnDatabaseDocumentInfoReadService.pas',
  BasedOnDatabaseDocumentCreatingDefaultInfoReadService in 'Presentation\Docs\Cards\On-Creating Default Doc Info\Based-On DB\BasedOnDatabaseDocumentCreatingDefaultInfoReadService.pas',
  DocumentCreatingDefaultInfoReadService in 'Presentation\Docs\Cards\On-Creating Default Doc Info\Interfaces\DocumentCreatingDefaultInfoReadService.pas',
  BasedOnDatabaseIncomingDocumentInfoReadService in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\BasedOnDatabaseIncomingDocumentInfoReadService.pas',
  PostgresDocumentFullInfoFetchingQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Postgres\PostgresDocumentFullInfoFetchingQueryBuilder.pas',
  PostgresIncomingDocumentFullInfoFetchingQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Postgres\PostgresIncomingDocumentFullInfoFetchingQueryBuilder.pas',
  PostgresDocumentCreatingDefaultInfoFetchingQueryBuilder in 'Presentation\Docs\Cards\On-Creating Default Doc Info\Based-On DB\Postgres\PostgresDocumentCreatingDefaultInfoFetchingQueryBuilder.pas',
  PostgresPersonnelOrderFullInfoFetchingQueryBuilder in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Postgres\PostgresPersonnelOrderFullInfoFetchingQueryBuilder.pas',
  BasedOnDatabasePersonnelOrderCreatingDefaultInfoReadService in 'Presentation\Docs\Personnel Orders\Cards\On-Creating Default Doc Info\BasedOnDatabasePersonnelOrderCreatingDefaultInfoReadService.pas',
  StandardDocumentApproverSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardDocumentApproverSetReadService.pas',
  StandardDocumentChargePerformerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardDocumentChargePerformerSetReadService.pas',
  StandardDocumentResponsibleSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardDocumentResponsibleSetReadService.pas',
  StandardDocumentSignerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardDocumentSignerSetReadService.pas',
  StandardIncomingInternalDocumentChargePerformerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardIncomingInternalDocumentChargePerformerSetReadService.pas',
  StandardInternalDocumentChargePerformerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardInternalDocumentChargePerformerSetReadService.pas',
  StandardInternalDocumentResponsibleSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardInternalDocumentResponsibleSetReadService.pas',
  StandardInternalDocumentSignerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardInternalDocumentSignerSetReadService.pas',
  PostgresDepartmentApproveableServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresDepartmentApproveableServiceNoteSetFetchingQueryBuilder.pas',
  PostgresDepartmentIncomingServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresDepartmentIncomingServiceNoteSetFetchingQueryBuilder.pas',
  PostgresDepartmentOutcomingServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresDepartmentOutcomingServiceNoteSetFetchingQueryBuilder.pas',
  PostgresEmployeeApproveableServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresEmployeeApproveableServiceNoteSetFetchingQueryBuilder.pas',
  PostgresEmployeeIncomingServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresEmployeeIncomingServiceNoteSetFetchingQueryBuilder.pas',
  PostgresEmployeeInternalServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresEmployeeInternalServiceNoteSetFetchingQueryBuilder.pas',
  PostgresEmployeeOutcomingServiceNoteSetFetchingQueryBuilder in 'Presentation\Docs\Service Notes\References\Document List\Based-On DB\Postgres\PostgresEmployeeOutcomingServiceNoteSetFetchingQueryBuilder.pas',
  PostgresEmployeePersonnelOrderSetFetchingQueryBuilder in 'Presentation\Docs\Personnel Orders\References\Document List\Based-On DB\Postgres\PostgresEmployeePersonnelOrderSetFetchingQueryBuilder.pas',
  BasedOnDatabasePersonnelOrderInfoReadService in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\BasedOnDatabasePersonnelOrderInfoReadService.pas',
  BasedOnDatabaseDepartmentPersonnelOrderSetReadService in 'Presentation\Docs\Personnel Orders\References\Document List\Based-On DB\BasedOnDatabaseDepartmentPersonnelOrderSetReadService.pas',
  PostgresDepartmentPersonnelOrderSetFetchingQueryBuilder in 'Presentation\Docs\Personnel Orders\References\Document List\Based-On DB\Postgres\PostgresDepartmentPersonnelOrderSetFetchingQueryBuilder.pas',
  UserNotificationProfileGroup in 'Management\User Profiles\Dtos\UserNotificationProfileGroup.pas',
  PlantItemService in 'External\Plant\PlantItemService.pas',
  BasedOnZeosVclPlantItemService in 'External\Plant\BasedOnZeosVclPlantItemService.pas',
  PlantStructureAccessService in 'External\Plant\PlantStructureAccessService.pas',
  BasedOnDBPlantStructureAccessService in 'External\Plant\BasedOnDBPlantStructureAccessService.pas',
  UserNotificationProfileAccessRightsService in 'Management\User Profiles\Interfaces\UserNotificationProfileAccessRightsService.pas',
  StandardUserNotificationProfileAccessRightsService in 'Management\User Profiles\Standard\StandardUserNotificationProfileAccessRightsService.pas',
  PersonnelOrderEmployeesControlService in 'System\Administration\Privilege Services\Interfaces\PersonnelOrderEmployeesControlService.pas',
  BasedOnVclZeosPersonnelOrderEmployeesControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosPersonnelOrderEmployeesControlService.pas',
  PersonnelOrderControlGroupsControlService in 'System\Administration\Privilege Services\Interfaces\PersonnelOrderControlGroupsControlService.pas',
  BasedOnVclZeosPersonnelOrderControlGroupsControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosPersonnelOrderControlGroupsControlService.pas',
  PersonnelOrderKindApproversControlService in 'System\Administration\Privilege Services\Interfaces\PersonnelOrderKindApproversControlService.pas',
  BasedOnVclZeosPersonnelOrderKindApproversControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosPersonnelOrderKindApproversControlService.pas',
  PersonnelOrderSignersControlService in 'System\Administration\Privilege Services\Interfaces\PersonnelOrderSignersControlService.pas',
  BasedOnVclZeosPersonnelOrderSignersControlService in 'System\Administration\Privilege Services\External Implementations\Based-On VclZeos\BasedOnVclZeosPersonnelOrderSignersControlService.pas',
  PersonnelOrderEmployeesAdminPrivilegeServices in 'System\Administration\DTOs\PersonnelOrderEmployeesAdminPrivilegeServices.pas',
  BasedOnVclZeosPersonnelOrderEmployeesAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosPersonnelOrderEmployeesAdminPrivilegeServicesFactory.pas',
  PersonnelOrderControlGroupsAdminPrivilegeServices in 'System\Administration\DTOs\PersonnelOrderControlGroupsAdminPrivilegeServices.pas',
  BasedOnVclZeosPersonnelOrderControlGroupsAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosPersonnelOrderControlGroupsAdminPrivilegeServicesFactory.pas',
  PersonnelOrderKindApproversAdminPrivilegeServices in 'System\Administration\DTOs\PersonnelOrderKindApproversAdminPrivilegeServices.pas',
  BasedOnVclZeosPersonnelOrderKindApproversAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosPersonnelOrderKindApproversAdminPrivilegeServicesFactory.pas',
  PersonnelOrderSignersAdminPrivilegeServices in 'System\Administration\DTOs\PersonnelOrderSignersAdminPrivilegeServices.pas',
  BasedOnVclZeosPersonnelOrderSignersAdminPrivilegeServicesFactory in 'System\Administration\DTOs\Factories\Based-On VclZeos\BasedOnVclZeosPersonnelOrderSignersAdminPrivilegeServicesFactory.pas',
  BasedOnDatabaseDocumentInfoPartlyReadService in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\BasedOnDatabaseDocumentInfoPartlyReadService.pas',
  DocumentFullInfoDataSetHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentFullInfoDataSetHolder.pas',
  IncomingDocumentFullInfoDataSetHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\IncomingDocumentFullInfoDataSetHolder.pas',
  DocumentChargeSheetsInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentChargeSheetsInfoHolder.pas',
  DocumentInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentInfoHolder.pas',
  DocumentFilesInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentFilesInfoHolder.pas',
  DocumentApprovingsInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentApprovingsInfoHolder.pas',
  DocumentChargesInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentChargesInfoHolder.pas',
  DocumentRelationsInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\DocumentRelationsInfoHolder.pas',
  DocumentDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentDTOFromDataSetMapper.pas',
  DocumentFullInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentFullInfoDTOFromDataSetMapper.pas',
  IncomingDocumentFullInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\IncomingDocumentFullInfoDTOFromDataSetMapper.pas',
  DocumentFilesInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentFilesInfoDTOFromDataSetMapper.pas',
  DocumentRelationsInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentRelationsInfoDTOFromDataSetMapper.pas',
  DocumentChargesInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentChargesInfoDTOFromDataSetMapper.pas',
  DocumentChargeSheetsInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentChargeSheetsInfoDTOFromDataSetMapper.pas',
  DocumentApprovingCycleResultsInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentApprovingCycleResultsInfoDTOFromDataSetMapper.pas',
  DocumentApprovingsInfoDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\DocumentApprovingsInfoDTOFromDataSetMapper.pas',
  DocumentInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\DocumentInfoHolderBuilder.pas',
  DocumentInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\DocumentInfoQueryBuilder.pas',
  FullDocumentApprovingsInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\FullDocumentApprovingsInfoQueryBuilder.pas',
  FullDocumentApprovingsInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\FullDocumentApprovingsInfoHolderBuilder.pas',
  DocumentPerformingInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\DocumentPerformingInfoQueryBuilder.pas',
  DocumentPerformingInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\DocumentPerformingInfoHolderBuilder.pas',
  DocumentFilesInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\DocumentFilesInfoQueryBuilder.pas',
  DocumentFilesInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\DocumentFilesInfoHolderBuilder.pas',
  DocumentRelationsInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\DocumentRelationsInfoQueryBuilder.pas',
  DocumentRelationsInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\DocumentRelationsInfoHolderBuilder.pas',
  IncomingDocumentInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\IncomingDocumentInfoQueryBuilder.pas',
  IncomingDocumentInfoHolder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Dtos\IncomingDocumentInfoHolder.pas',
  PostgresDocumentFilesInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresDocumentFilesInfoQueryBuilder.pas',
  PostgresDocumentInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresDocumentInfoQueryBuilder.pas',
  PostgresDocumentPerformingInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresDocumentPerformingInfoQueryBuilder.pas',
  PostgresDocumentRelationsInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresDocumentRelationsInfoQueryBuilder.pas',
  PostgresFullDocumentApprovingsInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresFullDocumentApprovingsInfoQueryBuilder.pas',
  PostgresIncomingDocumentInfoQueryBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresIncomingDocumentInfoQueryBuilder.pas',
  IncomingDocumentInfoHolderBuilder in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Builders\DataSets\IncomingDocumentInfoHolderBuilder.pas',
  IncomingDocumentDTOFromDataSetMapper in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\Mappers\IncomingDocumentDTOFromDataSetMapper.pas',
  BasedOnDatabaseIncomingDocumentInfoPartlyReadService in 'Presentation\Docs\Cards\Doc Full Info\Based-On DB\BasedOnDatabaseIncomingDocumentInfoPartlyReadService.pas',
  PersonnelOrderFullInfoDTOFromDataSetMapper in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Mappers\PersonnelOrderFullInfoDTOFromDataSetMapper.pas',
  PersonnelOrderDTOFromDataSetMapper in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Mappers\PersonnelOrderDTOFromDataSetMapper.pas',
  PersonnelOrderInfoHolder in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Dtos\PersonnelOrderInfoHolder.pas',
  PostgresPersonnelOrderInfoQueryBuilder in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresPersonnelOrderInfoQueryBuilder.pas',
  PersonnelOrderInfoHolderBuilder in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Builders\DataSets\PersonnelOrderInfoHolderBuilder.pas',
  PersonnelOrderFullInfoDataSetHolder in 'Presentation\Docs\Personnel Orders\Cards\Doc Full Info\Based-On DB\Dtos\PersonnelOrderFullInfoDataSetHolder.pas',
  DocumentChargeSheetViewingAccountingService in 'Accounting\Docs\Interfaces\DocumentChargeSheetViewingAccountingService.pas',
  BasedOnDocumentViewingDocumentChargeSheetViewingAccountingService in 'Accounting\Docs\BasedOnDocumentViewingDocumentChargeSheetViewingAccountingService.pas',
  DocumentKinds in 'Common\Documents\DocumentKinds.pas',
  DocumentChargeSheetsChangesInfoDTO in 'Common\Documents\Charge Sheets\Dtos\DocumentChargeSheetsChangesInfoDTO.pas',
  DocumentAcquaitanceSheetInfoDTODomainMapper in 'Common\Documents\Charge Sheets\Dtos\Mappers\DocumentAcquaitanceSheetInfoDTODomainMapper.pas',
  DocumentChargeSheetInfoDTODomainMapper in 'Common\Documents\Charge Sheets\Dtos\Mappers\DocumentChargeSheetInfoDTODomainMapper.pas',
  DocumentChargeSheetInfoDTODomainMapperRegistry in 'Common\Documents\Charge Sheets\Dtos\Mappers\DocumentChargeSheetInfoDTODomainMapperRegistry.pas',
  DocumentChargeSheetsInfoDTODomainMapper in 'Common\Documents\Charge Sheets\Dtos\Mappers\DocumentChargeSheetsInfoDTODomainMapper.pas',
  DocumentPerformingSheetInfoDTODomainMapper in 'Common\Documents\Charge Sheets\Dtos\Mappers\DocumentPerformingSheetInfoDTODomainMapper.pas',
  DocumentKindDto in 'Common\Documents\Document Kinds\DocumentKindDto.pas',
  DocumentKindWorkCycleInfoDto in 'Common\Documents\Document Kinds\DocumentKindWorkCycleInfoDto.pas',
  GlobalDocumentKindDto in 'Common\Documents\Document Kinds\GlobalDocumentKindDto.pas',
  NativeDocumentKindDto in 'Common\Documents\Document Kinds\NativeDocumentKindDto.pas',
  DocumentKindsMapper in 'Common\Documents\Document Kinds\Mappers\DocumentKindsMapper.pas',
  DocumentKindIdResolver in 'Common\Documents\Document Kinds\Resolvers\DocumentKindIdResolver.pas',
  DocumentKindResolver in 'Common\Documents\Document Kinds\Resolvers\DocumentKindResolver.pas',
  NumericDocumentKindIdResolver in 'Common\Documents\Document Kinds\Resolvers\NumericDocumentKindIdResolver.pas',
  NumericDocumentKindResolver in 'Common\Documents\Document Kinds\Resolvers\NumericDocumentKindResolver.pas',
  AbstractDocumentSetHolderDecorator in 'Common\Documents\Document List\AbstractDocumentSetHolderDecorator.pas',
  ApproveableDocumentSetHolder in 'Common\Documents\Document List\ApproveableDocumentSetHolder.pas',
  DepartmentDocumentSetHolder in 'Common\Documents\Document List\DepartmentDocumentSetHolder.pas',
  DocumentSetHolder in 'Common\Documents\Document List\DocumentSetHolder.pas',
  EmployeeDocumentSetHolder in 'Common\Documents\Document List\EmployeeDocumentSetHolder.pas',
  IncomingDocumentSetHolder in 'Common\Documents\Document List\IncomingDocumentSetHolder.pas',
  InternalDocumentSetHolder in 'Common\Documents\Document List\InternalDocumentSetHolder.pas',
  OutcomingDocumentSetHolder in 'Common\Documents\Document List\OutcomingDocumentSetHolder.pas',
  AbstractDocumentSetHolderFactoryDecorator in 'Common\Documents\Document List\Factories\AbstractDocumentSetHolderFactoryDecorator.pas',
  ApproveableDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\ApproveableDocumentSetHolderFactory.pas',
  DepartmentDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\DepartmentDocumentSetHolderFactory.pas',
  DocumentSetHolderFactory in 'Common\Documents\Document List\Factories\DocumentSetHolderFactory.pas',
  EmployeeDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\EmployeeDocumentSetHolderFactory.pas',
  IncomingDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\IncomingDocumentSetHolderFactory.pas',
  InternalDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\InternalDocumentSetHolderFactory.pas',
  OutcomingDocumentSetHolderFactory in 'Common\Documents\Document List\Factories\OutcomingDocumentSetHolderFactory.pas',
  ChangedDocumentInfoDTO in 'Common\Documents\Dtos\ChangedDocumentInfoDTO.pas',
  DocumentApprovingCycleDTO in 'Common\Documents\Dtos\DocumentApprovingCycleDTO.pas',
  DocumentChargeSheetsInfoDTO in 'Common\Documents\Dtos\DocumentChargeSheetsInfoDTO.pas',
  DocumentCreatingDefaultInfoDataSetHolder in 'Common\Documents\Dtos\DocumentCreatingDefaultInfoDataSetHolder.pas',
  DocumentCreatingDefaultInfoDTO in 'Common\Documents\Dtos\DocumentCreatingDefaultInfoDTO.pas',
  DocumentFullInfoDTO in 'Common\Documents\Dtos\DocumentFullInfoDTO.pas',
  DocumentResponsibleInfoDTO in 'Common\Documents\Dtos\DocumentResponsibleInfoDTO.pas',
  DocumentUsageEmployeeAccessRightsInfoDTO in 'Common\Documents\Dtos\DocumentUsageEmployeeAccessRightsInfoDTO.pas',
  EmployeeDocumentKindAccessRightsInfoDto in 'Common\Documents\Dtos\EmployeeDocumentKindAccessRightsInfoDto.pas',
  IncomingDocumentFullInfoDTO in 'Common\Documents\Dtos\IncomingDocumentFullInfoDTO.pas',
  NewDocumentInfoDTO in 'Common\Documents\Dtos\NewDocumentInfoDTO.pas',
  DocumentApprovingsInfoDTOMapper in 'Common\Documents\Dtos\Mappers\DocumentApprovingsInfoDTOMapper.pas',
  DocumentChargeInfoDTODomainMapper in 'Common\Documents\Dtos\Mappers\DocumentChargeInfoDTODomainMapper.pas',
  DocumentChargesInfoDTODomainMapper in 'Common\Documents\Dtos\Mappers\DocumentChargesInfoDTODomainMapper.pas',
  DocumentDTOMapper in 'Common\Documents\Dtos\Mappers\DocumentDTOMapper.pas',
  DocumentFullInfoDTOMapper in 'Common\Documents\Dtos\Mappers\DocumentFullInfoDTOMapper.pas',
  DocumentObjectsDTODomainMapper in 'Common\Documents\Dtos\Mappers\DocumentObjectsDTODomainMapper.pas',
  DocumentResponsibleInfoDTOMapper in 'Common\Documents\Dtos\Mappers\DocumentResponsibleInfoDTOMapper.pas',
  DocumentUsageEmployeeAccessRightsInfoDTOMapper in 'Common\Documents\Dtos\Mappers\DocumentUsageEmployeeAccessRightsInfoDTOMapper.pas',
  IncomingDocumentDTOMapper in 'Common\Documents\Dtos\Mappers\IncomingDocumentDTOMapper.pas',
  IncomingDocumentFullInfoDTOMapper in 'Common\Documents\Dtos\Mappers\IncomingDocumentFullInfoDTOMapper.pas',
  DocumentChargeInfoDTODomainMapperRegistry in 'Common\Documents\Dtos\Mappers\Registries\DocumentChargeInfoDTODomainMapperRegistry.pas',
  PersonnelOrderSubKindSetHolder in 'Common\Documents\Personnel Orders\Document Kinds\PersonnelOrderSubKindSetHolder.pas',
  PersonnelOrderSetHolder in 'Common\Documents\Personnel Orders\Document List\PersonnelOrderSetHolder.pas',
  PersonnelOrderSetHolderFactory in 'Common\Documents\Personnel Orders\Document List\Factories\PersonnelOrderSetHolderFactory.pas',
  ChangedPersonnelOrderDto in 'Common\Documents\Personnel Orders\Dtos\ChangedPersonnelOrderDto.pas',
  PersonnelOrderFullInfoDTO in 'Common\Documents\Personnel Orders\Dtos\PersonnelOrderFullInfoDTO.pas',
  DocumentApprovingListDTO in 'Common\Documents\Reporting\Dtos\DocumentApprovingListDTO.pas',
  DocumentApprovingSheetDataDto in 'Common\Documents\Reporting\Dtos\DocumentApprovingSheetDataDto.pas',
  NotPerformedDocumentsReportData in 'Common\Documents\Reporting\Dtos\NotPerformedDocumentsReportData.pas',
  NotPerformedIncomingDocumentsReportData in 'Common\Documents\Reporting\Dtos\NotPerformedIncomingDocumentsReportData.pas',
  DocumentApprovingSheetDataDtoMapper in 'Common\Documents\Reporting\Dtos\Mappers\DocumentApprovingSheetDataDtoMapper.pas',
  DepartmentInfoDTO in 'Common\Employees\Dtos\DepartmentInfoDTO.pas',
  DepartmentSetHolder in 'Common\Employees\Dtos\DepartmentSetHolder.pas',
  DocumentFlowEmployeeInfoDTO in 'Common\Employees\Dtos\DocumentFlowEmployeeInfoDTO.pas',
  EmployeeChargePerformingUnitDto in 'Common\Employees\Dtos\EmployeeChargePerformingUnitDto.pas',
  EmployeeInfoDTO in 'Common\Employees\Dtos\EmployeeInfoDTO.pas',
  EmployeeSetHolder in 'Common\Employees\Dtos\EmployeeSetHolder.pas',
  EmployeeStaffDto in 'Common\Employees\Dtos\EmployeeStaffDto.pas',
  DocumentFlowEmployeeInfoDTOMapper in 'Common\Employees\Dtos\Mappers\DocumentFlowEmployeeInfoDTOMapper.pas',
  PersonnelOrderDTODomainMapper in 'Common\Documents\Personnel Orders\Dtos\Mappers\PersonnelOrderDTODomainMapper.pas',
  DocumentAcquaitanceInfoDTODomainMapper in 'Common\Documents\Dtos\Mappers\DocumentAcquaitanceInfoDTODomainMapper.pas',
  DocumentPerformingInfoDTODomainMapper in 'Common\Documents\Dtos\Mappers\DocumentPerformingInfoDTODomainMapper.pas',
  DTODomainMapperRegistry in 'Common\Documents\Dtos\Mappers\Registries\DTODomainMapperRegistry.pas',
  DTODomainMapperRegistryConfigurator in 'Common\Documents\Dtos\Mappers\Registries\DTODomainMapperRegistryConfigurator.pas',
  DocumentChargeKindDto in 'Common\Documents\Charges\Dtos\DocumentChargeKindDto.pas',
  DocumentChargeKindDtoDomainMapper in 'Common\Documents\Charges\Dtos\Mappers\DocumentChargeKindDtoDomainMapper.pas',
  DocumentChargeKindsControlAppService in 'Business Processes\Docs\Common\Charges\Interfaces\DocumentChargeKindsControlAppService.pas',
  StandardDocumentChargeKindsControlAppService in 'Business Processes\Docs\Common\Charges\StandardDocumentChargeKindsControlAppService.pas',
  StandardDocumentSigningMarkingToPerformingAppService in 'Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningMarkingToPerformingAppService.pas',
  StandardDocumentChargeSheetPerformerSetReadService in 'Presentation\Docs\References\Document Actors\Standard\StandardDocumentChargeSheetPerformerSetReadService.pas',
  DocumentChargeSheetPerformerSetReadService in 'Presentation\Docs\References\Document Actors\Interfaces\DocumentChargeSheetPerformerSetReadService.pas',
  BasedOnDBApplicationVersionInfoService in 'Notifications\VersionInfo\BasedOnDBApplicationVersionInfoService.pas',
  VersionInfoDTOs in 'Notifications\VersionInfo\Dto\VersionInfoDTOs.pas',
  ApplicationVersionInfoService in 'Notifications\VersionInfo\Interfaces\ApplicationVersionInfoService.pas',
  NotificationRegistry in 'Notifications\NotificationRegistry.pas',
  ResourceRequestsItemService in 'External\ResourceRequests\ResourceRequestsItemService.pas',
  ResourceRequestsAccessService in 'External\ResourceRequests\ResourceRequestsAccessService.pas',
  BasedOnDBDocumentFlowItemStatisticsService in 'Statistics\Integration\Based-On DB\BasedOnDBDocumentFlowItemStatisticsService.pas',
  AbstractDocumentFlowItemStatistics in 'Statistics\Integration\Interfaces\AbstractDocumentFlowItemStatistics.pas',
  AbstractDocumentFlowItemStatisticsService in 'Statistics\Integration\Interfaces\AbstractDocumentFlowItemStatisticsService.pas',
  BasedOnZeosResourceRequestsAccessService in 'External\ResourceRequests\External Implementations\DocumentFlow\BasedOnZeosResourceRequestsAccessService.pas',
  BasedOnZeosResourceRequestsItemStatisticsService in 'External\ResourceRequests\External Implementations\DocumentFlow\BasedOnZeosResourceRequestsItemStatisticsService.pas',
  BasedOnZeosVclResourceRequestsItemService in 'External\ResourceRequests\External Implementations\DocumentFlow\BasedOnZeosVclResourceRequestsItemService.pas',
  ResourceRequestsItemStatistics in 'External\ResourceRequests\External Implementations\DocumentFlow\ResourceRequestsItemStatistics.pas',
  EmployeeDocumentWorkStatisticsPostgresService in 'Statistics\Docs\Zeos-Based\Postgres\EmployeeDocumentWorkStatisticsPostgresService.pas',
  StandardDocumentStorageService in 'Business Processes\Docs\Common\Storage\StandardDocumentStorageService.pas',
  PostgresServiceNoteSubstitutedInfoQueryBuilder in 'Presentation\Docs\Service Notes\Cards\Doc Full Info\Based-On DB\Builders\Queries\Postgres\PostgresServiceNoteSubstitutedInfoQueryBuilder.pas',
  PostgresIncomingServiceNoteFullInfoFetchingQueryBuilder in 'Presentation\Docs\Service Notes\Cards\Doc Full Info\Based-On DB\Postgres\PostgresIncomingServiceNoteFullInfoFetchingQueryBuilder.pas',
  LoodsmanDocumentsUploadingAccessRightsService in 'External\Integration\Loodsman\Uploading\Interfaces\LoodsmanDocumentsUploadingAccessRightsService.pas',
  LoodsmanDocumentsUploadingAccessRights in 'External\Integration\Loodsman\Uploading\Dtos\LoodsmanDocumentsUploadingAccessRights.pas',
  BasedOnDatabaseLoodsmanDocumentsUploadingAccessRightsService in 'External\Integration\Loodsman\Uploading\Based-On DB\BasedOnDatabaseLoodsmanDocumentsUploadingAccessRightsService.pas',
  LoodsmanDocumentsUploadingAccessRightsTableDef in 'External\Integration\Loodsman\Uploading\Based-On DB\LoodsmanDocumentsUploadingAccessRightsTableDef.pas';

{$R *.res}

begin

  Forms.Application.Initialize;
  Forms.Application.Run;
  
end.
