unit ServiceNoteChargeSheetTable;

interface

const

  SERVICE_NOTE_CHARGE_SHEET_TABLE_NAME = 'doc.service_note_receivers';

  SERVICE_NOTE_CHARGE_SHEET_ID_FIELD = 'id';

  SERVICE_NOTE_CHARGE_SHEET_REAL_SENDER_EMPLOYEE_ID_FIELD = 'real_sender_employee_id';
  SERVICE_NOTE_CHARGE_SHEET_CHARGE_FIELD = 'charge';
  SERVICE_NOTE_CHARGE_SHEET_CHARGE_PERIOD_START_FIELD = 'charge_period_start';
  SERVICE_NOTE_CHARGE_SHEET_CHARGE_PERIOD_END_FIELD = 'charge_period_end';
  SERVICE_NOTE_CHARGE_SHEET_PERFORMER_ID_FIELD = 'employee_id';
  SERVICE_NOTE_CHARGE_SHEET_PERFORMER_RESPONSE_FIELD = 'comment';
  SERVICE_NOTE_CHARGE_SHEET_ACTUAL_PERFORMER_ID_FIELD = 'actual_performer_id';
  SERVICE_NOTE_CHARGE_SHEET_INCOMING_DOCUMENT_ID_FIELD = 'incoming_document_id';
  SERVICE_NOTE_CHARGE_SHEET_ORIGINAL_DOCUMENT_ID_FIELD = 'document_id';
  SERVICE_NOTE_CHARGE_SHEET_TOP_LEVEL_SENDER_ID_FIELD = 'top_level_charge_sheet_id';
  SERVICE_NOTE_CHARGE_SHEET_PERFORMING_DATE_FIELD = 'performing_date';
  SERVICE_NOTE_CHARGE_SHEET_CURRENT_WORK_CYCLE_STAGE_ID_FIELD = 'current_work_cycle_stage_id';
  SERVICE_NOTE_CHARGE_SHEET_IS_PERFORMER_FIELD = 'is_performer';
  
implementation

end.
