unit ServiceNoteApprovingsTable;

interface

const

  SERVICE_NOTE_APPROVINGS_TABLE_NAME = 'doc.service_note_approvings';

  SERVICE_NOTE_APPROVINGS_TABLE_ID_FIELD = 'id';
  SERVICE_NOTE_APPROVINGS_TABLE_DOCUMENT_ID_FIELD = 'document_id';
  SERVICE_NOTE_APPROVINGS_TABLE_PERFORMING_DATE_FIELD = 'performing_date';
  SERVICE_NOTE_APPROVINGS_TABLE_PERFORMING_RESULT_ID_FIELD = 'performing_result_id';
  SERVICE_NOTE_APPROVINGS_TABLE_APPROVER_ID_FIELD = 'approver_id';
  SERVICE_NOTE_APPROVINGS_TABLE_ACTUAL_PERFORMED_EMPLOYEE_ID_FIELD = 'actual_performed_employee_id';
  SERVICE_NOTE_APPROVINGS_TABLE_NOTE_FIELD = 'note';
  SERVICE_NOTE_APPROVINGS_TABLE_CYCLE_NUMBER_FIELD = 'cycle_number';

implementation

end.
