program DocumentFlow;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  ArrayTypes,
  madListModules,
  Forms,
  Classes,
  SysUtils,
  CommonControlStyles in 'Forms\Common\Styles\CommonControlStyles.pas',
  EmployeeCardFormUnit in 'Forms\Employees\Cards\Management\EmployeeCardFormUnit.pas' {EmployeeCardForm},
  ExceptionHandling in 'Exception Handling\ExceptionHandling.pas',
  DocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\DocumentReportPresenterRegistry.pas',
  IDocumentReportPresenterRegistryUnit in 'Reporting\Presenters\Registries\IDocumentReportPresenterRegistryUnit.pas',
  StandardDocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\StandardDocumentReportPresenterRegistry.pas',
  NotPerformedDocumentsReportShowCustomizeFormUnit in 'Forms\Documents\Reporting\NotPerformedDocumentsReportShowCustomizeFormUnit.pas' {NotPerformedDocumentsReportShowCustomizeForm},
  DepartmentViewModel in 'Forms\Documents\Reporting\View Models\DepartmentViewModel.pas',
  DocumentKindWorkCycleColors in 'Forms\Documents\Styles\DocumentKindWorkCycleColors.pas',
  UIApplicationConfigurator in 'Launching\Configuration\UIApplicationConfigurator.pas',
  ApplicationLauncher in 'Launching\ApplicationLauncher.pas',
  EmployeesReferenceFormUnit in 'Forms\Employees\References\EmployeesReferenceFormUnit.pas' {EmployeesReferenceForm},
  unScrollableFrame in 'Forms\Common\Frames\unScrollableFrame.pas' {ScrollableFrame: TFrame},
  unDocumentFlowCardInformationFrame in 'Forms\Common\Frames\unDocumentFlowCardInformationFrame.pas' {DocumentFlowCardInformationFrame: TFrame},
  unDocumentFlowInformationFrame in 'Forms\Common\Frames\unDocumentFlowInformationFrame.pas' {DocumentFlowInformationFrame: TFrame},
  unApplicationMainFrame in 'Forms\Common\Primary Screens\unApplicationMainFrame.pas' {ApplicationMainFrame: TFrame},
  unApplicationMainForm in 'Forms\Common\Primary Screens\unApplicationMainForm.pas' {ApplicationMainForm},
  unDocumentFlowAdministrationForm in 'Forms\System Administration\Primary Screens\unDocumentFlowAdministrationForm.pas' {DocumentFlowAdministrationForm},
  DocumentFlowAdministrationFormViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdministrationFormViewModel.pas',
  DocumentFlowAdminPrivilegeSetHolder in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeSetHolder.pas',
  DocumentFlowAdminPrivilegeViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeViewModel.pas',
  unAdminDocumentCardListFrame in 'Forms\System Administration\Primary Screens\unAdminDocumentCardListFrame.pas' {AdminDocumentCardListFrame: TFrame},
  unSelectionDepartmentsReferenceForm in 'Forms\Employees\References\unSelectionDepartmentsReferenceForm.pas' {SelectionDepartmentsReferenceForm},
  SelectionDepartmentsReferenceFormViewModel in 'Forms\Employees\References\View Models\SelectionDepartmentsReferenceFormViewModel.pas',
  SelectionDepartmentSetHolder in 'Forms\Employees\References\View Models\SelectionDepartmentSetHolder.pas',
  DepartmentRecordViewModel in 'Forms\Employees\References\View Models\DepartmentRecordViewModel.pas',
  frxNotPerformedDocumentsReportObjectsUnit in 'Reporting\Presenters\Not Performed Documents\FastReport\Data Modules\frxNotPerformedDocumentsReportObjectsUnit.pas' {frxNotPerformedDocumentsReportObjects: TDataModule},
  NotPerformedDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedDocumentsReportFastReportPresenter.pas',
  NotPerformedIncomingDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedIncomingDocumentsReportFastReportPresenter.pas',
  NotPerformedDocumentsReportPresenter in 'Reporting\Presenters\Not Performed Documents\Interfaces\NotPerformedDocumentsReportPresenter.pas',
  frxDocumentPrintFormReportsModule in 'Reporting\Presenters\Print Forms\FastReport\Data Modules\frxDocumentPrintFormReportsModule.pas' {frxDocumentPrintFormReports: TDataModule},
  ServiceNotePrintFormFastReportPresenter in 'Reporting\Presenters\Print Forms\FastReport\ServiceNotePrintFormFastReportPresenter.pas',
  DocumentPrintFormPresenter in 'Reporting\Presenters\Print Forms\Interfaces\DocumentPrintFormPresenter.pas',
  DocumentApprovingSheetPresenter in 'Reporting\Presenters\Approving Sheets\Interfaces\DocumentApprovingSheetPresenter.pas',
  DocumentApprovingSheetViewModel in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetViewModel.pas',
  DocumentApprovingSheetApprovingSetHolder in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetApprovingSetHolder.pas',
  unFastReportApprovingSheetDataModule in 'Reporting\Presenters\Approving Sheets\FastReport\Data Modules\unFastReportApprovingSheetDataModule.pas' {FastReportApprovingSheetDataModule: TDataModule},
  DocumentApprovingSheetViewModelMapper in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\DocumentApprovingSheetViewModelMapper.pas',
  DocumentApprovingSheetFastReportPresenter in 'Reporting\Presenters\Approving Sheets\FastReport\DocumentApprovingSheetFastReportPresenter.pas',
  DocumentApprovingSheetViewModelMapperFactory in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactory.pas',
  DocumentApprovingSheetViewModelMapperFactories in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactories.pas',
  unPersonnelOrderSubKindsReferenceForm in 'Forms\Documents\Personnel Orders\References\unPersonnelOrderSubKindsReferenceForm.pas' {PersonnelOrderSubKindsReferenceForm},
  ServiceNoteNumberColumnCellComparator in 'Forms\Documents\Service Notes\References\Document List\Column Cell Comparators\ServiceNoteNumberColumnCellComparator.pas',
  unApproveableServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unApproveableServiceNotesReferenceForm.pas' {ApproveableServiceNotesReferenceForm},
  unIncomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unIncomingServiceNotesReferenceForm.pas' {IncomingServiceNotesReferenceForm},
  unOutcomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unOutcomingServiceNotesReferenceForm.pas' {OutcomingServiceNotesReferenceForm},
  unPersonnelOrdersReferenceForm in 'Forms\Documents\Personnel Orders\References\Document List\unPersonnelOrdersReferenceForm.pas' {PersonnelOrdersReferenceForm},
  PersonnelOrderSubKindViewModel in 'Forms\Documents\Personnel Orders\References\View Models\PersonnelOrderSubKindViewModel.pas',
  PersonnelOrdersReferenceFormProcessor in 'Forms\Documents\Personnel Orders\References\Document List\Processors\PersonnelOrdersReferenceFormProcessor.pas',
  PersonnelOrderRecordViewModel in 'Forms\Documents\Personnel Orders\References\Document List\View Models\PersonnelOrderRecordViewModel.pas',
  DocumentApprovingListRecordSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListRecordSetHolder.pas',
  DocumentApprovingListSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListSetHolder.pas',
  ApplicationSettingsResetService in 'Launching\Settings\Services\Interfaces\ApplicationSettingsResetService.pas',
  AppDataLocalSettingsResetService in 'Launching\Settings\Services\Standard\AppDataLocalSettingsResetService.pas',
  AuxDebugFunctionsUnit,
  unUserNotificationsSettingsForm in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsForm.pas' {UserNotificationsSettingsForm},
  UserNotificationsSettingsFormViewModelMapper in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModelMapper.pas',
  UserNotificationsSettingsFormViewModel in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModel.pas',
  StandardDocumentFlowStyle in 'Forms\Common\Styles\StandardDocumentFlowStyle.pas',
  unUserNotificationsSettingsFrame in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsFrame.pas' {UserNotificationsSettingsFrame: TFrame},
  UserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\UserNotificationsSettingsFrameFactory.pas',
  ZeosPostgresUserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\ZeosPostgresUserNotificationsSettingsFrameFactory.pas',
  ZConnection,
  Controls,
  UserInterfaceSwitch in 'Forms\Common\Frames\UserInterfaceSwitch.pas',
  AuxFileFunctions,
  StandardApplicationSettingsResetService in 'Launching\Settings\Services\Standard\StandardApplicationSettingsResetService.pas',
  DocumentFlowBaseReferenceFormUnit in 'Forms\Common\References\DocumentFlowBaseReferenceFormUnit.pas' {DocumentFlowBaseReferenceForm},
  unVersionInfosForm in 'Forms\Common\Primary Screens\unVersionInfosForm.pas' {VersionInfosForm},
  unApplicationDataModule in 'Launching\Configuration\unApplicationDataModule.pas' {DocumentFlowAppDataModule: TDataModule},
  RegExprValidateEditUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateEditUnit.pas',
  RegExprValidateMemoUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateMemoUnit.pas',
  RegExprValidateRichEdit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateRichEdit.pas',
  SourcedEventHandlers in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\SourcedEventHandlers.pas',
  EventHandlerChains in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\EventHandlerChains.pas',
  DomainObjectRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\Interfaces\DomainObjectRepository.pas',
  AbstractDBRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\AbstractDBRepository.pas',
  PropertiesIniFileUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Properties Storages\PropertiesIniFileUnit.pas',
  DocumentApproversReferenceFormUnit in 'Forms\Documents\References\DocumentApproversReferenceFormUnit.pas' {DocumentApproversReferenceForm},
  DocumentApprovingCyclesReferenceFormUnit in 'Forms\Documents\References\DocumentApprovingCyclesReferenceFormUnit.pas' {DocumentApprovingCyclesReferenceForm},
  DocumentChargePerformersReferenceFormUnit in 'Forms\Documents\References\DocumentChargePerformersReferenceFormUnit.pas' {DocumentChargePerformersReferenceForm},
  DocumentFilesReferenceFormUnit in 'Forms\Documents\References\DocumentFilesReferenceFormUnit.pas' {DocumentFilesReferenceForm},
  DocumentRelationsReferenceFormUnit in 'Forms\Documents\References\DocumentRelationsReferenceFormUnit.pas' {DocumentRelationsReferenceForm},
  DocumentResponsiblesReferenceFormUnit in 'Forms\Documents\References\DocumentResponsiblesReferenceFormUnit.pas' {DocumentResponsiblesReferenceForm},
  DocumentSignersReferenceFormUnit in 'Forms\Documents\References\DocumentSignersReferenceFormUnit.pas' {DocumentSignersReferenceForm},
  unDocumentChargeSheetPerformersReferenceForm in 'Forms\Documents\References\unDocumentChargeSheetPerformersReferenceForm.pas' {DocumentChargeSheetPerformersReferenceForm},
  DocumentApprovingCycleSetHolder in 'Forms\Documents\References\View Models\DocumentApprovingCycleSetHolder.pas',
  DocumentChargeSetHolder in 'Forms\Documents\References\View Models\DocumentChargeSetHolder.pas',
  DocumentChargeSheetSetHolder in 'Forms\Documents\References\View Models\DocumentChargeSheetSetHolder.pas',
  DocumentFileSetHolder in 'Forms\Documents\References\View Models\DocumentFileSetHolder.pas',
  DocumentRelationSetHolder in 'Forms\Documents\References\View Models\DocumentRelationSetHolder.pas',
  DocumentApprovingCycleSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentApprovingCycleSetHolderFactory.pas',
  DocumentApprovingSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentApprovingSetHolderFactory.pas',
  DocumentChargeSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentChargeSetHolderFactory.pas',
  DocumentChargeSheetSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentChargeSheetSetHolderFactory.pas',
  DocumentDataSetHoldersFactories in 'Forms\Documents\References\View Models\Factories\DocumentDataSetHoldersFactories.pas',
  DocumentDataSetHoldersFactory in 'Forms\Documents\References\View Models\Factories\DocumentDataSetHoldersFactory.pas',
  DocumentFileSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentFileSetHolderFactory.pas',
  DocumentRelationSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentRelationSetHolderFactory.pas',
  DBDataTableFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\DBDataTableFormUnit.pas' {DBDataTableForm},
  TableViewFilterFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\TableViewFilterFormUnit.pas' {TableViewFilterForm},
  BaseApproveableDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseApproveableDocumentsReferenceFormUnit.pas' {BaseApproveableDocumentsReferenceForm},
  BaseDocumentsReferenceFilterFormUnit in 'Forms\Documents\References\Document List\BaseDocumentsReferenceFilterFormUnit.pas' {BaseDocumentsReferenceFilterForm},
  BaseDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseDocumentsReferenceFormUnit.pas' {BaseDocumentsReferenceForm},
  BaseIncomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseIncomingDocumentsReferenceFormUnit.pas' {BaseIncomingDocumentsReferenceForm},
  BaseOutcomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseOutcomingDocumentsReferenceFormUnit.pas' {BaseOutcomingDocumentsReferenceForm},
  ApproveableDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\ApproveableDocumentRecordViewModel.pas',
  DocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\DocumentRecordViewModel.pas',
  DocumentRecordViewModelDecorator in 'Forms\Documents\References\Document List\View Models\DocumentRecordViewModelDecorator.pas',
  DocumentsReferenceViewModel in 'Forms\Documents\References\Document List\View Models\DocumentsReferenceViewModel.pas',
  DocumentTableViewModel in 'Forms\Documents\References\Document List\View Models\DocumentTableViewModel.pas',
  EmployeeDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\EmployeeDocumentRecordViewModel.pas',
  IncomingDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\IncomingDocumentRecordViewModel.pas',
  OutcomingDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\OutcomingDocumentRecordViewModel.pas',
  DocumentsReferenceViewModelFactory in 'Forms\Documents\References\Document List\View Models\Factories\DocumentsReferenceViewModelFactory.pas',
  ApproveableDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\ApproveableDocumentsReferenceFormProcessor.pas',
  DepartmentDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\DepartmentDocumentsReferenceFormProcessor.pas',
  DocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\DocumentsReferenceFormProcessor.pas',
  DocumentsReferenceFormProcessorDecorator in 'Forms\Documents\References\Document List\Processors\DocumentsReferenceFormProcessorDecorator.pas',
  EmployeeDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\EmployeeDocumentsReferenceFormProcessor.pas',
  IncomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\IncomingDocumentsReferenceFormProcessor.pas',
  OutcomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\OutcomingDocumentsReferenceFormProcessor.pas',
  DepartmentDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\DepartmentDocumentsReferenceFormProcessorFactory.pas',
  DocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\DocumentsReferenceFormProcessorFactory.pas',
  EmployeeDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\EmployeeDocumentsReferenceFormProcessorFactory.pas',
  DocumentsReferenceFormPresenter in 'Forms\Documents\References\Document List\Presenters\Interfaces\DocumentsReferenceFormPresenter.pas',
  StandardDocumentsReferenceFormPresenter in 'Forms\Documents\References\Document List\Presenters\StandardDocumentsReferenceFormPresenter.pas',
  DocumentsReferenceForm in 'Forms\Documents\References\Document List\Interfaces\DocumentsReferenceForm.pas',
  DocumentsReferenceFormFactory in 'Forms\Documents\References\Document List\Factories\DocumentsReferenceFormFactory.pas',
  ColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\ColumnCellComparator.pas',
  DefaultColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\DefaultColumnCellComparator.pas',
  DocumentNumberColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\DocumentNumberColumnCellComparator.pas',
  DocumentKindsPanelController in 'Forms\Documents\Primary Screens\Document Kinds\DocumentKindsPanelController.pas',
  unDocumentKindsFrame in 'Forms\Documents\Primary Screens\Document Kinds\unDocumentKindsFrame.pas' {DocumentKindsFrame: TFrame},
  unDocumentCardInformationFrame in 'Forms\Documents\Frames\Common\unDocumentCardInformationFrame.pas' {DocumentCardInformationFrame: TFrame},
  InputMemoFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\User Input Forms\InputMemoFormUnit.pas' {InputMemoForm},
  DocumentFlowSystemInputMemoFormUnit in 'Forms\Common\Field-Targeted\DocumentFlowSystemInputMemoFormUnit.pas' {DocumentFlowSystemInputMemoForm},
  DocumentApproversInfoFormUnit in 'Forms\Documents\Frames\Approvings\DocumentApproversInfoFormUnit.pas' {DocumentApproversInfoForm},
  DocumentApprovingsFrameUnit in 'Forms\Documents\Frames\Approvings\DocumentApprovingsFrameUnit.pas' {DocumentApprovingsFrame: TFrame},
  unNotDocumentApprovingReasonInputForm in 'Forms\Documents\Frames\Approvings\unNotDocumentApprovingReasonInputForm.pas' {NotDocumentApprovingReasonInputForm},
  DocumentApprovingCycleViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingCycleViewModel.pas',
  DocumentApprovingsFormViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingsFormViewModel.pas',
  DocumentApprovingViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingViewModel.pas',
  DocumentCardFormUnit in 'Forms\Documents\Frames\Cards\DocumentCardFormUnit.pas' {DocumentCardForm},
  unDocumentCardFrame in 'Forms\Documents\Frames\Cards\unDocumentCardFrame.pas' {DocumentCardFrame: TFrame},
  DocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\DocumentCardFormViewModel.pas',
  EmployeeDocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\EmployeeDocumentCardFormViewModel.pas',
  IncomingDocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\IncomingDocumentCardFormViewModel.pas',
  DocumentCardFrameFactories in 'Forms\Documents\Frames\Cards\Factories\DocumentCardFrameFactories.pas',
  DocumentCardFrameFactory in 'Forms\Documents\Frames\Cards\Factories\DocumentCardFrameFactory.pas',
  IncomingDocumentCardFrameFactory in 'Forms\Documents\Frames\Cards\Factories\IncomingDocumentCardFrameFactory.pas',
  unDocumentChargesFrame in 'Forms\Documents\Frames\Charges\unDocumentChargesFrame.pas' {DocumentChargesFrame: TFrame},
  DocumentChargesFormViewModelUnit in 'Forms\Documents\Frames\Charges\View Models\DocumentChargesFormViewModelUnit.pas',
  unDocumentChargeSheetsFrame in 'Forms\Documents\Frames\Charge Sheets\unDocumentChargeSheetsFrame.pas' {DocumentChargeSheetsFrame: TFrame},
  DocumentChargeSheetsFormViewModel in 'Forms\Documents\Frames\Charge Sheets\View Models\DocumentChargeSheetsFormViewModel.pas',
  DocumentFilesFrameUnit in 'Forms\Documents\Frames\Files\DocumentFilesFrameUnit.pas' {DocumentFilesFrame: TFrame},
  DocumentFilesViewFrameUnit in 'Forms\Documents\Frames\Files\DocumentFilesViewFrameUnit.pas' {DocumentFilesViewFrame: TFrame},
  DocumentFlowPDFViewFormUnit in 'Forms\Documents\Frames\Files\DocumentFlowPDFViewFormUnit.pas' {DocumentFlowPDFViewForm},
  DocumentFileInfoList in 'Forms\Documents\Frames\Files\View Models\DocumentFileInfoList.pas',
  DocumentFilesFormViewModelUnit in 'Forms\Documents\Frames\Files\View Models\DocumentFilesFormViewModelUnit.pas',
  DocumentFilesViewFormViewModel in 'Forms\Documents\Frames\Files\View Models\DocumentFilesViewFormViewModel.pas',
  DocumentMainInformationFrameUnit in 'Forms\Documents\Frames\Main Info\DocumentMainInformationFrameUnit.pas' {DocumentMainInformationFrame: TFrame},
  ExtendedDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\Main Info\ExtendedDocumentMainInformationFrameUnit.pas' {ExtendedDocumentMainInformationFrame: TFrame},
  DocumentOperationToolBarFrameUnit in 'Forms\Documents\Frames\Operations\DocumentOperationToolBarFrameUnit.pas' {DocumentOperationToolBarFrame: TFrame},
  DocumentRelationsFrameUnit in 'Forms\Documents\Frames\Relations\DocumentRelationsFrameUnit.pas' {DocumentRelationsFrame: TFrame},
  DocumentRelationsFormViewModelUnit in 'Forms\Documents\Frames\Relations\View Models\DocumentRelationsFormViewModelUnit.pas',
  unServiceNoteCardFrame in 'Forms\Documents\Service Notes\Frames\Cards\unServiceNoteCardFrame.pas' {ServiceNoteCardFrame: TFrame},
  ServiceNoteCardFrameFactory in 'Forms\Documents\Service Notes\Frames\Cards\Factories\ServiceNoteCardFrameFactory.pas',
  unServiceNoteChargeSheetsFrame in 'Forms\Documents\Service Notes\Frames\Charge Sheets\unServiceNoteChargeSheetsFrame.pas' {ServiceNoteChargeSheetsFrame: TFrame},
  unServiceNoteChargesFrame in 'Forms\Documents\Service Notes\Frames\Charges\unServiceNoteChargesFrame.pas' {ServiceNoteChargesFrame: TFrame},
  unPersonnelOrderApprovingsFrame in 'Forms\Documents\Personnel Orders\Frames\Approvings\unPersonnelOrderApprovingsFrame.pas' {PersonnelOrderApprovingsFrame: TFrame},
  unPersonnelOrderCardFrame in 'Forms\Documents\Personnel Orders\Frames\Cards\unPersonnelOrderCardFrame.pas' {PersonnelOrderCardFrame: TFrame},
  PersonnelOrderCardFormViewModel in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\PersonnelOrderCardFormViewModel.pas',
  PersonnelOrderCardFormViewModelMapper in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapper.pas',
  PersonnelOrderCardFormViewModelMapperFactory in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapperFactory.pas',
  PersonnelOrderCardFrameFactory in 'Forms\Documents\Personnel Orders\Frames\Cards\Factories\PersonnelOrderCardFrameFactory.pas',
  unPersonnelOrderChargeSheetsFrame in 'Forms\Documents\Personnel Orders\Frames\Charge Sheets\unPersonnelOrderChargeSheetsFrame.pas' {PersonnelOrderChargeSheetsFrame: TFrame},
  unPersonnelOrderChargesFrame in 'Forms\Documents\Personnel Orders\Frames\Charges\unPersonnelOrderChargesFrame.pas' {PersonnelOrderChargesFrame: TFrame},
  unPersonnelOrderMainInformationFrame in 'Forms\Documents\Personnel Orders\Frames\Main Info\unPersonnelOrderMainInformationFrame.pas' {PersonnelOrderMainInformationFrame: TFrame},
  PersonnelOrderMainInformationFormViewModel in 'Forms\Documents\Personnel Orders\Frames\Main Info\View Models\PersonnelOrderMainInformationFormViewModel.pas',
  PersonnelOrderMainInformationFormViewModelMapper in 'Forms\Documents\Personnel Orders\Frames\Main Info\View Models\Mappers\PersonnelOrderMainInformationFormViewModelMapper.pas',
  DocumentKindSetHolder in 'Forms\Documents\Primary Screens\Document Kinds\View Models\DocumentKindSetHolder.pas',
  DocumentKindsFormViewModel in 'Forms\Documents\Primary Screens\Document Kinds\View Models\DocumentKindsFormViewModel.pas',
  LoodsmanDocumentUploadingInfoFormViewModel in 'Forms\Documents\Frames\Loodsman\Uploading\LoodsmanDocumentUploadingInfoFormViewModel.pas',
  DocumentApprovingListRecordSetHolderFactory in 'Reporting\Presenters\Print Forms\View Models\Factories\DocumentApprovingListRecordSetHolderFactory.pas',
  DocumentApprovingListSetHolderFactory in 'Reporting\Presenters\Print Forms\View Models\Factories\DocumentApprovingListSetHolderFactory.pas',
  OperationalDocumentKindInfo in 'Application Binding\OperationalDocumentKindInfo.pas',
  UIDocumentKinds in 'Application Binding\UIDocumentKinds.pas',
  UIDocumentKindResolver in 'Application Binding\Resolvers\Interfaces\UIDocumentKindResolver.pas',
  UINativeDocumentKindResolver in 'Application Binding\Resolvers\Interfaces\UINativeDocumentKindResolver.pas',
  StandardUIDocumentKindResolver in 'Application Binding\Resolvers\StandardUIDocumentKindResolver.pas',
  StandardUINativeDocumentKindResolver in 'Application Binding\Resolvers\StandardUINativeDocumentKindResolver.pas',
  UIDocumentKindMapper in 'Application Binding\Mappers\Interfaces\UIDocumentKindMapper.pas',
  StandardUIDocumentKindMapper in 'Application Binding\Mappers\StandardUIDocumentKindMapper.pas',
  DocumentApprovingListSetHolderMapper in 'Reporting\Presenters\Print Forms\View Models\Mappers\DocumentApprovingListSetHolderMapper.pas',
  DocumentFlowInformationFramePropertiesStorage in 'Forms\Common\Frames\Settings\DocumentFlowInformationFramePropertiesStorage.pas',
  DocumentFlowAdminFormViewModelMapper in 'Forms\System Administration\Primary Screens\View Models\Mappers\DocumentFlowAdminFormViewModelMapper.pas',
  DocumentApprovingsFormViewModelMapper in 'Forms\Documents\Frames\Approvings\View Models\Mappers\DocumentApprovingsFormViewModelMapper.pas',
  DocumentCardFormViewModelMapper in 'Forms\Documents\Frames\Cards\View Models\Mappers\DocumentCardFormViewModelMapper.pas',
  DocumentCardFormViewModelMapperFactories in 'Forms\Documents\Frames\Cards\View Models\Mappers\DocumentCardFormViewModelMapperFactories.pas',
  DocumentCardFormViewModelMapperFactory in 'Forms\Documents\Frames\Cards\View Models\Mappers\DocumentCardFormViewModelMapperFactory.pas',
  EmployeeDocumentCardFormViewModelMapper in 'Forms\Documents\Frames\Cards\View Models\Mappers\EmployeeDocumentCardFormViewModelMapper.pas',
  EmployeeDocumentCardFormViewModelMapperFactory in 'Forms\Documents\Frames\Cards\View Models\Mappers\EmployeeDocumentCardFormViewModelMapperFactory.pas',
  IncomingDocumentCardFormViewModelMapper in 'Forms\Documents\Frames\Cards\View Models\Mappers\IncomingDocumentCardFormViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapperFactory in 'Forms\Documents\Frames\Cards\View Models\Mappers\IncomingDocumentCardFormViewModelMapperFactory.pas',
  DocumentCardFramePropertiesIniFile in 'Forms\Documents\Frames\Cards\Settings\DocumentCardFramePropertiesIniFile.pas',
  DocumentCardFramePropertiesStorage in 'Forms\Documents\Frames\Cards\Settings\DocumentCardFramePropertiesStorage.pas',
  DocumentChargeSheetsChangesInfoDTOMapper in 'Forms\Documents\Frames\Charge Sheets\DTOs Mappers\DocumentChargeSheetsChangesInfoDTOMapper.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactories in 'Forms\Documents\Frames\Charge Sheets\DTOs Mappers\DocumentChargeSheetsChangesInfoDTOMapperFactories.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactory in 'Forms\Documents\Frames\Charge Sheets\DTOs Mappers\DocumentChargeSheetsChangesInfoDTOMapperFactory.pas',
  DocumentChargeSheetsFormViewModelMapper in 'Forms\Documents\Frames\Charge Sheets\View Models\Mappers\DocumentChargeSheetsFormViewModelMapper.pas',
  DocumentChargesFramePropertiesIniFile in 'Forms\Documents\Frames\Charges\Settings\DocumentChargesFramePropertiesIniFile.pas',
  DocumentChargesFramePropertiesStorage in 'Forms\Documents\Frames\Charges\Settings\DocumentChargesFramePropertiesStorage.pas',
  DocumentChargesFormViewModelMapper in 'Forms\Documents\Frames\Charges\View Models\Mappers\DocumentChargesFormViewModelMapper.pas',
  StandardDocumentFlowInformationFramePropertiesStorage in 'Forms\Documents\Frames\Common\Settings\StandardDocumentFlowInformationFramePropertiesStorage.pas',
  DocumentFilesFormViewModelMapper in 'Forms\Documents\Frames\Files\View Models\Mappers\DocumentFilesFormViewModelMapper.pas',
  DocumentFilesViewFormViewModelMapper in 'Forms\Documents\Frames\Files\View Models\Mappers\DocumentFilesViewFormViewModelMapper.pas',
  LoodsmanDocumentUploadingInfoFormViewModelMapper in 'Forms\Documents\Frames\Loodsman\Uploading\LoodsmanDocumentUploadingInfoFormViewModelMapper.pas',
  DocumentMainInformationFormViewModelMapper in 'Forms\Documents\Frames\Main Info\View Models\Mappers\DocumentMainInformationFormViewModelMapper.pas',
  DocumentResponsibleViewModelMapper in 'Forms\Documents\Frames\Main Info\View Models\Mappers\DocumentResponsibleViewModelMapper.pas',
  DocumentSignerViewModelMapper in 'Forms\Documents\Frames\Main Info\View Models\Mappers\DocumentSignerViewModelMapper.pas',
  DocumentMainInformationFormViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentMainInformationFormViewModelUnit.pas',
  DocumentResponsibleViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentResponsibleViewModelUnit.pas',
  DocumentSignerViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentSignerViewModelUnit.pas',
  IncomingDocumentMainInformationFormViewModel in 'Forms\Documents\Frames\Main Info\View Models\IncomingDocumentMainInformationFormViewModel.pas',
  IncomingDocumentMainInformationFormViewModelMapper in 'Forms\Documents\Frames\Main Info\View Models\IncomingDocumentMainInformationFormViewModelMapper.pas',
  DocumentRelationsFormViewModelMapper in 'Forms\Documents\Frames\Relations\View Models\Mappers\DocumentRelationsFormViewModelMapper.pas',
  unDocumentFlowWorkingFrame in 'Forms\Documents\Primary Screens\Common\unDocumentFlowWorkingFrame.pas' {DocumentFlowWorkingFrame: TFrame},
  unDocumentCardListFrame in 'Forms\Documents\Primary Screens\Document Card List\unDocumentCardListFrame.pas' {DocumentCardListFrame: TFrame},
  unSelectionDocumentCardListFrame in 'Forms\Documents\Primary Screens\Document Card List\unSelectionDocumentCardListFrame.pas' {SelectionDocumentCardListFrame: TFrame},
  unSelectionDocumentsForm in 'Forms\Documents\Primary Screens\Document Card List\unSelectionDocumentsForm.pas' {SelectionDocumentsForm},
  unSelectionDocumentsWorkingFrame in 'Forms\Documents\Primary Screens\Document Card List\unSelectionDocumentsWorkingFrame.pas' {SelectionDocumentsWorkingFrame: TFrame},
  DocumentCardListFramePropertiesIniFile in 'Forms\Documents\Primary Screens\Document Card List\Settings\DocumentCardListFramePropertiesIniFile.pas',
  DocumentCardListFramePropertiesStorage in 'Forms\Documents\Primary Screens\Document Card List\Settings\DocumentCardListFramePropertiesStorage.pas',
  DocumentKindsFormViewModelMapper in 'Forms\Documents\Primary Screens\Document Kinds\View Models\Mappers\DocumentKindsFormViewModelMapper.pas',
  DocumentKindsFramePropertiesIniFile in 'Forms\Documents\Primary Screens\Document Kinds\Settings\DocumentKindsFramePropertiesIniFile.pas',
  DocumentKindsFramePropertiesStorage in 'Forms\Documents\Primary Screens\Document Kinds\Settings\DocumentKindsFramePropertiesStorage.pas',
  ApplicationPropertiesStorageRegistry in 'Forms\Documents\Settings\ApplicationPropertiesStorageRegistry.pas',
  DocumentRecordsPanelSettingsFormPropertiesIniFile in 'Forms\Documents\Settings\Document List\DocumentRecordsPanelSettingsFormPropertiesIniFile.pas',
  DocumentRecordsPanelSettingsFormPropertiesStorage in 'Forms\Documents\Settings\Document List\DocumentRecordsPanelSettingsFormPropertiesStorage.pas',
  DeletableOnCloseFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DeletableOnCloseFormUnit.pas' {DeletableOnCloseForm},
  DocumentRecordsPanelSettingsFormUnit in 'Forms\Documents\Settings\Document List\DocumentRecordsPanelSettingsFormUnit.pas' {DocumentRecordsPanelSettingsForm},
  IncomingServiceNoteCardFormViewModelMapper in 'Forms\Documents\Service Notes\Frames\Cards\View Models\Mappers\IncomingServiceNoteCardFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapperFactory in 'Forms\Documents\Service Notes\Frames\Cards\View Models\Mappers\IncomingServiceNoteCardFormViewModelMapperFactory.pas',
  OutcomingServiceNoteCardFormViewModelMapper in 'Forms\Documents\Service Notes\Frames\Cards\View Models\Mappers\OutcomingServiceNoteCardFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapperFactory in 'Forms\Documents\Service Notes\Frames\Cards\View Models\Mappers\OutcomingServiceNoteCardFormViewModelMapperFactory.pas',
  IncomingServiceNoteMainInformationFormViewModelMapper in 'Forms\Documents\Service Notes\Frames\Main Info\View Models\Mappers\IncomingServiceNoteMainInformationFormViewModelMapper.pas',
  OutcomingServiceNoteMainInformationFormViewModelMapper in 'Forms\Documents\Service Notes\Frames\Main Info\View Models\Mappers\OutcomingServiceNoteMainInformationFormViewModelMapper.pas',
  SelectionDepartmentsReferenceFormViewModelMapper in 'Forms\Employees\References\View Models\Mappers\SelectionDepartmentsReferenceFormViewModelMapper.pas',
  DocumentsReferenceFilterFormStatePropertiesIniFile in 'Forms\Documents\References\Document List\Settings\DocumentsReferenceFilterFormStatePropertiesIniFile.pas',
  DocumentsReferenceFormPropertiesIniFile in 'Forms\Documents\References\Document List\Settings\DocumentsReferenceFormPropertiesIniFile.pas',
  ApplicationMainFramePropertiesIniFile in 'Forms\Common\Primary Screens\Settings\ApplicationMainFramePropertiesIniFile.pas',
  ApplicationMainFramePropertiesStorage in 'Forms\Common\Primary Screens\Settings\ApplicationMainFramePropertiesStorage.pas';

{$R *.res}

var
    ApplicationLauncher: TApplicationLauncher;
begin

  //ReportMemoryLeaksOnShutdown := True;

  try

    ApplicationLauncher :=
      TApplicationLauncher.Create(
        TUIApplicationConfigurator.Create
      );

    ApplicationLauncher.Launch;

  finally

    FreeAndNil(ApplicationLauncher);

  end;  

end.
