program DocumentFlow;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  ArrayTypes,
  madListModules,
  Forms,
  Classes,
  SysUtils,
  Controller in 'Controllers\Controller.pas',
  EmployeeDocumentsReferenceFormController in 'Controllers\EmployeeDocumentsReferenceFormController.pas',
  DocumentApprovingsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingsFormViewModelMapper.pas',
  DocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapper.pas',
  DocumentCardFormViewModelMapperFactories in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactories.pas',
  DocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactory.pas',
  DocumentChargesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentChargesFormViewModelMapper.pas',
  DocumentFilesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesFormViewModelMapper.pas',
  DocumentFilesViewFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesViewFormViewModelMapper.pas',
  DocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentMainInformationFormViewModelMapper.pas',
  DocumentRelationsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentRelationsFormViewModelMapper.pas',
  DocumentResponsibleViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentResponsibleViewModelMapper.pas',
  DocumentSignerViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentSignerViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapperFactory.pas',
  IncomingDocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentMainInformationFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapperFactory.pas',
  IncomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteMainInformationFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapperFactory.pas',
  OutcomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteMainInformationFormViewModelMapper.pas',
  IncomingDocumentMainInformationFormViewModel in 'Forms\Documents\Frames\View Models\IncomingDocumentMainInformationFormViewModel.pas',
  DocumentApprovingsFormViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingsFormViewModel.pas',
  DocumentApprovingViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingViewModel.pas',
  DocumentFileInfoList in 'Forms\Documents\Frames\View Models\DocumentFileInfoList.pas',
  DocumentFilesFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentFilesFormViewModelUnit.pas',
  DocumentFilesViewFormViewModel in 'Forms\Documents\Frames\View Models\DocumentFilesViewFormViewModel.pas',
  DocumentMainInformationFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentMainInformationFormViewModelUnit.pas',
  DocumentRelationsFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentRelationsFormViewModelUnit.pas',
  DocumentResponsibleViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentResponsibleViewModelUnit.pas',
  DocumentSignerViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentSignerViewModelUnit.pas',
  DocumentApproversInfoFormUnit in 'Forms\Documents\Frames\DocumentApproversInfoFormUnit.pas' {DocumentApproversInfoForm},
  DocumentFlowPDFViewFormUnit in 'Forms\Documents\Frames\DocumentFlowPDFViewFormUnit.pas' {DocumentFlowPDFViewForm},
  IncomingDocumentCardFormViewModel in 'Forms\Documents\Cards\Common\View Models\IncomingDocumentCardFormViewModel.pas',
  DocumentCardFrameFactories in 'Forms\Documents\Cards\Common\Factories\DocumentCardFrameFactories.pas',
  DocumentCardFrameFactory in 'Forms\Documents\Cards\Common\Factories\DocumentCardFrameFactory.pas',
  DocumentCardFormUnit in 'Forms\Documents\Cards\Common\DocumentCardFormUnit.pas' {DocumentCardForm},
  DocumentFlowSystemInputMemoFormUnit in 'Forms\Common\Field-Targeted\DocumentFlowSystemInputMemoFormUnit.pas' {DocumentFlowSystemInputMemoForm},
  CommonControlStyles in 'Forms\Common\Styles\CommonControlStyles.pas',
  EmployeeCardFormUnit in 'Forms\Employees\Cards\Management\EmployeeCardFormUnit.pas' {EmployeeCardForm},
  DocumentChargeSheetsChangesInfoDTOMapper in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapper.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactories in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactories.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactory in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactory.pas',
  UIDocumentKinds in 'Document Kinds\UIDocumentKinds.pas',
  UIDocumentKindResolver in 'Document Kinds\Resolvers\Interfaces\UIDocumentKindResolver.pas',
  ExceptionHandling in 'Exception Handling\ExceptionHandling.pas',
  DocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\DocumentReportPresenterRegistry.pas',
  IDocumentReportPresenterRegistryUnit in 'Reporting\Presenters\Registries\IDocumentReportPresenterRegistryUnit.pas',
  StandardDocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\StandardDocumentReportPresenterRegistry.pas',
  NotPerformedDocumentsReportShowCustomizeFormUnit in 'Forms\Documents\Reporting\NotPerformedDocumentsReportShowCustomizeFormUnit.pas' {NotPerformedDocumentsReportShowCustomizeForm},
  DepartmentViewModel in 'Forms\Documents\Reporting\View Models\DepartmentViewModel.pas',
  DocumentKindWorkCycleColors in 'Forms\Documents\Styles\DocumentKindWorkCycleColors.pas',
  UIApplicationConfigurator in 'Launching\Configuration\UIApplicationConfigurator.pas',
  ApplicationLauncher in 'Launching\ApplicationLauncher.pas',
  DocumentRecordsPanelSettingsFormUnit in 'Forms\Documents\Settings\DocumentRecordsPanelSettingsFormUnit.pas' {DocumentRecordsPanelSettingsForm},
  DocumentOperationToolBarFrameUnit in 'Forms\Documents\Frames\DocumentOperationToolBarFrameUnit.pas' {DocumentOperationToolBarFrame: TFrame},
  DocumentApprovingCycleViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingCycleViewModel.pas',
  unNotDocumentApprovingReasonInputForm in 'Forms\Documents\Frames\unNotDocumentApprovingReasonInputForm.pas' {NotDocumentApprovingReasonInputForm},
  EmployeesReferenceFormUnit in 'Forms\Employees\References\EmployeesReferenceFormUnit.pas' {EmployeesReferenceForm},
  DocumentApproversReferenceFormUnit in 'Forms\Documents\References\Common\DocumentApproversReferenceFormUnit.pas' {DocumentApproversReferenceForm},
  DocumentApprovingCyclesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentApprovingCyclesReferenceFormUnit.pas' {DocumentApprovingCyclesReferenceForm},
  DocumentChargePerformersReferenceFormUnit in 'Forms\Documents\References\Common\DocumentChargePerformersReferenceFormUnit.pas' {DocumentChargePerformersReferenceForm},
  DocumentFilesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentFilesReferenceFormUnit.pas' {DocumentFilesReferenceForm},
  DocumentRelationsReferenceFormUnit in 'Forms\Documents\References\Common\DocumentRelationsReferenceFormUnit.pas' {DocumentRelationsReferenceForm},
  DocumentResponsiblesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentResponsiblesReferenceFormUnit.pas' {DocumentResponsiblesReferenceForm},
  DocumentSignersReferenceFormUnit in 'Forms\Documents\References\Common\DocumentSignersReferenceFormUnit.pas' {DocumentSignersReferenceForm},
  DocumentChargesFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentChargesFormViewModelUnit.pas',
  DocumentKindsFormViewModel in 'Forms\Documents\Primary Screens\View Models\DocumentKindsFormViewModel.pas',
  DocumentKindsFormViewModelMapper in 'ViewModel Mappers\Documents\References\Document Kinds\DocumentKindsFormViewModelMapper.pas',
  StandardUIDocumentKindResolver in 'Document Kinds\Resolvers\StandardUIDocumentKindResolver.pas',
  UINativeDocumentKindResolver in 'Document Kinds\Resolvers\Interfaces\UINativeDocumentKindResolver.pas',
  StandardUINativeDocumentKindResolver in 'Document Kinds\Resolvers\StandardUINativeDocumentKindResolver.pas',
  UIDocumentKindMapper in 'Document Kinds\Mappers\Interfaces\UIDocumentKindMapper.pas',
  StandardUIDocumentKindMapper in 'Document Kinds\Mappers\StandardUIDocumentKindMapper.pas',
  DocumentKindSetHolder in 'Forms\Documents\Primary Screens\View Models\DocumentKindSetHolder.pas',
  unDocumentCardListFrame in 'Forms\Documents\Primary Screens\unDocumentCardListFrame.pas' {DocumentCardListFrame: TFrame},
  DocumentKindsPanelController in 'Controllers\DocumentKindsPanelController.pas',
  unScrollableFrame in 'Forms\Common\Frames\unScrollableFrame.pas' {ScrollableFrame: TFrame},
  unDocumentFlowCardInformationFrame in 'Forms\Common\Frames\unDocumentFlowCardInformationFrame.pas' {DocumentFlowCardInformationFrame: TFrame},
  unDocumentFlowInformationFrame in 'Forms\Common\Frames\unDocumentFlowInformationFrame.pas' {DocumentFlowInformationFrame: TFrame},
  unDocumentCardInformationFrame in 'Forms\Documents\Frames\unDocumentCardInformationFrame.pas' {DocumentCardInformationFrame: TFrame},
  DocumentMainInformationFrameUnit in 'Forms\Documents\Frames\DocumentMainInformationFrameUnit.pas' {DocumentMainInformationFrame: TFrame},
  CreateableDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\CreateableDocumentMainInformationFrameUnit.pas' {CreatableDocumentMainInformationFrame: TFrame},
  DocumentApprovingsFrameUnit in 'Forms\Documents\Frames\DocumentApprovingsFrameUnit.pas' {DocumentApprovingsFrame: TFrame},
  DocumentFilesFrameUnit in 'Forms\Documents\Frames\DocumentFilesFrameUnit.pas' {DocumentFilesFrame: TFrame},
  DocumentRelationsFrameUnit in 'Forms\Documents\Frames\DocumentRelationsFrameUnit.pas' {DocumentRelationsFrame: TFrame},
  unDocumentKindsFrame in 'Forms\Documents\Primary Screens\unDocumentKindsFrame.pas' {DocumentKindsFrame: TFrame},
  unDocumentCardFrame in 'Forms\Documents\Cards\Common\unDocumentCardFrame.pas' {DocumentCardFrame: TFrame},
  OperationalDocumentKindInfo in 'Document Kinds\OperationalDocumentKindInfo.pas',
  unDocumentFlowWorkingFrame in 'Forms\Documents\Primary Screens\unDocumentFlowWorkingFrame.pas' {DocumentFlowWorkingFrame: TFrame},
  unApplicationMainFrame in 'Forms\Common\Primary Screens\unApplicationMainFrame.pas' {ApplicationMainFrame: TFrame},
  unApplicationMainForm in 'Forms\Common\Primary Screens\unApplicationMainForm.pas' {ApplicationMainForm},
  unSelectionDocumentCardListFrame in 'Forms\Documents\Primary Screens\unSelectionDocumentCardListFrame.pas' {SelectionDocumentCardListFrame: TFrame},
  unSelectionDocumentsWorkingFrame in 'Forms\Documents\Primary Screens\unSelectionDocumentsWorkingFrame.pas' {SelectionDocumentsWorkingFrame: TFrame},
  DocumentFilesViewFrameUnit in 'Forms\Documents\Frames\DocumentFilesViewFrameUnit.pas' {DocumentFilesViewFrame: TFrame},
  unSelectionDocumentsForm in 'Forms\Documents\Primary Screens\unSelectionDocumentsForm.pas' {SelectionDocumentsForm},
  unDocumentFlowAdministrationForm in 'Forms\System Administration\Primary Screens\unDocumentFlowAdministrationForm.pas' {DocumentFlowAdministrationForm},
  DocumentFlowAdministrationFormViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdministrationFormViewModel.pas',
  DocumentFlowAdminPrivilegeSetHolder in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeSetHolder.pas',
  DocumentFlowAdminPrivilegeViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeViewModel.pas',
  DocumentFlowAdminFormViewModelMapper in 'ViewModel Mappers\System Administration\Primary Screens\DocumentFlowAdminFormViewModelMapper.pas',
  unAdminDocumentCardListFrame in 'Forms\System Administration\Primary Screens\unAdminDocumentCardListFrame.pas' {AdminDocumentCardListFrame: TFrame},
  unSelectionDepartmentsReferenceForm in 'Forms\Employees\References\unSelectionDepartmentsReferenceForm.pas' {SelectionDepartmentsReferenceForm},
  SelectionDepartmentsReferenceFormViewModelMapper in 'ViewModel Mappers\Employees\SelectionDepartmentsReferenceFormViewModelMapper.pas',
  SelectionDepartmentsReferenceFormViewModel in 'Forms\Employees\References\View Models\SelectionDepartmentsReferenceFormViewModel.pas',
  SelectionDepartmentSetHolder in 'Forms\Employees\References\View Models\SelectionDepartmentSetHolder.pas',
  DepartmentRecordViewModel in 'Forms\Employees\References\View Models\DepartmentRecordViewModel.pas',
  BaseDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Document List\BaseDocumentsReferenceFormUnit.pas' {BaseDocumentsReferenceForm},
  ColumnCellComparator in 'Forms\Documents\References\Common\Document List\Column Cell Comparators\ColumnCellComparator.pas',
  DefaultColumnCellComparator in 'Forms\Documents\References\Common\Document List\Column Cell Comparators\DefaultColumnCellComparator.pas',
  DocumentNumberColumnCellComparator in 'Forms\Documents\References\Common\Document List\Column Cell Comparators\DocumentNumberColumnCellComparator.pas',
  DocumentsReferenceFormPresenter in 'Forms\Documents\References\Common\Document List\Presenters\Interfaces\DocumentsReferenceFormPresenter.pas',
  StandardDocumentsReferenceFormPresenter in 'Forms\Documents\References\Common\Document List\Presenters\StandardDocumentsReferenceFormPresenter.pas',
  DocumentRecordViewModel in 'Forms\Documents\References\Common\Document List\View Models\DocumentRecordViewModel.pas',
  DocumentsReferenceViewModel in 'Forms\Documents\References\Common\Document List\View Models\DocumentsReferenceViewModel.pas',
  DocumentTableViewModel in 'Forms\Documents\References\Common\Document List\View Models\DocumentTableViewModel.pas',
  BaseDocumentsReferenceFilterFormUnit in 'Forms\Documents\References\Common\Document List\BaseDocumentsReferenceFilterFormUnit.pas' {BaseDocumentsReferenceFilterForm},
  EmployeeDocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\EmployeeDocumentCardFormViewModelMapper.pas',
  EmployeeDocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\EmployeeDocumentCardFormViewModelMapperFactory.pas',
  BaseIncomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Document List\BaseIncomingDocumentsReferenceFormUnit.pas' {BaseIncomingDocumentsReferenceForm},
  DocumentRecordViewModelDecorator in 'Forms\Documents\References\Common\Document List\View Models\DocumentRecordViewModelDecorator.pas',
  IncomingDocumentRecordViewModel in 'Forms\Documents\References\Common\Document List\View Models\IncomingDocumentRecordViewModel.pas',
  OutcomingDocumentRecordViewModel in 'Forms\Documents\References\Common\Document List\View Models\OutcomingDocumentRecordViewModel.pas',
  EmployeeDocumentRecordViewModel in 'Forms\Documents\References\Common\Document List\Employee\View Models\EmployeeDocumentRecordViewModel.pas',
  BaseOutcomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Document List\BaseOutcomingDocumentsReferenceFormUnit.pas' {BaseOutcomingDocumentsReferenceForm},
  BaseApproveableDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Document List\BaseApproveableDocumentsReferenceFormUnit.pas' {BaseApproveableDocumentsReferenceForm},
  DocumentCardFormViewModel in 'Forms\Documents\Cards\Common\View Models\DocumentCardFormViewModel.pas',
  EmployeeDocumentCardFormViewModel in 'Forms\Documents\Cards\Common\View Models\EmployeeDocumentCardFormViewModel.pas',
  frxNotPerformedDocumentsReportObjectsUnit in 'Reporting\Presenters\Not Performed Documents\FastReport\Data Modules\frxNotPerformedDocumentsReportObjectsUnit.pas' {frxNotPerformedDocumentsReportObjects: TDataModule},
  NotPerformedDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedDocumentsReportFastReportPresenter.pas',
  NotPerformedIncomingDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedIncomingDocumentsReportFastReportPresenter.pas',
  NotPerformedDocumentsReportPresenter in 'Reporting\Presenters\Not Performed Documents\Interfaces\NotPerformedDocumentsReportPresenter.pas',
  frxDocumentPrintFormReportsModule in 'Reporting\Presenters\Print Forms\FastReport\Data Modules\frxDocumentPrintFormReportsModule.pas' {frxDocumentPrintFormReports: TDataModule},
  ServiceNotePrintFormFastReportPresenter in 'Reporting\Presenters\Print Forms\FastReport\ServiceNotePrintFormFastReportPresenter.pas',
  DocumentPrintFormPresenter in 'Reporting\Presenters\Print Forms\Interfaces\DocumentPrintFormPresenter.pas',
  unDocumentChargesFrame in 'Forms\Documents\Frames\unDocumentChargesFrame.pas' {DocumentChargesFrame: TFrame},
  unDocumentChargeSheetsFrame in 'Forms\Documents\Frames\unDocumentChargeSheetsFrame.pas' {DocumentChargeSheetsFrame: TFrame},
  IncomingDocumentCardFrameFactory in 'Forms\Documents\Cards\Common\Factories\IncomingDocumentCardFrameFactory.pas',
  DocumentApprovingSheetPresenter in 'Reporting\Presenters\Approving Sheets\Interfaces\DocumentApprovingSheetPresenter.pas',
  DocumentApprovingSheetViewModel in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetViewModel.pas',
  DocumentApprovingSheetApprovingSetHolder in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetApprovingSetHolder.pas',
  unFastReportApprovingSheetDataModule in 'Reporting\Presenters\Approving Sheets\FastReport\Data Modules\unFastReportApprovingSheetDataModule.pas' {FastReportApprovingSheetDataModule: TDataModule},
  DocumentApprovingSheetViewModelMapper in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\DocumentApprovingSheetViewModelMapper.pas',
  DocumentApprovingSheetFastReportPresenter in 'Reporting\Presenters\Approving Sheets\FastReport\DocumentApprovingSheetFastReportPresenter.pas',
  DocumentApprovingSheetViewModelMapperFactory in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactory.pas',
  DocumentApprovingSheetViewModelMapperFactories in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactories.pas',
  ApproveableDocumentRecordViewModel in 'Forms\Documents\References\Common\Document List\View Models\ApproveableDocumentRecordViewModel.pas',
  unPersonnelOrderMainInformationFrame in 'Forms\Documents\Personnel Orders\Frames\unPersonnelOrderMainInformationFrame.pas' {PersonnelOrderMainInformationFrame: TFrame},
  unPersonnelOrderSubKindsReferenceForm in 'Forms\Documents\Personnel Orders\References\unPersonnelOrderSubKindsReferenceForm.pas' {PersonnelOrderSubKindsReferenceForm},
  DocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\DocumentsReferenceFormProcessor.pas',
  DocumentsReferenceForm in 'Forms\Documents\References\Common\Document List\Interfaces\DocumentsReferenceForm.pas',
  DocumentsReferenceFormProcessorDecorator in 'Forms\Documents\References\Common\Document List\Processors\DocumentsReferenceFormProcessorDecorator.pas',
  EmployeeDocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\EmployeeDocumentsReferenceFormProcessor.pas',
  OutcomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\OutcomingDocumentsReferenceFormProcessor.pas',
  IncomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\IncomingDocumentsReferenceFormProcessor.pas',
  ApproveableDocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\ApproveableDocumentsReferenceFormProcessor.pas',
  DocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Common\Document List\Processors\Factories\DocumentsReferenceFormProcessorFactory.pas',
  EmployeeDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Common\Document List\Processors\Factories\EmployeeDocumentsReferenceFormProcessorFactory.pas',
  DocumentsReferenceFormFactory in 'Forms\Documents\References\Common\Document List\Factories\DocumentsReferenceFormFactory.pas',
  DocumentsReferenceViewModelFactory in 'Forms\Documents\References\Common\Document List\View Models\Factories\DocumentsReferenceViewModelFactory.pas',
  ServiceNoteNumberColumnCellComparator in 'Forms\Documents\Service Notes\References\Document List\Column Cell Comparators\ServiceNoteNumberColumnCellComparator.pas',
  unApproveableServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unApproveableServiceNotesReferenceForm.pas' {ApproveableServiceNotesReferenceForm},
  unIncomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unIncomingServiceNotesReferenceForm.pas' {IncomingServiceNotesReferenceForm},
  unOutcomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unOutcomingServiceNotesReferenceForm.pas' {OutcomingServiceNotesReferenceForm},
  unPersonnelOrdersReferenceForm in 'Forms\Documents\Personnel Orders\References\Document List\unPersonnelOrdersReferenceForm.pas' {PersonnelOrdersReferenceForm},
  unDocumentChargeSheetPerformersReferenceForm in 'Forms\Documents\References\Common\unDocumentChargeSheetPerformersReferenceForm.pas' {DocumentChargeSheetPerformersReferenceForm},
  ExtendedDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\ExtendedDocumentMainInformationFrameUnit.pas' {ExtendedDocumentMainInformationFrame: TFrame},
  PersonnelOrderSubKindViewModel in 'Forms\Documents\Personnel Orders\References\View Models\PersonnelOrderSubKindViewModel.pas',
  PersonnelOrderMainInformationFormViewModel in 'Forms\Documents\Personnel Orders\Frames\View Models\PersonnelOrderMainInformationFormViewModel.pas',
  unPersonnelOrderCardFrame in 'Forms\Documents\Personnel Orders\Cards\unPersonnelOrderCardFrame.pas' {PersonnelOrderCardFrame: TFrame},
  PersonnelOrderCardFormViewModel in 'Forms\Documents\Personnel Orders\Cards\View Models\PersonnelOrderCardFormViewModel.pas',
  unPersonnelOrderApprovingsFrame in 'Forms\Documents\Personnel Orders\Frames\unPersonnelOrderApprovingsFrame.pas' {PersonnelOrderApprovingsFrame: TFrame},
  PersonnelOrderCardFrameFactory in 'Forms\Documents\Personnel Orders\Cards\Factories\PersonnelOrderCardFrameFactory.pas',
  PersonnelOrderMainInformationFormViewModelMapper in 'Forms\Documents\Personnel Orders\Frames\View Models\Mappers\PersonnelOrderMainInformationFormViewModelMapper.pas',
  PersonnelOrderCardFormViewModelMapper in 'Forms\Documents\Personnel Orders\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapper.pas',
  PersonnelOrderCardFormViewModelMapperFactory in 'Forms\Documents\Personnel Orders\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapperFactory.pas',
  PersonnelOrdersReferenceFormProcessor in 'Forms\Documents\Personnel Orders\References\Document List\Processors\PersonnelOrdersReferenceFormProcessor.pas',
  PersonnelOrderRecordViewModel in 'Forms\Documents\Personnel Orders\References\Document List\View Models\PersonnelOrderRecordViewModel.pas',
  DepartmentDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Common\Document List\Processors\Factories\DepartmentDocumentsReferenceFormProcessorFactory.pas',
  DepartmentDocumentsReferenceFormProcessor in 'Forms\Documents\References\Common\Document List\Processors\DepartmentDocumentsReferenceFormProcessor.pas',
  DocumentFileSetHolder in 'Forms\Documents\References\Common\View Models\DocumentFileSetHolder.pas',
  DocumentRelationSetHolder in 'Forms\Documents\References\Common\View Models\DocumentRelationSetHolder.pas',
  DocumentApprovingListRecordSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListRecordSetHolder.pas',
  DocumentApprovingCycleSetHolder in 'Forms\Documents\References\Common\View Models\DocumentApprovingCycleSetHolder.pas',
  DocumentChargeSetHolder in 'Forms\Documents\References\Common\View Models\DocumentChargeSetHolder.pas',
  DocumentDataSetHolderFactories in 'Forms\Documents\References\Common\View Models\Factories\DocumentDataSetHolderFactories.pas',
  DocumentDataSetHoldersFactory in 'Forms\Documents\References\Common\View Models\Factories\DocumentDataSetHoldersFactory.pas',
  DocumentApprovingListSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListSetHolder.pas',
  DocumentApprovingListSetHolderMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingListSetHolderMapper.pas',
  ApplicationPropertiesStorageRegistry in 'Launching\Settings\Storing\ApplicationPropertiesStorageRegistry.pas',
  DocumentRecordsPanelSettingsFormPropertiesIniFile in 'Launching\Settings\Storing\Documents\Forms\DocumentRecordsPanelSettingsFormPropertiesIniFile.pas',
  DocumentRecordsPanelSettingsFormPropertiesStorage in 'Launching\Settings\Storing\Documents\Forms\DocumentRecordsPanelSettingsFormPropertiesStorage.pas',
  DocumentChargesFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\DocumentChargesFramePropertiesIniFile.pas',
  DocumentChargesFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\DocumentChargesFramePropertiesStorage.pas',
  DocumentCardFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Cards\DocumentCardFramePropertiesIniFile.pas',
  DocumentCardFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Cards\DocumentCardFramePropertiesStorage.pas',
  DocumentCardListFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Card List\DocumentCardListFramePropertiesIniFile.pas',
  DocumentKindsFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Kinds\DocumentKindsFramePropertiesIniFile.pas',
  DocumentsReferenceFilterFormStatePropertiesIniFile in 'Launching\Settings\Storing\Documents\References\DocumentsReferenceFilterFormStatePropertiesIniFile.pas',
  DocumentsReferenceFormPropertiesIniFile in 'Launching\Settings\Storing\Documents\References\DocumentsReferenceFormPropertiesIniFile.pas',
  ApplicationSettingsResetService in 'Launching\Settings\Services\Interfaces\ApplicationSettingsResetService.pas',
  AppDataLocalSettingsResetService in 'Launching\Settings\Services\Standard\AppDataLocalSettingsResetService.pas',
  ApplicationMainFramePropertiesIniFile in 'Launching\Settings\Storing\Common\ApplicationMainFramePropertiesIniFile.pas',
  ApplicationMainFramePropertiesStorage in 'Launching\Settings\Storing\Common\ApplicationMainFramePropertiesStorage.pas',
  DocumentKindsFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Kinds\DocumentKindsFramePropertiesStorage.pas',
  DocumentCardListFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Card List\DocumentCardListFramePropertiesStorage.pas',
  AuxDebugFunctionsUnit,
  unUserNotificationsSettingsForm in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsForm.pas' {UserNotificationsSettingsForm},
  UserNotificationsSettingsFormViewModelMapper in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModelMapper.pas',
  UserNotificationsSettingsFormViewModel in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModel.pas',
  StandardDocumentFlowStyle in 'Forms\Common\Styles\StandardDocumentFlowStyle.pas',
  unUserNotificationsSettingsFrame in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsFrame.pas' {UserNotificationsSettingsFrame: TFrame},
  UserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\UserNotificationsSettingsFrameFactory.pas',
  ZeosPostgresUserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\ZeosPostgresUserNotificationsSettingsFrameFactory.pas',
  ZConnection,
  Controls,
  PDFViewFormUnit,
  UserInterfaceSwitch in 'Forms\Common\Frames\UserInterfaceSwitch.pas',
  AuxFileFunctions,
  DocumentFlowInformationFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Interfaces\DocumentFlowInformationFramePropertiesStorage.pas',
  StandardDocumentFlowInformationFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\StandardDocumentFlowInformationFramePropertiesStorage.pas',
  StandardApplicationSettingsResetService in 'Launching\Settings\Services\Standard\StandardApplicationSettingsResetService.pas',
  DocumentFlowBaseReferenceFormUnit in 'Forms\Common\References\DocumentFlowBaseReferenceFormUnit.pas' {DocumentFlowBaseReferenceForm},
  unVersionInfosForm in 'Forms\Common\Primary Screens\unVersionInfosForm.pas' {VersionInfosForm},
  unApplicationDataModule in 'Launching\Configuration\unApplicationDataModule.pas' {DocumentFlowAppDataModule: TDataModule},
  DBDataTableFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\DBDataTableFormUnit.pas' {DBDataTableForm},
  RegExprValidateEditUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateEditUnit.pas',
  RegExprValidateMemoUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateMemoUnit.pas',
  RegExprValidateRichEdit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateRichEdit.pas',
  SourcedEventHandlers in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\SourcedEventHandlers.pas',
  EventHandlerChains in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\EventHandlerChains.pas',
  DomainObjectRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\Interfaces\DomainObjectRepository.pas',
  AbstractDBRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\AbstractDBRepository.pas',
  PropertiesIniFileUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Properties Storages\PropertiesIniFileUnit.pas';

{$R *.res}

var
    ApplicationLauncher: TApplicationLauncher;
begin

  //ReportMemoryLeaksOnShutdown := True;

  try

    ApplicationLauncher :=
      TApplicationLauncher.Create(
        TUIApplicationConfigurator.Create
      );

    ApplicationLauncher.Launch;

  finally

    FreeAndNil(ApplicationLauncher);

  end;  

end.
