program DocumentFlow;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  ArrayTypes,
  madListModules,
  Forms,
  Classes,
  SysUtils,
  CommonControlStyles in 'Forms\Common\Styles\CommonControlStyles.pas',
  EmployeeCardFormUnit in 'Forms\Employees\Cards\Management\EmployeeCardFormUnit.pas' {EmployeeCardForm},
  DocumentChargeSheetsChangesInfoDTOMapper in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapper.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactories in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactories.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactory in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactory.pas',
  UIDocumentKinds in 'Document Kinds\UIDocumentKinds.pas',
  UIDocumentKindResolver in 'Document Kinds\Resolvers\Interfaces\UIDocumentKindResolver.pas',
  ExceptionHandling in 'Exception Handling\ExceptionHandling.pas',
  DocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\DocumentReportPresenterRegistry.pas',
  IDocumentReportPresenterRegistryUnit in 'Reporting\Presenters\Registries\IDocumentReportPresenterRegistryUnit.pas',
  StandardDocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\StandardDocumentReportPresenterRegistry.pas',
  NotPerformedDocumentsReportShowCustomizeFormUnit in 'Forms\Documents\Reporting\NotPerformedDocumentsReportShowCustomizeFormUnit.pas' {NotPerformedDocumentsReportShowCustomizeForm},
  DepartmentViewModel in 'Forms\Documents\Reporting\View Models\DepartmentViewModel.pas',
  DocumentKindWorkCycleColors in 'Forms\Documents\Styles\DocumentKindWorkCycleColors.pas',
  UIApplicationConfigurator in 'Launching\Configuration\UIApplicationConfigurator.pas',
  ApplicationLauncher in 'Launching\ApplicationLauncher.pas',
  DocumentRecordsPanelSettingsFormUnit in 'Forms\Documents\Settings\DocumentRecordsPanelSettingsFormUnit.pas' {DocumentRecordsPanelSettingsForm},
  EmployeesReferenceFormUnit in 'Forms\Employees\References\EmployeesReferenceFormUnit.pas' {EmployeesReferenceForm},
  StandardUIDocumentKindResolver in 'Document Kinds\Resolvers\StandardUIDocumentKindResolver.pas',
  UINativeDocumentKindResolver in 'Document Kinds\Resolvers\Interfaces\UINativeDocumentKindResolver.pas',
  StandardUINativeDocumentKindResolver in 'Document Kinds\Resolvers\StandardUINativeDocumentKindResolver.pas',
  UIDocumentKindMapper in 'Document Kinds\Mappers\Interfaces\UIDocumentKindMapper.pas',
  StandardUIDocumentKindMapper in 'Document Kinds\Mappers\StandardUIDocumentKindMapper.pas',
  unScrollableFrame in 'Forms\Common\Frames\unScrollableFrame.pas' {ScrollableFrame: TFrame},
  unDocumentFlowCardInformationFrame in 'Forms\Common\Frames\unDocumentFlowCardInformationFrame.pas' {DocumentFlowCardInformationFrame: TFrame},
  unDocumentFlowInformationFrame in 'Forms\Common\Frames\unDocumentFlowInformationFrame.pas' {DocumentFlowInformationFrame: TFrame},
  OperationalDocumentKindInfo in 'Document Kinds\OperationalDocumentKindInfo.pas',
  unApplicationMainFrame in 'Forms\Common\Primary Screens\unApplicationMainFrame.pas' {ApplicationMainFrame: TFrame},
  unApplicationMainForm in 'Forms\Common\Primary Screens\unApplicationMainForm.pas' {ApplicationMainForm},
  unDocumentFlowAdministrationForm in 'Forms\System Administration\Primary Screens\unDocumentFlowAdministrationForm.pas' {DocumentFlowAdministrationForm},
  DocumentFlowAdministrationFormViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdministrationFormViewModel.pas',
  DocumentFlowAdminPrivilegeSetHolder in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeSetHolder.pas',
  DocumentFlowAdminPrivilegeViewModel in 'Forms\System Administration\Primary Screens\View Models\DocumentFlowAdminPrivilegeViewModel.pas',
  DocumentFlowAdminFormViewModelMapper in 'ViewModel Mappers\System Administration\Primary Screens\DocumentFlowAdminFormViewModelMapper.pas',
  unAdminDocumentCardListFrame in 'Forms\System Administration\Primary Screens\unAdminDocumentCardListFrame.pas' {AdminDocumentCardListFrame: TFrame},
  unSelectionDepartmentsReferenceForm in 'Forms\Employees\References\unSelectionDepartmentsReferenceForm.pas' {SelectionDepartmentsReferenceForm},
  SelectionDepartmentsReferenceFormViewModelMapper in 'ViewModel Mappers\Employees\SelectionDepartmentsReferenceFormViewModelMapper.pas',
  SelectionDepartmentsReferenceFormViewModel in 'Forms\Employees\References\View Models\SelectionDepartmentsReferenceFormViewModel.pas',
  SelectionDepartmentSetHolder in 'Forms\Employees\References\View Models\SelectionDepartmentSetHolder.pas',
  DepartmentRecordViewModel in 'Forms\Employees\References\View Models\DepartmentRecordViewModel.pas',
  frxNotPerformedDocumentsReportObjectsUnit in 'Reporting\Presenters\Not Performed Documents\FastReport\Data Modules\frxNotPerformedDocumentsReportObjectsUnit.pas' {frxNotPerformedDocumentsReportObjects: TDataModule},
  NotPerformedDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedDocumentsReportFastReportPresenter.pas',
  NotPerformedIncomingDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\FastReport\NotPerformedIncomingDocumentsReportFastReportPresenter.pas',
  NotPerformedDocumentsReportPresenter in 'Reporting\Presenters\Not Performed Documents\Interfaces\NotPerformedDocumentsReportPresenter.pas',
  frxDocumentPrintFormReportsModule in 'Reporting\Presenters\Print Forms\FastReport\Data Modules\frxDocumentPrintFormReportsModule.pas' {frxDocumentPrintFormReports: TDataModule},
  ServiceNotePrintFormFastReportPresenter in 'Reporting\Presenters\Print Forms\FastReport\ServiceNotePrintFormFastReportPresenter.pas',
  DocumentPrintFormPresenter in 'Reporting\Presenters\Print Forms\Interfaces\DocumentPrintFormPresenter.pas',
  DocumentApprovingSheetPresenter in 'Reporting\Presenters\Approving Sheets\Interfaces\DocumentApprovingSheetPresenter.pas',
  DocumentApprovingSheetViewModel in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetViewModel.pas',
  DocumentApprovingSheetApprovingSetHolder in 'Reporting\Presenters\Approving Sheets\View Models\DocumentApprovingSheetApprovingSetHolder.pas',
  unFastReportApprovingSheetDataModule in 'Reporting\Presenters\Approving Sheets\FastReport\Data Modules\unFastReportApprovingSheetDataModule.pas' {FastReportApprovingSheetDataModule: TDataModule},
  DocumentApprovingSheetViewModelMapper in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\DocumentApprovingSheetViewModelMapper.pas',
  DocumentApprovingSheetFastReportPresenter in 'Reporting\Presenters\Approving Sheets\FastReport\DocumentApprovingSheetFastReportPresenter.pas',
  DocumentApprovingSheetViewModelMapperFactory in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactory.pas',
  DocumentApprovingSheetViewModelMapperFactories in 'Reporting\Presenters\Approving Sheets\View Models\Mappers\Factories\DocumentApprovingSheetViewModelMapperFactories.pas',
  unPersonnelOrderSubKindsReferenceForm in 'Forms\Documents\Personnel Orders\References\unPersonnelOrderSubKindsReferenceForm.pas' {PersonnelOrderSubKindsReferenceForm},
  ServiceNoteNumberColumnCellComparator in 'Forms\Documents\Service Notes\References\Document List\Column Cell Comparators\ServiceNoteNumberColumnCellComparator.pas',
  unApproveableServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unApproveableServiceNotesReferenceForm.pas' {ApproveableServiceNotesReferenceForm},
  unIncomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unIncomingServiceNotesReferenceForm.pas' {IncomingServiceNotesReferenceForm},
  unOutcomingServiceNotesReferenceForm in 'Forms\Documents\Service Notes\References\Document List\unOutcomingServiceNotesReferenceForm.pas' {OutcomingServiceNotesReferenceForm},
  unPersonnelOrdersReferenceForm in 'Forms\Documents\Personnel Orders\References\Document List\unPersonnelOrdersReferenceForm.pas' {PersonnelOrdersReferenceForm},
  PersonnelOrderSubKindViewModel in 'Forms\Documents\Personnel Orders\References\View Models\PersonnelOrderSubKindViewModel.pas',
  PersonnelOrdersReferenceFormProcessor in 'Forms\Documents\Personnel Orders\References\Document List\Processors\PersonnelOrdersReferenceFormProcessor.pas',
  PersonnelOrderRecordViewModel in 'Forms\Documents\Personnel Orders\References\Document List\View Models\PersonnelOrderRecordViewModel.pas',
  DocumentApprovingListRecordSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListRecordSetHolder.pas',
  DocumentApprovingListSetHolder in 'Reporting\Presenters\Print Forms\View Models\DocumentApprovingListSetHolder.pas',
  ApplicationPropertiesStorageRegistry in 'Launching\Settings\Storing\ApplicationPropertiesStorageRegistry.pas',
  DocumentRecordsPanelSettingsFormPropertiesIniFile in 'Launching\Settings\Storing\Documents\Forms\DocumentRecordsPanelSettingsFormPropertiesIniFile.pas',
  DocumentRecordsPanelSettingsFormPropertiesStorage in 'Launching\Settings\Storing\Documents\Forms\DocumentRecordsPanelSettingsFormPropertiesStorage.pas',
  DocumentChargesFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\DocumentChargesFramePropertiesIniFile.pas',
  DocumentChargesFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\DocumentChargesFramePropertiesStorage.pas',
  DocumentCardFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Cards\DocumentCardFramePropertiesIniFile.pas',
  DocumentCardFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Cards\DocumentCardFramePropertiesStorage.pas',
  DocumentCardListFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Card List\DocumentCardListFramePropertiesIniFile.pas',
  DocumentKindsFramePropertiesIniFile in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Kinds\DocumentKindsFramePropertiesIniFile.pas',
  DocumentsReferenceFilterFormStatePropertiesIniFile in 'Launching\Settings\Storing\Documents\References\DocumentsReferenceFilterFormStatePropertiesIniFile.pas',
  DocumentsReferenceFormPropertiesIniFile in 'Launching\Settings\Storing\Documents\References\DocumentsReferenceFormPropertiesIniFile.pas',
  ApplicationSettingsResetService in 'Launching\Settings\Services\Interfaces\ApplicationSettingsResetService.pas',
  AppDataLocalSettingsResetService in 'Launching\Settings\Services\Standard\AppDataLocalSettingsResetService.pas',
  ApplicationMainFramePropertiesIniFile in 'Launching\Settings\Storing\Common\ApplicationMainFramePropertiesIniFile.pas',
  ApplicationMainFramePropertiesStorage in 'Launching\Settings\Storing\Common\ApplicationMainFramePropertiesStorage.pas',
  DocumentKindsFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Kinds\DocumentKindsFramePropertiesStorage.pas',
  DocumentCardListFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Primary\Document Card List\DocumentCardListFramePropertiesStorage.pas',
  AuxDebugFunctionsUnit,
  unUserNotificationsSettingsForm in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsForm.pas' {UserNotificationsSettingsForm},
  UserNotificationsSettingsFormViewModelMapper in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModelMapper.pas',
  UserNotificationsSettingsFormViewModel in 'Forms\Employees\Settings\Notifications\View Models\UserNotificationsSettingsFormViewModel.pas',
  StandardDocumentFlowStyle in 'Forms\Common\Styles\StandardDocumentFlowStyle.pas',
  unUserNotificationsSettingsFrame in 'Forms\Employees\Settings\Notifications\unUserNotificationsSettingsFrame.pas' {UserNotificationsSettingsFrame: TFrame},
  UserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\UserNotificationsSettingsFrameFactory.pas',
  ZeosPostgresUserNotificationsSettingsFrameFactory in 'Forms\Employees\Settings\Notifications\Factories\ZeosPostgresUserNotificationsSettingsFrameFactory.pas',
  ZConnection,
  Controls,
  UserInterfaceSwitch in 'Forms\Common\Frames\UserInterfaceSwitch.pas',
  AuxFileFunctions,
  DocumentFlowInformationFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\Interfaces\DocumentFlowInformationFramePropertiesStorage.pas',
  StandardDocumentFlowInformationFramePropertiesStorage in 'Launching\Settings\Storing\Documents\Frames\StandardDocumentFlowInformationFramePropertiesStorage.pas',
  StandardApplicationSettingsResetService in 'Launching\Settings\Services\Standard\StandardApplicationSettingsResetService.pas',
  DocumentFlowBaseReferenceFormUnit in 'Forms\Common\References\DocumentFlowBaseReferenceFormUnit.pas' {DocumentFlowBaseReferenceForm},
  unVersionInfosForm in 'Forms\Common\Primary Screens\unVersionInfosForm.pas' {VersionInfosForm},
  unApplicationDataModule in 'Launching\Configuration\unApplicationDataModule.pas' {DocumentFlowAppDataModule: TDataModule},
  RegExprValidateEditUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateEditUnit.pas',
  RegExprValidateMemoUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateMemoUnit.pas',
  RegExprValidateRichEdit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Validate Edit\DesignComponents\RegExprValidateRichEdit.pas',
  SourcedEventHandlers in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\SourcedEventHandlers.pas',
  EventHandlerChains in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Event Handlers\EventHandlerChains.pas',
  DomainObjectRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\Interfaces\DomainObjectRepository.pas',
  AbstractDBRepository in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\New\AbstractDBRepository.pas',
  PropertiesIniFileUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Properties Storages\PropertiesIniFileUnit.pas',
  DocumentApproversReferenceFormUnit in 'Forms\Documents\References\DocumentApproversReferenceFormUnit.pas' {DocumentApproversReferenceForm},
  DocumentApprovingCyclesReferenceFormUnit in 'Forms\Documents\References\DocumentApprovingCyclesReferenceFormUnit.pas' {DocumentApprovingCyclesReferenceForm},
  DocumentChargePerformersReferenceFormUnit in 'Forms\Documents\References\DocumentChargePerformersReferenceFormUnit.pas' {DocumentChargePerformersReferenceForm},
  DocumentFilesReferenceFormUnit in 'Forms\Documents\References\DocumentFilesReferenceFormUnit.pas' {DocumentFilesReferenceForm},
  DocumentRelationsReferenceFormUnit in 'Forms\Documents\References\DocumentRelationsReferenceFormUnit.pas' {DocumentRelationsReferenceForm},
  DocumentResponsiblesReferenceFormUnit in 'Forms\Documents\References\DocumentResponsiblesReferenceFormUnit.pas' {DocumentResponsiblesReferenceForm},
  DocumentSignersReferenceFormUnit in 'Forms\Documents\References\DocumentSignersReferenceFormUnit.pas' {DocumentSignersReferenceForm},
  unDocumentChargeSheetPerformersReferenceForm in 'Forms\Documents\References\unDocumentChargeSheetPerformersReferenceForm.pas' {DocumentChargeSheetPerformersReferenceForm},
  DocumentApprovingCycleSetHolder in 'Forms\Documents\References\View Models\DocumentApprovingCycleSetHolder.pas',
  DocumentChargeSetHolder in 'Forms\Documents\References\View Models\DocumentChargeSetHolder.pas',
  DocumentChargeSheetSetHolder in 'Forms\Documents\References\View Models\DocumentChargeSheetSetHolder.pas',
  DocumentFileSetHolder in 'Forms\Documents\References\View Models\DocumentFileSetHolder.pas',
  DocumentRelationSetHolder in 'Forms\Documents\References\View Models\DocumentRelationSetHolder.pas',
  DocumentApprovingCycleSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentApprovingCycleSetHolderFactory.pas',
  DocumentApprovingSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentApprovingSetHolderFactory.pas',
  DocumentChargeSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentChargeSetHolderFactory.pas',
  DocumentChargeSheetSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentChargeSheetSetHolderFactory.pas',
  DocumentDataSetHoldersFactories in 'Forms\Documents\References\View Models\Factories\DocumentDataSetHoldersFactories.pas',
  DocumentDataSetHoldersFactory in 'Forms\Documents\References\View Models\Factories\DocumentDataSetHoldersFactory.pas',
  DocumentFileSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentFileSetHolderFactory.pas',
  DocumentRelationSetHolderFactory in 'Forms\Documents\References\View Models\Factories\DocumentRelationSetHolderFactory.pas',
  DBDataTableFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\DBDataTableFormUnit.pas' {DBDataTableForm},
  TableViewFilterFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\TableViewFilterFormUnit.pas' {TableViewFilterForm},
  BaseApproveableDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseApproveableDocumentsReferenceFormUnit.pas' {BaseApproveableDocumentsReferenceForm},
  BaseDocumentsReferenceFilterFormUnit in 'Forms\Documents\References\Document List\BaseDocumentsReferenceFilterFormUnit.pas' {BaseDocumentsReferenceFilterForm},
  BaseDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseDocumentsReferenceFormUnit.pas' {BaseDocumentsReferenceForm},
  BaseIncomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseIncomingDocumentsReferenceFormUnit.pas' {BaseIncomingDocumentsReferenceForm},
  BaseOutcomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Document List\BaseOutcomingDocumentsReferenceFormUnit.pas' {BaseOutcomingDocumentsReferenceForm},
  ApproveableDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\ApproveableDocumentRecordViewModel.pas',
  DocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\DocumentRecordViewModel.pas',
  DocumentRecordViewModelDecorator in 'Forms\Documents\References\Document List\View Models\DocumentRecordViewModelDecorator.pas',
  DocumentsReferenceViewModel in 'Forms\Documents\References\Document List\View Models\DocumentsReferenceViewModel.pas',
  DocumentTableViewModel in 'Forms\Documents\References\Document List\View Models\DocumentTableViewModel.pas',
  EmployeeDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\EmployeeDocumentRecordViewModel.pas',
  IncomingDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\IncomingDocumentRecordViewModel.pas',
  OutcomingDocumentRecordViewModel in 'Forms\Documents\References\Document List\View Models\OutcomingDocumentRecordViewModel.pas',
  DocumentsReferenceViewModelFactory in 'Forms\Documents\References\Document List\View Models\Factories\DocumentsReferenceViewModelFactory.pas',
  ApproveableDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\ApproveableDocumentsReferenceFormProcessor.pas',
  DepartmentDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\DepartmentDocumentsReferenceFormProcessor.pas',
  DocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\DocumentsReferenceFormProcessor.pas',
  DocumentsReferenceFormProcessorDecorator in 'Forms\Documents\References\Document List\Processors\DocumentsReferenceFormProcessorDecorator.pas',
  EmployeeDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\EmployeeDocumentsReferenceFormProcessor.pas',
  IncomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\IncomingDocumentsReferenceFormProcessor.pas',
  OutcomingDocumentsReferenceFormProcessor in 'Forms\Documents\References\Document List\Processors\OutcomingDocumentsReferenceFormProcessor.pas',
  DepartmentDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\DepartmentDocumentsReferenceFormProcessorFactory.pas',
  DocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\DocumentsReferenceFormProcessorFactory.pas',
  EmployeeDocumentsReferenceFormProcessorFactory in 'Forms\Documents\References\Document List\Processors\Factories\EmployeeDocumentsReferenceFormProcessorFactory.pas',
  DocumentsReferenceFormPresenter in 'Forms\Documents\References\Document List\Presenters\Interfaces\DocumentsReferenceFormPresenter.pas',
  StandardDocumentsReferenceFormPresenter in 'Forms\Documents\References\Document List\Presenters\StandardDocumentsReferenceFormPresenter.pas',
  DocumentsReferenceForm in 'Forms\Documents\References\Document List\Interfaces\DocumentsReferenceForm.pas',
  DocumentsReferenceFormFactory in 'Forms\Documents\References\Document List\Factories\DocumentsReferenceFormFactory.pas',
  ColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\ColumnCellComparator.pas',
  DefaultColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\DefaultColumnCellComparator.pas',
  DocumentNumberColumnCellComparator in 'Forms\Documents\References\Document List\Column Cell Comparators\DocumentNumberColumnCellComparator.pas',
  DocumentKindsPanelController in 'Forms\Documents\Primary Screens\Document Kinds\DocumentKindsPanelController.pas',
  unDocumentKindsFrame in 'Forms\Documents\Primary Screens\Document Kinds\unDocumentKindsFrame.pas' {DocumentKindsFrame: TFrame},
  unDocumentCardListFrame in 'Forms\Documents\Primary Screens\unDocumentCardListFrame.pas' {DocumentCardListFrame: TFrame},
  unDocumentFlowWorkingFrame in 'Forms\Documents\Primary Screens\unDocumentFlowWorkingFrame.pas' {DocumentFlowWorkingFrame: TFrame},
  unSelectionDocumentCardListFrame in 'Forms\Documents\Primary Screens\unSelectionDocumentCardListFrame.pas' {SelectionDocumentCardListFrame: TFrame},
  unSelectionDocumentsForm in 'Forms\Documents\Primary Screens\unSelectionDocumentsForm.pas' {SelectionDocumentsForm},
  unSelectionDocumentsWorkingFrame in 'Forms\Documents\Primary Screens\unSelectionDocumentsWorkingFrame.pas' {SelectionDocumentsWorkingFrame: TFrame},
  unDocumentCardInformationFrame in 'Forms\Documents\Frames\Common\unDocumentCardInformationFrame.pas' {DocumentCardInformationFrame: TFrame},
  InputMemoFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\User Input Forms\InputMemoFormUnit.pas' {InputMemoForm},
  DocumentFlowSystemInputMemoFormUnit in 'Forms\Common\Field-Targeted\DocumentFlowSystemInputMemoFormUnit.pas' {DocumentFlowSystemInputMemoForm},
  DocumentApproversInfoFormUnit in 'Forms\Documents\Frames\Approvings\DocumentApproversInfoFormUnit.pas' {DocumentApproversInfoForm},
  DocumentApprovingsFrameUnit in 'Forms\Documents\Frames\Approvings\DocumentApprovingsFrameUnit.pas' {DocumentApprovingsFrame: TFrame},
  unNotDocumentApprovingReasonInputForm in 'Forms\Documents\Frames\Approvings\unNotDocumentApprovingReasonInputForm.pas' {NotDocumentApprovingReasonInputForm},
  DocumentApprovingCycleViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingCycleViewModel.pas',
  DocumentApprovingsFormViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingsFormViewModel.pas',
  DocumentApprovingViewModel in 'Forms\Documents\Frames\Approvings\View Models\DocumentApprovingViewModel.pas',
  DocumentCardFormUnit in 'Forms\Documents\Frames\Cards\DocumentCardFormUnit.pas' {DocumentCardForm},
  unDocumentCardFrame in 'Forms\Documents\Frames\Cards\unDocumentCardFrame.pas' {DocumentCardFrame: TFrame},
  DocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\DocumentCardFormViewModel.pas',
  EmployeeDocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\EmployeeDocumentCardFormViewModel.pas',
  IncomingDocumentCardFormViewModel in 'Forms\Documents\Frames\Cards\View Models\IncomingDocumentCardFormViewModel.pas',
  DocumentCardFrameFactories in 'Forms\Documents\Frames\Cards\Factories\DocumentCardFrameFactories.pas',
  DocumentCardFrameFactory in 'Forms\Documents\Frames\Cards\Factories\DocumentCardFrameFactory.pas',
  IncomingDocumentCardFrameFactory in 'Forms\Documents\Frames\Cards\Factories\IncomingDocumentCardFrameFactory.pas',
  unDocumentChargesFrame in 'Forms\Documents\Frames\Charges\unDocumentChargesFrame.pas' {DocumentChargesFrame: TFrame},
  DocumentChargesFormViewModelUnit in 'Forms\Documents\Frames\Charges\View Models\DocumentChargesFormViewModelUnit.pas',
  unDocumentChargeSheetsFrame in 'Forms\Documents\Frames\Charge Sheets\unDocumentChargeSheetsFrame.pas' {DocumentChargeSheetsFrame: TFrame},
  DocumentChargeSheetsFormViewModel in 'Forms\Documents\Frames\Charge Sheets\View Models\DocumentChargeSheetsFormViewModel.pas',
  DocumentFilesFrameUnit in 'Forms\Documents\Frames\Files\DocumentFilesFrameUnit.pas' {DocumentFilesFrame: TFrame},
  DocumentFilesViewFrameUnit in 'Forms\Documents\Frames\Files\DocumentFilesViewFrameUnit.pas' {DocumentFilesViewFrame: TFrame},
  DocumentFlowPDFViewFormUnit in 'Forms\Documents\Frames\Files\DocumentFlowPDFViewFormUnit.pas' {DocumentFlowPDFViewForm},
  DocumentFileInfoList in 'Forms\Documents\Frames\Files\View Models\DocumentFileInfoList.pas',
  DocumentFilesFormViewModelUnit in 'Forms\Documents\Frames\Files\View Models\DocumentFilesFormViewModelUnit.pas',
  DocumentFilesViewFormViewModel in 'Forms\Documents\Frames\Files\View Models\DocumentFilesViewFormViewModel.pas',
  DocumentMainInformationFrameUnit in 'Forms\Documents\Frames\Main Info\DocumentMainInformationFrameUnit.pas' {DocumentMainInformationFrame: TFrame},
  ExtendedDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\Main Info\ExtendedDocumentMainInformationFrameUnit.pas' {ExtendedDocumentMainInformationFrame: TFrame},
  DocumentMainInformationFormViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentMainInformationFormViewModelUnit.pas',
  DocumentResponsibleViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentResponsibleViewModelUnit.pas',
  DocumentSignerViewModelUnit in 'Forms\Documents\Frames\Main Info\View Models\DocumentSignerViewModelUnit.pas',
  IncomingDocumentMainInformationFormViewModel in 'Forms\Documents\Frames\Main Info\View Models\IncomingDocumentMainInformationFormViewModel.pas',
  DocumentOperationToolBarFrameUnit in 'Forms\Documents\Frames\Operations\DocumentOperationToolBarFrameUnit.pas' {DocumentOperationToolBarFrame: TFrame},
  DocumentRelationsFrameUnit in 'Forms\Documents\Frames\Relations\DocumentRelationsFrameUnit.pas' {DocumentRelationsFrame: TFrame},
  DocumentRelationsFormViewModelUnit in 'Forms\Documents\Frames\Relations\View Models\DocumentRelationsFormViewModelUnit.pas',
  unServiceNoteCardFrame in 'Forms\Documents\Service Notes\Frames\Cards\unServiceNoteCardFrame.pas' {ServiceNoteCardFrame: TFrame},
  ServiceNoteCardFrameFactory in 'Forms\Documents\Service Notes\Frames\Cards\Factories\ServiceNoteCardFrameFactory.pas',
  unServiceNoteChargeSheetsFrame in 'Forms\Documents\Service Notes\Frames\Charge Sheets\unServiceNoteChargeSheetsFrame.pas' {ServiceNoteChargeSheetsFrame: TFrame},
  unServiceNoteChargesFrame in 'Forms\Documents\Service Notes\Frames\Charges\unServiceNoteChargesFrame.pas' {ServiceNoteChargesFrame: TFrame},
  unPersonnelOrderApprovingsFrame in 'Forms\Documents\Personnel Orders\Frames\Approvings\unPersonnelOrderApprovingsFrame.pas' {PersonnelOrderApprovingsFrame: TFrame},
  unPersonnelOrderCardFrame in 'Forms\Documents\Personnel Orders\Frames\Cards\unPersonnelOrderCardFrame.pas' {PersonnelOrderCardFrame: TFrame},
  PersonnelOrderCardFormViewModel in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\PersonnelOrderCardFormViewModel.pas',
  PersonnelOrderCardFormViewModelMapper in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapper.pas',
  PersonnelOrderCardFormViewModelMapperFactory in 'Forms\Documents\Personnel Orders\Frames\Cards\View Models\Mappers\PersonnelOrderCardFormViewModelMapperFactory.pas',
  PersonnelOrderCardFrameFactory in 'Forms\Documents\Personnel Orders\Frames\Cards\Factories\PersonnelOrderCardFrameFactory.pas',
  unPersonnelOrderChargeSheetsFrame in 'Forms\Documents\Personnel Orders\Frames\Charge Sheets\unPersonnelOrderChargeSheetsFrame.pas' {PersonnelOrderChargeSheetsFrame: TFrame},
  unPersonnelOrderChargesFrame in 'Forms\Documents\Personnel Orders\Frames\Charges\unPersonnelOrderChargesFrame.pas' {PersonnelOrderChargesFrame: TFrame},
  unPersonnelOrderMainInformationFrame in 'Forms\Documents\Personnel Orders\Frames\Main Info\unPersonnelOrderMainInformationFrame.pas' {PersonnelOrderMainInformationFrame: TFrame},
  PersonnelOrderMainInformationFormViewModel in 'Forms\Documents\Personnel Orders\Frames\Main Info\View Models\PersonnelOrderMainInformationFormViewModel.pas',
  PersonnelOrderMainInformationFormViewModelMapper in 'Forms\Documents\Personnel Orders\Frames\Main Info\View Models\Mappers\PersonnelOrderMainInformationFormViewModelMapper.pas',
  DocumentApprovingListSetHolderMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingListSetHolderMapper.pas',
  DocumentApprovingsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingsFormViewModelMapper.pas',
  DocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapper.pas',
  DocumentCardFormViewModelMapperFactories in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactories.pas',
  DocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactory.pas',
  DocumentChargesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentChargesFormViewModelMapper.pas',
  DocumentChargeSheetsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentChargeSheetsFormViewModelMapper.pas',
  DocumentFilesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesFormViewModelMapper.pas',
  DocumentFilesViewFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesViewFormViewModelMapper.pas',
  DocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentMainInformationFormViewModelMapper.pas',
  DocumentRelationsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentRelationsFormViewModelMapper.pas',
  DocumentResponsibleViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentResponsibleViewModelMapper.pas',
  DocumentSignerViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentSignerViewModelMapper.pas',
  EmployeeDocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\EmployeeDocumentCardFormViewModelMapper.pas',
  EmployeeDocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\EmployeeDocumentCardFormViewModelMapperFactory.pas',
  IncomingDocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapperFactory.pas',
  IncomingDocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentMainInformationFormViewModelMapper.pas',
  LoodsmanDocumentUploadingInfoFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\LoodsmanDocumentUploadingInfoFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapperFactory.pas',
  IncomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteMainInformationFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapperFactory.pas',
  OutcomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteMainInformationFormViewModelMapper.pas',
  DocumentKindSetHolder in 'Forms\Documents\Primary Screens\Document Kinds\View Models\DocumentKindSetHolder.pas',
  DocumentKindsFormViewModel in 'Forms\Documents\Primary Screens\Document Kinds\View Models\DocumentKindsFormViewModel.pas',
  DocumentKindsFormViewModelMapper in 'ViewModel Mappers\Documents\References\Document Kinds\DocumentKindsFormViewModelMapper.pas',
  LoodsmanDocumentUploadingInfoFormViewModel in 'Forms\Documents\Frames\Loodsman\Uploading\LoodsmanDocumentUploadingInfoFormViewModel.pas',
  DocumentApprovingListRecordSetHolderFactory in 'Reporting\Presenters\Print Forms\View Models\Factories\DocumentApprovingListRecordSetHolderFactory.pas',
  DocumentApprovingListSetHolderFactory in 'Reporting\Presenters\Print Forms\View Models\Factories\DocumentApprovingListSetHolderFactory.pas';

{$R *.res}

var
    ApplicationLauncher: TApplicationLauncher;
begin

  //ReportMemoryLeaksOnShutdown := True;

  try

    ApplicationLauncher :=
      TApplicationLauncher.Create(
        TUIApplicationConfigurator.Create
      );

    ApplicationLauncher.Launch;

  finally

    FreeAndNil(ApplicationLauncher);

  end;  

end.
