program DocumentFlowSystemPresentationLayer;

uses
  Forms,
  TestFormUnit in 'TestFormUnit.pas' {Form5},
  ApplicationMainFormUnit in 'ApplicationMainFormUnit.pas' {ApplicationMainForm},
  AuxWindowsFunctionsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxWindowsFunctions\AuxWindowsFunctionsUnit.pas',
  DocumentMainInformationFrameUnit in 'Document Info Forms\Common\DocumentMainInformationFrameUnit.pas' {DocumentMainInformationFrame: TFrame},
  DocumentInformationFrameUnit in 'Document Info Forms\Common\DocumentInformationFrameUnit.pas' {DocumentInformationFrame: TFrame},
  ScrollableFrameUnit in 'Document Info Forms\Common\ScrollableFrameUnit.pas' {ScrollableFrame: TFrame},
  ServiceNoteMainInformationUnit in 'Document Info Forms\Service Notes\ServiceNoteMainInformationUnit.pas' {ServiceNoteMainInformationFrame: TFrame},
  DocumentReceiversFrameUnit in 'Document Info Forms\Common\DocumentReceiversFrameUnit.pas' {DocumentReceiversFrame: TFrame},
  DocumentRelationsFrameUnit in 'Document Info Forms\Common\DocumentRelationsFrameUnit.pas' {DocumentRelationsFrame: TFrame},
  DocumentFilesFrameUnit in 'Document Info Forms\Common\DocumentFilesFrameUnit.pas' {DocumentFilesFrame: TFrame},
  VariantTypeUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\VariantTypeUnit.pas',
  DBDataTableFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\DBDataTableFormUnit.pas' {DBDataTableForm},
  TableViewFilterFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\TableViewFilterFormUnit.pas' {TableViewFilterForm},
  AuxSystemFunctionsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxSystemFunctions\AuxSystemFunctionsUnit.pas',
  AuxZeosFunctions in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxZeosFunctions\AuxZeosFunctions.pas',
  AuxCollectionFunctionsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxCollectionFunctions\AuxCollectionFunctionsUnit.pas',
  StackedControlUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Stacked Control\StackedControlUnit.pas',
  DocumentRelationsDBTableFormUnit in 'Document Info Forms\Common\Table Forms\DocumentRelationsDBTableFormUnit.pas' {DocumentRelationsDBTableForm},
  DocumentFilesDBTableFormUnit in 'Document Info Forms\Common\Table Forms\DocumentFilesDBTableFormUnit.pas' {DocumentFilesDBTableForm},
  AuxDebugFunctionsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxDebugFunctions\AuxDebugFunctionsUnit.pas',
  ApplicationDataModuleUnit in 'Data Interfaces\ApplicationDataModuleUnit.pas' {ApplicationDataModule: TDataModule},
  ServiceNoteCardFrameFactoryUnit in 'Document Card Form\Service Notes\ServiceNoteCardFrameFactoryUnit.pas',
  DocumentCardFrameFactoryUnit in 'Document Card Form\Common\DocumentCardFrameFactoryUnit.pas',
  DocumentCardFrameUnit in 'Document Card Form\Common\DocumentCardFrameUnit.pas' {DocumentCardFrame: TFrame},
  DocumentCardFormUnit in 'Document Card Form\Common\DocumentCardFormUnit.pas' {DocumentCardForm},
  ColoredPageControlUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Colored Page Control\ColoredPageControlUnit.pas',
  Unit1 in 'Unit1.pas' {Form1},
  DocumentFlowSystemBaseTableFormUnit in 'Document Info Forms\Common\Table Forms\DocumentFlowSystemBaseTableFormUnit.pas' {DocumentFlowSystemBaseTableForm},
  CreatableServiceNoteMainInformationFrameUnit in 'Document Info Forms\Service Notes\CreatableServiceNoteMainInformationFrameUnit.pas' {CreatableServiceNoteMainInformationFrame: TFrame},
  CreatableServiceNoteCardFrameUnit in 'Document Card Form\Service Notes\CreatableServiceNoteCardFrameUnit.pas' {CreatableServiceNoteCardFrame: TFrame},
  SignableServiceNoteForLeaderCardFrameUnit in 'Document Card Form\Service Notes\SignableServiceNoteForLeaderCardFrameUnit.pas' {SignableServiceNoteForLeaderCardFrame: TFrame},
  SignableServiceNoteForCreatorCardFrameUnit in 'Document Card Form\Service Notes\SignableServiceNoteForCreatorCardFrameUnit.pas' {SignableServiceNoteForCreatorCardFrame: TFrame},
  SignedServiceNoteMainInformationFrameUnit in 'Document Info Forms\Service Notes\SignedServiceNoteMainInformationFrameUnit.pas' {SignedServiceNoteMainInformationFrame: TFrame},
  SignedServiceNoteForCreatorCardFrameUnit in 'Document Card Form\Service Notes\SignedServiceNoteForCreatorCardFrameUnit.pas' {SignedServiceNoteForCreatorCardFrame: TFrame},
  SignedServiceNoteForLeaderCardFrameUnit in 'Document Card Form\Service Notes\SignedServiceNoteForLeaderCardFrameUnit.pas' {SignedServiceNoteForLeaderCardFrame: TFrame},
  PerformableServiceNoteCardFrameUnit in 'Document Card Form\Service Notes\PerformableServiceNoteCardFrameUnit.pas' {PerformableServiceNoteCardFrame: TFrame},
  PerformedServiceNoteCardFrameUnit in 'Document Card Form\Service Notes\PerformedServiceNoteCardFrameUnit.pas' {PerformedServiceNoteCardFrame: TFrame},
  DocumentCardViewModelUnit in 'Document Card Form\Common\DocumentCardViewModelUnit.pas',
  DocumentFilesPageViewModelUnit in 'Document Info Forms\Common\View Models\DocumentFilesPageViewModelUnit.pas',
  DocumentMainInformationPageViewModelUnit in 'Document Info Forms\Common\View Models\DocumentMainInformationPageViewModelUnit.pas',
  DocumentReceiversPageViewModelUnit in 'Document Info Forms\Common\View Models\DocumentReceiversPageViewModelUnit.pas',
  DocumentRelationsPageViewModelUnit in 'Document Info Forms\Common\View Models\DocumentRelationsPageViewModelUnit.pas',
  SignedServiceNoteMainInformationPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\SignedServiceNoteMainInformationPageViewModelUnit.pas',
  CreatableServiceNoteMainInformationPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\CreatableServiceNoteMainInformationPageViewModelUnit.pas',
  ServiceNoteMainInformationPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\ServiceNoteMainInformationPageViewModelUnit.pas',
  DocumentResponsibleViewModelUnit in 'Document Info Forms\Common\View Models\DocumentResponsibleViewModelUnit.pas',
  DocumentSignerViewModelUnit in 'Document Info Forms\Common\View Models\DocumentSignerViewModelUnit.pas',
  ServiceNoteCardViewModelUnit in 'Document Card Form\Service Notes\View Models\ServiceNoteCardViewModelUnit.pas',
  SignedServiceNoteCardViewModelUnit in 'Document Card Form\Service Notes\View Models\SignedServiceNoteCardViewModelUnit.pas',
  EmployeesReferenceFormUnit in 'Other Forms\EmployeesReferenceFormUnit.pas' {EmployeesReferenceForm},
  DocumentSignersReferenceFormUnit in 'Document Info Forms\Common\Table Forms\DocumentSignersReferenceFormUnit.pas' {DocumentSignersReferenceForm},
  DocumentResponsiblesReferenceFormUnit in 'Document Info Forms\Common\Table Forms\DocumentResponsiblesReferenceFormUnit.pas' {DocumentResponsiblesReferenceForm},
  TestDocumentReceiversFormUnit in 'Document Info Forms\Common\TestDocumentReceiversFormUnit.pas' {TestDocumentReceiversForm},
  DocumentDBViewDataSetsDataModuleUnit in 'Data Interfaces\DocumentDBViewDataSetsDataModuleUnit.pas' {DocumentDBViewDataSetsDataModule: TDataModule},
  IDocumentViewDataSetRegistryUnit in 'Data Interfaces\IDocumentViewDataSetRegistryUnit.pas',
  DocumentDBViewDataSetRegistryUnit in 'Data Interfaces\DocumentDBViewDataSetRegistryUnit.pas',
  EmployeeDocumentsReferenceFormUnit in 'EmployeeDocumentsReferenceFormUnit.pas' {EmployeeDocumentsReferenceForm},
  IWorkingEmployeeUnit in 'Working Employee\IWorkingEmployeeUnit.pas',
  WorkingEmployeeUnit in 'Working Employee\WorkingEmployeeUnit.pas',
  DBWorkingEmployeeUnit in 'Working Employee\DBWorkingEmployeeUnit.pas',
  ZeosPostgresWorkingEmployeeUnit in 'Working Employee\ZeosPostgresWorkingEmployeeUnit.pas',
  DocumentFileUnit in '..\Domain\Documents\DocumentFileUnit.pas',
  DocumentRelationsUnit in '..\Domain\Documents\DocumentRelationsUnit.pas',
  DocumentUnit in '..\Domain\Documents\DocumentUnit.pas',
  DocumentWorkCycleUnit in '..\Domain\Documents\DocumentWorkCycleUnit.pas',
  IncommingServiceNoteUnit in '..\Domain\Documents\IncommingServiceNoteUnit.pas',
  OutcommingServiceNoteUnit in '..\Domain\Documents\OutcommingServiceNoteUnit.pas',
  PerformableDocumentUnit in '..\Domain\Documents\PerformableDocumentUnit.pas',
  ServiceNoteUnit in '..\Domain\Documents\ServiceNoteUnit.pas',
  RoleUnit in '..\Domain\RoleUnit.pas',
  EmployeeUnit in '..\Domain\EmployeeUnit.pas',
  OutcommingServiceNoteCardFrameFactoryUnit in 'Document Card Form\Service Notes\OutcommingServiceNoteCardFrameFactoryUnit.pas',
  IncommingServiceNoteCardFrameFactoryUnit in 'Document Card Form\Service Notes\IncommingServiceNoteCardFrameFactoryUnit.pas',
  DocumentCardViewModelFactoryUnit in 'Document Card Form\Common\DocumentCardViewModelFactoryUnit.pas',
  ServiceNoteCardViewModelFactoryUnit in 'Document Card Form\Service Notes\ServiceNoteCardViewModelFactoryUnit.pas',
  OutcommingServiceNoteCardViewModelFactoryUnit in 'Document Card Form\Service Notes\OutcommingServiceNoteCardViewModelFactoryUnit.pas',
  IncommingServiceNoteCardViewModelFactoryUnit in 'Document Card Form\Service Notes\IncommingServiceNoteCardViewModelFactoryUnit.pas',
  ServiceNoteFilesPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\ServiceNoteFilesPageViewModelUnit.pas',
  ServiceNoteReceiversPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\ServiceNoteReceiversPageViewModelUnit.pas',
  ServiceNoteRelationsPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\ServiceNoteRelationsPageViewModelUnit.pas',
  DocumentCardFrameFactoryRegistryUnit in 'Document Card Form\Common\DocumentCardFrameFactoryRegistryUnit.pas',
  DocumentCardViewModelFactoryRegistryUnit in 'Document Card Form\Common\DocumentCardViewModelFactoryRegistryUnit.pas',
  ServiceDocumentKindsUnit in 'ServiceDocumentKindsUnit.pas',
  DocumentComponentViewDataSetsUnit in 'Data Interfaces\DocumentComponentViewDataSetsUnit.pas',
  DocumentComponentViewDataSetsRegistryUnit in 'Data Interfaces\DocumentComponentViewDataSetsRegistryUnit.pas',
  DocumentComponentViewDataSetsDataModuleUnit in 'Data Interfaces\DocumentComponentViewDataSetsDataModuleUnit.pas' {DocumentComponentViewDataSetsDataModule: TDataModule},
  IncommingServiceNoteReceiversAndPerformersFrameUnit in 'Document Info Forms\Service Notes\IncommingServiceNoteReceiversAndPerformersFrameUnit.pas' {IncommingServiceNoteReceiversAndPerformersFrame: TFrame},
  DocumentKindResolverUnit in 'Data Interfaces\DocumentKindResolverUnit.pas',
  DocumentIdResolverUnit in 'Data Interfaces\DocumentIdResolverUnit.pas',
  ISendingToPerformingDocumentServiceUnit in '..\Application Service Layer\Interfaces\ISendingToPerformingDocumentServiceUnit.pas',
  IDocumentNumeratorRegistryUnit in '..\Data Access Layer\Document Numerators\IDocumentNumeratorRegistryUnit.pas',
  DocumentReceiversPageViewModelFactoryUnit in 'Document Info Forms\Common\View Models\DocumentReceiversPageViewModelFactoryUnit.pas',
  DocumentSigningServiceUnit in '..\Application Service Layer\Common\DocumentSigningServiceUnit.pas',
  DocumentCardFrameServiceUnit in '..\Application Service Layer\Common\DocumentCardFrameServiceUnit.pas',
  DocumentPerformingsChangesSavingServiceUnit in '..\Application Service Layer\Common\DocumentPerformingsChangesSavingServiceUnit.pas',
  DocumentPerformingServiceUnit in '..\Application Service Layer\Common\DocumentPerformingServiceUnit.pas',
  DocumentRejectingServiceUnit in '..\Application Service Layer\Common\DocumentRejectingServiceUnit.pas',
  SendingToSigningDocumentServiceUnit in '..\Application Service Layer\Common\SendingToSigningDocumentServiceUnit.pas',
  SendingToSigningServiceNoteServiceUnit in '..\Application Service Layer\Service Notes\SendingToSigningServiceNoteServiceUnit.pas',
  SendingToPerformingServiceNoteServiceUnit in '..\Application Service Layer\Service Notes\SendingToPerformingServiceNoteServiceUnit.pas',
  ServiceNoteSigningServiceUnit in '..\Application Service Layer\Service Notes\ServiceNoteSigningServiceUnit.pas',
  ServiceNoteCardFrameServiceUnit in '..\Application Service Layer\Service Notes\ServiceNoteCardFrameServiceUnit.pas',
  ServiceNoteRejectingServiceUnit in '..\Application Service Layer\Service Notes\ServiceNoteRejectingServiceUnit.pas',
  EditDocumentPerformingsInfoUnit in '..\Common\EditDocumentPerformingsInfoUnit.pas',
  DocumentApplicationServiceRegistryUnit in '..\Application Service Layer\DocumentApplicationServiceRegistryUnit.pas',
  IncommingServiceNotePerformingsChangesSavingServiceUnit in '..\Application Service Layer\Service Notes\Incommings\IncommingServiceNotePerformingsChangesSavingServiceUnit.pas',
  IncommingServiceNoteCardFrameServiceUnit in '..\Application Service Layer\Service Notes\Incommings\IncommingServiceNoteCardFrameServiceUnit.pas',
  IncommingServiceNotePerformingServiceUnit in '..\Application Service Layer\Service Notes\Incommings\IncommingServiceNotePerformingServiceUnit.pas',
  OutcommingServiceNoteCardFrameServiceUnit in '..\Application Service Layer\Service Notes\Outcommings\OutcommingServiceNoteCardFrameServiceUnit.pas',
  OutcommingServiceNotePerformingsChangesSavingServiceUnit in '..\Application Service Layer\Service Notes\Outcommings\OutcommingServiceNotePerformingsChangesSavingServiceUnit.pas',
  OutcommingServiceNotePerformingServiceUnit in '..\Application Service Layer\Service Notes\Outcommings\OutcommingServiceNotePerformingServiceUnit.pas',
  IncommingServiceNoteReceiversPageViewModelFactoryUnit in 'Document Info Forms\Service Notes\View Models\IncommingServiceNoteReceiversPageViewModelFactoryUnit.pas',
  DocumentNumeratorRegistryUnit in '..\Data Access Layer\Document Numerators\DocumentNumeratorRegistryUnit.pas',
  ApplicationStarterUnit in '..\Composition Root\ApplicationStarterUnit.pas',
  LoginFrm in 'D:\Common Delphi Libs\DelphLib\LoginFrm.pas' {LoginForm},
  DepartmentRepositoryUnit in '..\Data Access Layer\Repositories\DepartmentRepositoryUnit.pas',
  DocumentFilesRepositoryUnit in '..\Data Access Layer\Repositories\DocumentFilesRepositoryUnit.pas',
  DocumentRelationsRepositoryUnit in '..\Data Access Layer\Repositories\DocumentRelationsRepositoryUnit.pas',
  EmployeeRepositoryUnit in '..\Data Access Layer\Repositories\EmployeeRepositoryUnit.pas',
  IncommingServiceNoteRepositoryUnit in '..\Data Access Layer\Repositories\IncommingServiceNoteRepositoryUnit.pas',
  OutcommingServiceNoteRepositoryUnit in '..\Data Access Layer\Repositories\OutcommingServiceNoteRepositoryUnit.pas',
  RepositoryRegistryUnit in '..\Data Access Layer\Repositories\RepositoryRegistryUnit.pas',
  ServiceNoteFilesRepositoryUnit in '..\Data Access Layer\Repositories\ServiceNoteFilesRepositoryUnit.pas',
  RoleRepositoryUnit in '..\Data Access Layer\Repositories\RoleRepositoryUnit.pas',
  ServiceNotePostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\ServiceNotePostgresRepositoryUnit.pas',
  AbstractZeosPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\AbstractZeosPostgresRepositoryUnit.pas',
  DepartmentPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DepartmentPostgresRepositoryUnit.pas',
  DocumentFilesPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentFilesPostgresRepositoryUnit.pas',
  DocumentPerformingPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentPerformingPostgresRepositoryUnit.pas',
  DocumentPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentPostgresRepositoryUnit.pas',
  DocumentReceiversPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentReceiversPostgresRepositoryUnit.pas',
  DocumentRelationsPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentRelationsPostgresRepositoryUnit.pas',
  EmployeePostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\EmployeePostgresRepositoryUnit.pas',
  IncommingServiceNotePerformingPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\IncommingServiceNotePerformingPostgresRepositoryUnit.pas',
  IncommingServiceNotePostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\IncommingServiceNotePostgresRepositoryUnit.pas',
  OutcommingServiceNoteSignerPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\OutcommingServiceNoteSignerPostgresRepositoryUnit.pas',
  OutcommingServiceNotePerformingPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\OutcommingServiceNotePerformingPostgresRepositoryUnit.pas',
  OutcommingServiceNotePostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\OutcommingServiceNotePostgresRepositoryUnit.pas',
  PerformableDocumentPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\PerformableDocumentPostgresRepositoryUnit.pas',
  RolePostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\RolePostgresRepositoryUnit.pas',
  ServiceNoteFilesPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\ServiceNoteFilesPostgresRepositoryUnit.pas',
  ServiceNotePerformingPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\ServiceNotePerformingPostgresRepositoryUnit.pas',
  AbstractDBRepositoryUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\AbstractDBRepositoryUnit.pas',
  AbstractRepositoryUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\AbstractRepositoryUnit.pas',
  AbstractZeosDBRepositoryUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\AbstractZeosDBRepositoryUnit.pas',
  DBTableColumnMappingsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\DBTableColumnMappingsUnit.pas',
  DBTableMappingUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\DBTableMappingUnit.pas',
  DomainObjectFromDataSetLoaderUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\DomainObjectFromDataSetLoaderUnit.pas',
  TableColumnMappingsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\TableColumnMappingsUnit.pas',
  TableMappingUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\TableMappingUnit.pas',
  TestZeosDBRepositoryUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Repositories\TestZeosDBRepositoryUnit.pas',
  DocumentServiceUnit in '..\Application Service Layer\Common\DocumentServiceUnit.pas',
  DatabaseTransactionUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Session\DatabaseTransactionUnit.pas',
  ISessionUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Session\ISessionUnit.pas',
  PostgresTransactionUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Session\PostgresTransactionUnit.pas',
  ZeosPostgresTransactionUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Repositories and Domain\Session\ZeosPostgresTransactionUnit.pas',
  NotImplementedExceptionUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\Misceleneous\Exceptions\NotImplementedExceptionUnit.pas',
  DocumentViewDataSetRegistryUnit in 'Data Interfaces\DocumentViewDataSetRegistryUnit.pas',
  ModifiedDocumentInfoUnit in '..\Application Service Layer\Common\ModifiedDocumentInfoUnit.pas',
  DocumentResponsibleZeosPostgresRepositoryUnit in '..\Data Access Layer\Repositories\Postgres\DocumentResponsibleZeosPostgresRepositoryUnit.pas',
  CentralEmployeeDocumentsReferenceFormUnit in 'Central Employee Document References\CentralEmployeeDocumentsReferenceFormUnit.pas' {CentralEmployeeDocumentsReferenceForm},
  CentralEmployeeIncommingServiceNotesReferenceFormUnit in 'Central Employee Document References\CentralEmployeeIncommingServiceNotesReferenceFormUnit.pas' {CentralEmployeeIncommingServiceNotesReferenceForm},
  OutcommingServiceNoteReceiversAndPerformersFrameUnit in 'Document Info Forms\Service Notes\OutcommingServiceNoteReceiversAndPerformersFrameUnit.pas' {OutcommingServiceNoteReceiversAndPerformersFrame: TFrame},
  IDocumentComponentViewDataSetsRegistryUnit in 'Data Interfaces\IDocumentComponentViewDataSetsRegistryUnit.pas',
  DocumentComponentViewDataSetsZeosPostgresRegistryUnit in 'Data Interfaces\DocumentComponentViewDataSetsZeosPostgresRegistryUnit.pas',
  AuxDataSetFunctionsUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\AuxDataSetFunctions\AuxDataSetFunctionsUnit.pas',
  CentralEmployeeDocumentsReferenceFormFactoryUnit in 'Central Employee Document References\CentralEmployeeDocumentsReferenceFormFactoryUnit.pas',
  IncommingServiceNoteMainInformationPageViewModelUnit in 'Document Info Forms\Service Notes\View Models\IncommingServiceNoteMainInformationPageViewModelUnit.pas',
  EmployeeDocumentViewDataSetEditorUnit in 'Employee Document View DataSet Editors\EmployeeDocumentViewDataSetEditorUnit.pas',
  EmployeeIncommingServiceNoteViewDataSetEditorUnit in 'Employee Document View DataSet Editors\EmployeeIncommingServiceNoteViewDataSetEditorUnit.pas',
  EmployeeDocumentViewDataSetEditorFactoryUnit in 'Employee Document View DataSet Editors\EmployeeDocumentViewDataSetEditorFactoryUnit.pas',
  DocumentWorkCycleStageColorRegistryUnit in 'Document Work Cycle Stages Colors\DocumentWorkCycleStageColorRegistryUnit.pas',
  DocumentWorkCycleStageNumberReferenceUnit in '..\Common\DocumentWorkCycleStageNumberReferenceUnit.pas',
  SignableServiceNoteForCreatorLeaderCardFrameUnit in 'Document Card Form\Service Notes\SignableServiceNoteForCreatorLeaderCardFrameUnit.pas' {SignableServiceNoteForCreatorLeaderCardFrame: TFrame},
  SignedServiceNoteForCreatorLeaderCardFrameUnit in 'Document Card Form\Service Notes\SignedServiceNoteForCreatorLeaderCardFrameUnit.pas' {SignedServiceNoteForCreatorLeaderCardFrame: TFrame},
  InputMemoFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\User Input Forms\InputMemoFormUnit.pas' {InputMemoForm},
  DocumentInfoInputMemoFormUnit in 'Common User Input Forms\DocumentInfoInputMemoFormUnit.pas' {DocumentInfoInputMemoForm};

{$R *.res}

begin

  TApplicationStarter.Start;
  
end.
