program Presentation;

uses
  madExcept,
  madLinkDisAsm,
  madListHardware,
  madListProcesses,
  madListModules,
  Forms,
  Classes,
  SysUtils,
  DocumentIdResolverUnit in 'Data Interfaces\DocumentIdResolverUnit.pas',
  DocumentFilesViewDataSetInfoHolderUnit in 'Data Interfaces\DocumentFilesViewDataSetInfoHolderUnit.pas',
  DocumentRelationsViewDataSetInfoHolderUnit in 'Data Interfaces\DocumentRelationsViewDataSetInfoHolderUnit.pas',
  DocumentReceiversViewDataSetInfoHolderUnit in 'Data Interfaces\DocumentReceiversViewDataSetInfoHolderUnit.pas',
  Controller in 'Controllers\Controller.pas',
  DocumentTypesPanelController in 'Controllers\DocumentTypesPanelController.pas',
  EmployeeDocumentsReferenceFormController in 'Controllers\EmployeeDocumentsReferenceFormController.pas',
  SystemAdministrationController in 'Controllers\SystemAdministrationController.pas',
  DocumentApprovingsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingsFormViewModelMapper.pas',
  DocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapper.pas',
  DocumentCardFormViewModelMapperFactories in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactories.pas',
  DocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\DocumentCardFormViewModelMapperFactory.pas',
  DocumentChargesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentChargesFormViewModelMapper.pas',
  DocumentFilesFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesFormViewModelMapper.pas',
  DocumentFilesViewFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentFilesViewFormViewModelMapper.pas',
  DocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentMainInformationFormViewModelMapper.pas',
  DocumentRelationsFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentRelationsFormViewModelMapper.pas',
  DocumentResponsibleViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentResponsibleViewModelMapper.pas',
  DocumentSignerViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentSignerViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapper.pas',
  IncomingDocumentCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentCardFormViewModelMapperFactory.pas',
  IncomingDocumentMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\IncomingDocumentMainInformationFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapper.pas',
  IncomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteCardFormViewModelMapperFactory.pas',
  IncomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\IncomingServiceNoteMainInformationFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapper.pas',
  OutcomingServiceNoteCardFormViewModelMapperFactory in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteCardFormViewModelMapperFactory.pas',
  OutcomingServiceNoteMainInformationFormViewModelMapper in 'ViewModel Mappers\Documents\Cards\Service Notes\OutcomingServiceNoteMainInformationFormViewModelMapper.pas',
  ScrollableFrameUnit in 'Forms\Common\Frames\ScrollableFrameUnit.pas' {ScrollableFrame: TFrame},
  IncomingDocumentMainInformationFormViewModel in 'Forms\Documents\Frames\View Models\IncomingDocumentMainInformationFormViewModel.pas',
  DocumentApprovingsFormViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingsFormViewModel.pas',
  DocumentApprovingViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingViewModel.pas',
  DocumentFileInfoList in 'Forms\Documents\Frames\View Models\DocumentFileInfoList.pas',
  DocumentFilesFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentFilesFormViewModelUnit.pas',
  DocumentFilesPageViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentFilesPageViewModelUnit.pas',
  DocumentFilesViewFormViewModel in 'Forms\Documents\Frames\View Models\DocumentFilesViewFormViewModel.pas',
  DocumentMainInformationFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentMainInformationFormViewModelUnit.pas',
  DocumentReceiversFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentReceiversFormViewModelUnit.pas',
  DocumentReceiversPageViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentReceiversPageViewModelUnit.pas',
  DocumentRelationsFormViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentRelationsFormViewModelUnit.pas',
  DocumentRelationsPageViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentRelationsPageViewModelUnit.pas',
  DocumentResponsibleViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentResponsibleViewModelUnit.pas',
  DocumentSignerViewModelUnit in 'Forms\Documents\Frames\View Models\DocumentSignerViewModelUnit.pas',
  SignedDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\SignedDocumentMainInformationFrameUnit.pas' {SignedDocumentMainInformationFrame: TFrame},
  CreateableDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\CreateableDocumentMainInformationFrameUnit.pas' {CreatableDocumentMainInformationFrame: TFrame},
  DocumentApproversInfoFormUnit in 'Forms\Documents\Frames\DocumentApproversInfoFormUnit.pas' {DocumentApproversInfoForm},
  DocumentApprovingsFrameUnit in 'Forms\Documents\Frames\DocumentApprovingsFrameUnit.pas' {DocumentApprovingsFrame: TFrame},
  DocumentFilesFrameUnit in 'Forms\Documents\Frames\DocumentFilesFrameUnit.pas' {DocumentFilesFrame: TFrame},
  DocumentFilesViewFormUnit in 'Forms\Documents\Frames\DocumentFilesViewFormUnit.pas' {DocumentFilesViewForm},
  DocumentFlowPDFViewFormUnit in 'Forms\Documents\Frames\DocumentFlowPDFViewFormUnit.pas' {DocumentFlowPDFViewForm},
  DocumentInformationFrameUnit in 'Forms\Documents\Frames\DocumentInformationFrameUnit.pas' {DocumentInformationFrame: TFrame},
  DocumentMainInformationFrameUnit in 'Forms\Documents\Frames\DocumentMainInformationFrameUnit.pas' {DocumentMainInformationFrame: TFrame},
  DocumentChargesFrameUnit in 'Forms\Documents\Frames\DocumentChargesFrameUnit.pas' {DocumentChargesFrame: TFrame},
  DocumentRelationsFrameUnit in 'Forms\Documents\Frames\DocumentRelationsFrameUnit.pas' {DocumentRelationsFrame: TFrame},
  ExtendedDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\ExtendedDocumentMainInformationFrameUnit.pas' {ExtendedDocumentMainInformationFrame: TFrame},
  IncommingDocumentMainInformationFrameUnit in 'Forms\Documents\Frames\IncommingDocumentMainInformationFrameUnit.pas' {IncommingDocumentMainInformationFrame: TFrame},
  IncomingDocumentChargesFrameUnit in 'Forms\Documents\Frames\IncomingDocumentChargesFrameUnit.pas' {IncomingDocumentChargesFrame: TFrame},
  OutcomingDocumentChargesFrameUnit in 'Forms\Documents\Frames\OutcomingDocumentChargesFrameUnit.pas' {OutcomingDocumentChargesFrame: TFrame},
  DocumentCardViewModelUnit in 'Forms\Documents\Cards\Common\View Models\DocumentCardViewModelUnit.pas',
  IncomingDocumentCardFormViewModel in 'Forms\Documents\Cards\Common\View Models\IncomingDocumentCardFormViewModel.pas',
  DocumentCardFrameFactories in 'Forms\Documents\Cards\Common\Factories\DocumentCardFrameFactories.pas',
  DocumentCardFrameFactory in 'Forms\Documents\Cards\Common\Factories\DocumentCardFrameFactory.pas',
  IncomingDocumentCardFrameFactory in 'Forms\Documents\Cards\Common\Factories\IncomingDocumentCardFrameFactory.pas',
  DocumentCardFormUnit in 'Forms\Documents\Cards\Common\DocumentCardFormUnit.pas' {DocumentCardForm},
  DocumentCardFrameUnit in 'Forms\Documents\Cards\Common\DocumentCardFrameUnit.pas' {DocumentCardFrame: TFrame},
  BaseEmployeeDocumentsReferenceFilterFormUnit in 'Forms\Documents\References\Common\BaseEmployeeDocumentsReferenceFilterFormUnit.pas' {BaseEmployeeDocumentsReferenceFilterForm},
  BaseEmployeeDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\BaseEmployeeDocumentsReferenceFormUnit.pas' {BaseEmployeeDocumentsReferenceForm},
  EmployeeDocumentsReferenceFormFactoryUnit in 'Forms\Documents\References\Common\Factories\EmployeeDocumentsReferenceFormFactoryUnit.pas',
  EmployeeDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Employee\EmployeeDocumentsReferenceFormUnit.pas' {EmployeeDocumentsReferenceForm},
  EmployeeIncomingDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Employee\EmployeeIncomingDocumentsReferenceFormUnit.pas' {EmployeeIncomingDocumentsReferenceForm},
  EmployeeDocumentsForApprovingReferenceFormUnit in 'Forms\Documents\References\Common\Employee\EmployeeDocumentsForApprovingReferenceFormUnit.pas' {EmployeeDocumentsForApprovingReferenceForm},
  DocumentRecordViewModel in 'Forms\Documents\References\Common\Employee\View Models\DocumentRecordViewModel.pas',
  EmployeeDocumentsReferenceViewModel in 'Forms\Documents\References\Common\Employee\View Models\EmployeeDocumentsReferenceViewModel.pas',
  EmployeeDocumentTableViewModel in 'Forms\Documents\References\Common\Employee\View Models\EmployeeDocumentTableViewModel.pas',
  IncomingDocumentRecordViewModel in 'Forms\Documents\References\Common\Employee\View Models\IncomingDocumentRecordViewModel.pas',
  ColumnCellComparator in 'Forms\Documents\References\Common\Employee\Column Cell Comparators\ColumnCellComparator.pas',
  DefaultColumnCellComparator in 'Forms\Documents\References\Common\Employee\Column Cell Comparators\DefaultColumnCellComparator.pas',
  DocumentNumberColumnCellComparator in 'Forms\Documents\References\Common\Employee\Column Cell Comparators\DocumentNumberColumnCellComparator.pas',
  EmployeeServiceNotesReferenceViewModel in 'Forms\Documents\References\Service Notes\Employee\View Models\EmployeeServiceNotesReferenceViewModel.pas',
  EmployeeServiceNoteTableViewModel in 'Forms\Documents\References\Service Notes\Employee\View Models\EmployeeServiceNoteTableViewModel.pas',
  ServiceNoteNumberColumnCellComparator in 'Forms\Documents\References\Service Notes\Employee\Column Cell Comparators\ServiceNoteNumberColumnCellComparator.pas',
  DocumentFlowWorkingFormUnit in 'Forms\Documents\Primary Screens\DocumentFlowWorkingFormUnit.pas' {DocumentFlowWorkingForm},
  DocumentSelectionFormUnit in 'Forms\Documents\Primary Screens\DocumentSelectionFormUnit.pas' {DocumentSelectionForm},
  SystemAdministrationFormUnit in 'Forms\System Administration\Forms\SystemAdministrationFormUnit.pas' {SystemAdministrationForm},
  SystemAdministrationFormViewModel in 'Forms\System Administration\Forms\View Models\SystemAdministrationFormViewModel.pas',
  SystemAdministrationSectionContentFormViewModel in 'Forms\System Administration\Forms\View Models\SystemAdministrationSectionContentFormViewModel.pas',
  SystemAdministrationSectionViewModel in 'Forms\System Administration\Forms\View Models\SystemAdministrationSectionViewModel.pas',
  DocumentFlowSystemInputMemoFormUnit in 'Forms\Common\Field-Targeted\DocumentFlowSystemInputMemoFormUnit.pas' {DocumentFlowSystemInputMemoForm},
  CommonControlStyles in 'Forms\Common\Styles\CommonControlStyles.pas',
  EmployeeCardFormUnit in 'Forms\Employees\Cards\Management\EmployeeCardFormUnit.pas' {EmployeeCardForm},
  DocumentChargeSheetsChangesInfoDTOMapper in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapper.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactories in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactories.pas',
  DocumentChargeSheetsChangesInfoDTOMapperFactory in 'DTO-Mappers\Documents\Charge Sheets\Common\DocumentChargeSheetsChangesInfoDTOMapperFactory.pas',
  DocumentApprovingCyclesDataSetHolder in 'DataSet Holders\Documents\Common\DocumentApprovingCyclesDataSetHolder.pas',
  AbstractDocumentDataSetHoldersFactory in 'DataSet Holders\Documents\Factories\AbstractDocumentDataSetHoldersFactory.pas',
  DevExpressDocumentDataSetHoldersFactory in 'DataSet Holders\Documents\Factories\DevExpressDocumentDataSetHoldersFactory.pas',
  EhLibDocumentDataSetHoldersFactory in 'DataSet Holders\Documents\Factories\EhLibDocumentDataSetHoldersFactory.pas',
  ZeosDocumentDataSetHoldersFactory in 'DataSet Holders\Documents\Factories\ZeosDocumentDataSetHoldersFactory.pas',
  EmployeeDocumentsForApprovingReferenceDataSetHolder in 'DataSet Holders\References\Common\EmployeeDocumentsForApprovingReferenceDataSetHolder.pas',
  EmployeeDocumentsReferenceDataSetHolder in 'DataSet Holders\References\Common\EmployeeDocumentsReferenceDataSetHolder.pas',
  EmployeesReferenceDataSetHolder in 'DataSet Holders\References\Common\EmployeesReferenceDataSetHolder.pas',
  ReferenceDataSetHolderFactory in 'DataSet Holders\References\Factories\ReferenceDataSetHolderFactory.pas',
  ZeosReferenceDataSetHolderFactory in 'DataSet Holders\References\Factories\ZeosReferenceDataSetHolderFactory.pas',
  SystemAdministrationSectionSetHolder in 'DataSet Holders\System Administration\Common\SystemAdministrationSectionSetHolder.pas',
  UIDocumentKinds in 'Document Kinds\UIDocumentKinds.pas',
  DocumentKindMapper in 'Document Kinds\Mappers\DocumentKindMapper.pas',
  UIDocumentKindResolver in 'Document Kinds\Resolvers\Interfaces\UIDocumentKindResolver.pas',
  NumericUIDocumentKindResolver in 'Document Kinds\Resolvers\NumericUIDocumentKindResolver.pas',
  DocumentRecordViewModelMapper in 'ViewModel Mappers\Documents\References\Common\DocumentRecordViewModelMapper.pas',
  IncomingDocumentRecordViewModelMapper in 'ViewModel Mappers\Documents\References\Common\IncomingDocumentRecordViewModelMapper.pas',
  DocumentRecordViewModelMapperFactory in 'ViewModel Mappers\Documents\References\Common\Factories\DocumentRecordViewModelMapperFactory.pas',
  ExceptionHandling in 'Exception Handling\ExceptionHandling.pas',
  DocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\DocumentReportPresenterRegistry.pas',
  IDocumentReportPresenterRegistryUnit in 'Reporting\Presenters\Registries\IDocumentReportPresenterRegistryUnit.pas',
  StandardDocumentReportPresenterRegistry in 'Reporting\Presenters\Registries\StandardDocumentReportPresenterRegistry.pas',
  DocumentPrintFormPresenter in 'Reporting\Presenters\Print Forms\DocumentPrintFormPresenter.pas',
  ServiceNotePrintFormFastReportPresenter in 'Reporting\Presenters\Print Forms\ServiceNotePrintFormFastReportPresenter.pas',
  frxDocumentPrintFormReportsModule in 'Reporting\Presenters\Print Forms\Data Modules\Fast Report\frxDocumentPrintFormReportsModule.pas' {frxDocumentPrintFormReports: TDataModule},
  NotPerformedDocumentsReportFastReportPresenter in 'Reporting\Presenters\Not Performed Documents\NotPerformedDocumentsReportFastReportPresenter.pas',
  NotPerformedDocumentsReportPresenter in 'Reporting\Presenters\Not Performed Documents\NotPerformedDocumentsReportPresenter.pas',
  frxNotPerformedDocumentsReportObjectsUnit in 'Reporting\Presenters\Not Performed Documents\Data Modules\Fast Report\frxNotPerformedDocumentsReportObjectsUnit.pas' {frxNotPerformedDocumentsReportObjects: TDataModule},
  NotPerformedDocumentsReportShowCustomizeFormUnit in 'Forms\Documents\Reporting\NotPerformedDocumentsReportShowCustomizeFormUnit.pas' {NotPerformedDocumentsReportShowCustomizeForm},
  DepartmentViewModel in 'Forms\Documents\Reporting\View Models\DepartmentViewModel.pas',
  DocumentWorkCycleStageColorRegistryUnit in 'Forms\Documents\Styles\DocumentWorkCycleStageColorRegistryUnit.pas',
  DocumentWorkCycleStageInfoReferenceUnit in 'Forms\Documents\Styles\DocumentWorkCycleStageInfoReferenceUnit.pas',
  ApplicationMainFormUnit in 'Forms\Common\Primary Screens\ApplicationMainFormUnit.pas' {ApplicationMainForm},
  UIApplicationConfigurator in 'Launching\Configuration\UIApplicationConfigurator.pas',
  ApplicationLauncher in 'Launching\ApplicationLauncher.pas',
  DocumentViewingAccountingService in '..\Application\Accounting\Docs\Interfaces\DocumentViewingAccountingService.pas',
  DocumentChargeSheetControlAppService in '..\Application\Business Processes\Docs\Common\Charge Sheets\Interfaces\DocumentChargeSheetControlAppService.pas',
  DocumentStorageService in '..\Application\Business Processes\Docs\Common\Storage\Interfaces\DocumentStorageService.pas',
  DocumentApprovingControlAppService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingControlAppService.pas',
  DocumentApprovingPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingPerformingService.pas',
  DocumentApprovingRejectingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingRejectingService.pas',
  DocumentApprovingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentApprovingService.pas',
  DocumentPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentPerformingService.pas',
  DocumentSigningRejectingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningRejectingService.pas',
  DocumentSigningService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\DocumentSigningService.pas',
  SendingDocumentToApprovingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToApprovingService.pas',
  SendingDocumentToSigningService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToSigningService.pas',
  ApplicationConfigurator in '..\Application\Configuration\ApplicationConfigurator.pas',
  ConfigurationData in '..\Application\Configuration\ConfigurationData.pas',
  IDocumentFileServiceClientUnit in '..\Application\External\Storage\Interfaces\IDocumentFileServiceClientUnit.pas',
  EmployeeDepartmentManagementService in '..\Application\Management\Employees\Interfaces\EmployeeDepartmentManagementService.pas',
  NotPerformedDocumentsReportDataService in '..\Application\Reporting\Docs\Interfaces\NotPerformedDocumentsReportDataService.pas',
  EmployeeDocumentWorkStatistics in '..\Application\Statistics\Docs\Interfaces\EmployeeDocumentWorkStatistics.pas',
  EmployeeDocumentWorkStatisticsService in '..\Application\Statistics\Docs\Interfaces\EmployeeDocumentWorkStatisticsService.pas',
  AccountingServiceRegistry in '..\Application\Accounting\AccountingServiceRegistry.pas',
  DocumentBusinessProcessServiceRegistry in '..\Application\Business Processes\Docs\DocumentBusinessProcessServiceRegistry.pas',
  ExternalServiceRegistry in '..\Application\External\ExternalServiceRegistry.pas',
  ManagementServiceRegistry in '..\Application\Management\ManagementServiceRegistry.pas',
  PresentationServiceRegistry in '..\Application\Presentation\PresentationServiceRegistry.pas',
  ReportingServiceRegistry in '..\Application\Reporting\ReportingServiceRegistry.pas',
  StatisticsServiceRegistry in '..\Application\Statistics\StatisticsServiceRegistry.pas',
  DocumentKinds in '..\Application\Common\DocumentKinds.pas',
  ApplicationService in '..\Application\Common\ApplicationService.pas',
  ApplicationServiceRegistries in '..\Application\Service Registries\ApplicationServiceRegistries.pas',
  ApplicationServiceRegistry in '..\Application\Common\ApplicationServiceRegistry.pas',
  SendingDocumentToPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\Interfaces\SendingDocumentToPerformingService.pas',
  IDocumentUnit in '..\Domain\Documents\Common\Entities\Interfaces\IDocumentUnit.pas',
  Document in '..\Domain\Documents\Common\Entities\Document.pas',
  DocumentApprovingCycle in '..\Domain\Documents\Common\Entities\DocumentApprovingCycle.pas',
  DocumentApprovingCycleResult in '..\Domain\Documents\Common\Entities\DocumentApprovingCycleResult.pas',
  DocumentApprovings in '..\Domain\Documents\Common\Entities\DocumentApprovings.pas',
  DocumentCharges in '..\Domain\Documents\Common\Entities\DocumentCharges.pas',
  DocumentChargeSheet in '..\Domain\Documents\Common\Entities\DocumentChargeSheet.pas',
  DocumentFileUnit in '..\Domain\Documents\Common\Entities\DocumentFileUnit.pas',
  DocumentRelationsUnit in '..\Domain\Documents\Common\Entities\DocumentRelationsUnit.pas',
  DocumentSignings in '..\Domain\Documents\Common\Entities\DocumentSignings.pas',
  DocumentWorkCycle in '..\Domain\Documents\Common\Entities\DocumentWorkCycle.pas',
  IncomingDocument in '..\Domain\Documents\Common\Entities\IncomingDocument.pas',
  IDocumentChargeSheetUnit in '..\Domain\Documents\Common\Entities\Interfaces\IDocumentChargeSheetUnit.pas',
  DocumentChargeSheetsChangesInfoDTO in '..\Application\Business Processes\Docs\Common\DTOs\DocumentChargeSheetsChangesInfoDTO.pas',
  DocumentUsageEmployeeAccessRightsInfoDTO in '..\Application\Business Processes\Docs\Common\DTOs\DocumentUsageEmployeeAccessRightsInfoDTO.pas',
  NewDocumentInfoDTO in '..\Application\Business Processes\Docs\Common\DTOs\NewDocumentInfoDTO.pas',
  ChangedDocumentInfoDTO in '..\Application\Business Processes\Docs\Common\DTOs\ChangedDocumentInfoDTO.pas',
  DocumentApprovingCycleDTO in '..\Application\Business Processes\Docs\Common\DTOs\DocumentApprovingCycleDTO.pas',
  DepartmentInfoDTO in '..\Application\Common\DTOs\DepartmentInfoDTO.pas',
  DocumentChargeSheetsInfoDTO in '..\Application\Common\DTOs\DocumentChargeSheetsInfoDTO.pas',
  DocumentFlowEmployeeInfoDTO in '..\Application\Common\DTOs\DocumentFlowEmployeeInfoDTO.pas',
  DocumentFullInfoDTO in '..\Application\Common\DTOs\DocumentFullInfoDTO.pas',
  DocumentResponsibleInfoDTO in '..\Application\Common\DTOs\DocumentResponsibleInfoDTO.pas',
  EmployeeInfoDTO in '..\Application\Common\DTOs\EmployeeInfoDTO.pas',
  IncomingDocumentFullInfoDTO in '..\Application\Common\DTOs\IncomingDocumentFullInfoDTO.pas',
  BusinessProcessService in '..\Application\Business Processes\Common\BusinessProcessService.pas',
  AbstractApplicationService in '..\Application\Common\AbstractApplicationService.pas',
  NotPerformedDocumentsReportData in '..\Application\Reporting\Docs\Common\NotPerformedDocumentsReportData.pas',
  DocumentCreatingDefaultInfoDTO in '..\Application\Presentation\Docs\DTOs\DocumentCreatingDefaultInfoDTO.pas',
  DocumentChargeSheetCasesNotifier in '..\Application\External\Messaging\Documents\Common\Interfaces\DocumentChargeSheetCasesNotifier.pas',
  DocumentChargeSheetNotifyingMessageBuilder in '..\Application\External\Messaging\Documents\Common\Interfaces\DocumentChargeSheetNotifyingMessageBuilder.pas',
  DocumentRecordsPanelSettingsFormUnit in 'Forms\Documents\Settings\DocumentRecordsPanelSettingsFormUnit.pas' {DocumentRecordsPanelSettingsForm},
  RepositoryRegistryUnit in '..\Persistance\Repositories\Registries\RepositoryRegistryUnit.pas',
  IRepositoryRegistryUnit in '..\Persistance\Repositories\Registries\Interfaces\IRepositoryRegistryUnit.pas',
  BasedOnRepositoryApprovingCycleResultFinder in '..\Persistance\Domain\Services\Documents\Approving\BasedOnRepositoryApprovingCycleResultFinder.pas',
  BasedOnRepositoryDocumentChargeSheetFinder in '..\Persistance\Domain\Services\Documents\Charge Sheets\BasedOnRepositoryDocumentChargeSheetFinder.pas',
  BasedOnRepositoryDocumentResponsibleFinder in '..\Persistance\Domain\Services\Documents\Formalization\BasedOnRepositoryDocumentResponsibleFinder.pas',
  ZeosPostgresDocumentNumeratorRegistryUnit in '..\Persistance\Domain\Services\Documents\Numerators\ZeosPostgresDocumentNumeratorRegistryUnit.pas',
  BasedOnRepositoryDepartmentFinder in '..\Persistance\Domain\Services\Employees\References\BasedOnRepositoryDepartmentFinder.pas',
  BasedOnRepositoryEmployeeFinder in '..\Persistance\Domain\Services\Employees\References\BasedOnRepositoryEmployeeFinder.pas',
  DocumentApprovingCycleResultRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\DocumentApprovingCycleResultRepository.pas',
  DocumentChargeSheetRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\DocumentChargeSheetRepository.pas',
  DocumentFilesRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\DocumentFilesRepository.pas',
  DocumentRelationsRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\DocumentRelationsRepository.pas',
  DocumentRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\DocumentRepository.pas',
  IDocumentResponsibleRepositoryUnit in '..\Persistance\Repositories\Documents\Common\Interfaces\IDocumentResponsibleRepositoryUnit.pas',
  IncomingDocumentRepository in '..\Persistance\Repositories\Documents\Common\Interfaces\IncomingDocumentRepository.pas',
  DocumentApprovingCycleResultZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentApprovingCycleResultZeosPostgresRepository.pas',
  DocumentApprovingZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentApprovingZeosPostgresRepository.pas',
  DocumentChargePostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentChargePostgresRepository.pas',
  DocumentChargeSheetZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentChargeSheetZeosPostgresRepository.pas',
  DocumentFilesPostgresRepositoryUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentFilesPostgresRepositoryUnit.pas',
  DocumentRelationsPostgresRepositoryUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentRelationsPostgresRepositoryUnit.pas',
  DocumentResponsibleZeosPostgresRepositoryUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentResponsibleZeosPostgresRepositoryUnit.pas',
  DocumentSigningPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentSigningPostgresRepository.pas',
  DocumentZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\DocumentZeosPostgresRepository.pas',
  HistoricalDocumentApprovingZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\HistoricalDocumentApprovingZeosPostgresRepository.pas',
  IncomingDocumentZeosPostgresRepository in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\IncomingDocumentZeosPostgresRepository.pas',
  DocumentApprovingResultsTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentApprovingResultsTable.pas',
  DocumentApprovingsTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentApprovingsTable.pas',
  DocumentChargeSheetStageTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentChargeSheetStageTable.pas',
  DocumentChargeSheetTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentChargeSheetTable.pas',
  DocumentChargeTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentChargeTable.pas',
  DocumentDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentDBTableUnit.pas',
  DocumentFilesDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentFilesDBTableUnit.pas',
  DocumentFilesDBViewUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentFilesDBViewUnit.pas',
  DocumentLinksDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentLinksDBTableUnit.pas',
  DocumentReceiversDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentReceiversDBTableUnit.pas',
  DocumentSigningTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentSigningTable.pas',
  DocumentTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentTable.pas',
  DocumentTypesDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentTypesDBTableUnit.pas',
  DocumentTypeStageDBTableUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentTypeStageDBTableUnit.pas',
  DocumentTypeStageTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\DocumentTypeStageTable.pas',
  IncomingDocumentTable in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Schema\IncomingDocumentTable.pas',
  DocumentReceiversRepositoryQueryTexts in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Queries\DocumentReceiversRepositoryQueryTexts.pas',
  DocumentReceiversViewQueryTextsUnit in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Queries\DocumentReceiversViewQueryTextsUnit.pas',
  SelectDocumentRecordsViewQueries in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Queries\SelectDocumentRecordsViewQueries.pas',
  DocumentApprovingCycleResultZeosPostgresRepositoryAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\DocumentApprovingCycleResultZeosPostgresRepositoryAdapter.pas',
  DocumentChargeSheetZeosPostgresRepositoryAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\DocumentChargeSheetZeosPostgresRepositoryAdapter.pas',
  DocumentFilesRepositoryZeosPostgresAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\DocumentFilesRepositoryZeosPostgresAdapter.pas',
  DocumentRelationsRepositoryZeosPostgresAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\DocumentRelationsRepositoryZeosPostgresAdapter.pas',
  DocumentZeosPostgresRepositoryAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\DocumentZeosPostgresRepositoryAdapter.pas',
  IncomingDocumentZeosPostgresRepositoryAdapter in '..\Persistance\Repositories\Documents\Common\SQL\Postgres\Adapters\IncomingDocumentZeosPostgresRepositoryAdapter.pas',
  IncomingServiceNoteRepository in '..\Persistance\Repositories\Documents\Service Notes\Interfaces\IncomingServiceNoteRepository.pas',
  ServiceNoteRepository in '..\Persistance\Repositories\Documents\Service Notes\Interfaces\ServiceNoteRepository.pas',
  ServiceNoteZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteZeosPostgresRepository.pas',
  HistoricalServiceNoteApprovingZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\HistoricalServiceNoteApprovingZeosPostgresRepository.pas',
  IncomingServiceNoteZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\IncomingServiceNoteZeosPostgresRepository.pas',
  ServiceNoteApprovingCycleResultZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteApprovingCycleResultZeosPostgresRepository.pas',
  ServiceNoteApprovingZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteApprovingZeosPostgresRepository.pas',
  ServiceNoteChargePostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteChargePostgresRepository.pas',
  ServiceNoteChargeSheetPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteChargeSheetPostgresRepository.pas',
  ServiceNoteFilesZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteFilesZeosPostgresRepository.pas',
  ServiceNoteRelationsZeosPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteRelationsZeosPostgresRepository.pas',
  ServiceNoteSigningPostgresRepository in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\ServiceNoteSigningPostgresRepository.pas',
  IncomingServiceNoteTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\IncomingServiceNoteTable.pas',
  ServiceNoteApprovingsTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteApprovingsTable.pas',
  ServiceNoteChargeSheetTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteChargeSheetTable.pas',
  ServiceNoteDBTableUnit in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteDBTableUnit.pas',
  ServiceNoteFilesDBTableUnit in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteFilesDBTableUnit.pas',
  ServiceNoteLinksDBTableUnit in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteLinksDBTableUnit.pas',
  ServiceNoteReceiversDBTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteReceiversDBTable.pas',
  ServiceNoteSigningTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteSigningTable.pas',
  ServiceNoteTable in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Schema\ServiceNoteTable.pas',
  ServiceNoteReceiversViewQueryTexts in '..\Persistance\Repositories\Documents\Service Notes\SQL\Postgres\Queries\ServiceNoteReceiversViewQueryTexts.pas',
  IncomingServiceNote in '..\Domain\Documents\Service Notes\Entities\IncomingServiceNote.pas',
  ServiceNote in '..\Domain\Documents\Service Notes\Entities\ServiceNote.pas',
  ServiceNoteChargeSheet in '..\Domain\Documents\Service Notes\Entities\ServiceNoteChargeSheet.pas',
  ServiceNoteWorkCycle in '..\Domain\Documents\Service Notes\Entities\ServiceNoteWorkCycle.pas',
  DepartmentUnit in '..\Domain\Employees\Entities\DepartmentUnit.pas',
  Employee in '..\Domain\Employees\Entities\Employee.pas',
  RoleUnit in '..\Domain\Employees\Entities\RoleUnit.pas',
  DepartmentRepository in '..\Persistance\Repositories\Employees\Interfaces\DepartmentRepository.pas',
  IEmployeeRepositoryUnit in '..\Persistance\Repositories\Employees\Interfaces\IEmployeeRepositoryUnit.pas',
  IRoleRepositoryUnit in '..\Persistance\Repositories\Employees\Interfaces\IRoleRepositoryUnit.pas',
  DepartmentPostgresRepositoryUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\DepartmentPostgresRepositoryUnit.pas',
  EmployeePostgresRepository in '..\Persistance\Repositories\Employees\SQL\Postgres\EmployeePostgresRepository.pas',
  EmployeeReplacementPostgresRepository in '..\Persistance\Repositories\Employees\SQL\Postgres\EmployeeReplacementPostgresRepository.pas',
  RolePostgresRepositoryUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\RolePostgresRepositoryUnit.pas',
  EmployeeContactInfoDBTableUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\EmployeeContactInfoDBTableUnit.pas',
  EmployeeDBTableUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\EmployeeDBTableUnit.pas',
  EmployeeReplacementTable in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\EmployeeReplacementTable.pas',
  EmployeeRoleDBAssocTableUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\EmployeeRoleDBAssocTableUnit.pas',
  EmployeeViewMetadataUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\EmployeeViewMetadataUnit.pas',
  RoleDBTableUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Schema\RoleDBTableUnit.pas',
  EmployeePostgresRepositoryQueryTextsUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Queries\EmployeePostgresRepositoryQueryTextsUnit.pas',
  EmployeeReplacementQueryTexts in '..\Persistance\Repositories\Employees\SQL\Postgres\Queries\EmployeeReplacementQueryTexts.pas',
  EmployeesViewQueryTextsUnit in '..\Persistance\Repositories\Employees\SQL\Postgres\Queries\EmployeesViewQueryTextsUnit.pas',
  DepartmentRepositoryZeosPostgresAdapter in '..\Persistance\Repositories\Employees\SQL\Postgres\Adapters\DepartmentRepositoryZeosPostgresAdapter.pas',
  EmployeeRepositoryZeosPostgresAdapter in '..\Persistance\Repositories\Employees\SQL\Postgres\Adapters\EmployeeRepositoryZeosPostgresAdapter.pas',
  RoleRepositoryZeosPostgresAdapter in '..\Persistance\Repositories\Employees\SQL\Postgres\Adapters\RoleRepositoryZeosPostgresAdapter.pas',
  AbstractEmployeeIsSameAsOrReplacingForOthersSpecification in '..\Domain\Employees\Specifications\Subordination\AbstractEmployeeIsSameAsOrReplacingForOthersSpecification.pas',
  StandardAreEmployeesSecretariesOfSameLeaderSpecification in '..\Domain\Employees\Specifications\Subordination\StandardAreEmployeesSecretariesOfSameLeaderSpecification.pas',
  StandardAreEmployeesSubLeadersOfSameLeaderSpecification in '..\Domain\Employees\Specifications\Subordination\StandardAreEmployeesSubLeadersOfSameLeaderSpecification.pas',
  StandardEmployeeIsSameAsOrDeputyOfEmployeesSpecification in '..\Domain\Employees\Specifications\Subordination\StandardEmployeeIsSameAsOrDeputyOfEmployeesSpecification.pas',
  StandardEmployeeIsSameAsOrDeputySpecification in '..\Domain\Employees\Specifications\Subordination\StandardEmployeeIsSameAsOrDeputySpecification.pas',
  StandardEmployeeIsSameAsOrReplacingSignerForOthersSpecification in '..\Domain\Employees\Specifications\Subordination\StandardEmployeeIsSameAsOrReplacingSignerForOthersSpecification.pas',
  StandardEmployeeIsSecretaryForAnyOfEmployeesSpecification in '..\Domain\Employees\Specifications\Subordination\StandardEmployeeIsSecretaryForAnyOfEmployeesSpecification.pas',
  AreEmployeesSecretariesOfSameLeaderSpecification in '..\Domain\Employees\Specifications\Subordination\Interfaces\AreEmployeesSecretariesOfSameLeaderSpecification.pas',
  AreEmployeesSubLeadersOfSameLeaderSpecification in '..\Domain\Employees\Specifications\Subordination\Interfaces\AreEmployeesSubLeadersOfSameLeaderSpecification.pas',
  EmployeeIsSameAsOrDeputySpecification in '..\Domain\Employees\Specifications\Subordination\Interfaces\EmployeeIsSameAsOrDeputySpecification.pas',
  EmployeeIsSameAsOrReplacingForOthersSpecification in '..\Domain\Employees\Specifications\Subordination\Interfaces\EmployeeIsSameAsOrReplacingForOthersSpecification.pas',
  EmployeeIsSecretaryForAnyOfEmployeesSpecification in '..\Domain\Employees\Specifications\Subordination\Interfaces\EmployeeIsSecretaryForAnyOfEmployeesSpecification.pas',
  DocumentUsageEmployeeAccessRightsService in '..\Domain\Documents\Common\Services\Access Rights\Interfaces\DocumentUsageEmployeeAccessRightsService.pas',
  StandardDocumentUsageEmployeeAccessRightsService in '..\Domain\Documents\Common\Services\Access Rights\StandardDocumentUsageEmployeeAccessRightsService.pas',
  StandardIncomingDocumentUsageEmployeeAccessRightsService in '..\Domain\Documents\Common\Services\Access Rights\StandardIncomingDocumentUsageEmployeeAccessRightsService.pas',
  StandardDocumentApprovingProcessControlService in '..\Domain\Documents\Common\Services\Approving\StandardDocumentApprovingProcessControlService.pas',
  DocumentApprovingCycleResultFinder in '..\Domain\Documents\Common\Services\Approving\Interfaces\DocumentApprovingCycleResultFinder.pas',
  DocumentApprovingProcessControlService in '..\Domain\Documents\Common\Services\Approving\Interfaces\DocumentApprovingProcessControlService.pas',
  DocumentChargeSheetControlService in '..\Domain\Documents\Common\Services\Charge Sheets\Interfaces\DocumentChargeSheetControlService.pas',
  DocumentChargeSheetFinder in '..\Domain\Documents\Common\Services\Charge Sheets\Interfaces\DocumentChargeSheetFinder.pas',
  DocumentChargeSheetOverlappingPerformingService in '..\Domain\Documents\Common\Services\Charge Sheets\Interfaces\DocumentChargeSheetOverlappingPerformingService.pas',
  AbstractDocumentChargeSheetFinder in '..\Domain\Documents\Common\Services\Charge Sheets\AbstractDocumentChargeSheetFinder.pas',
  StandardDocumentChargeSheetControlService in '..\Domain\Documents\Common\Services\Charge Sheets\StandardDocumentChargeSheetControlService.pas',
  StandardDocumentChargeSheetFinder in '..\Domain\Documents\Common\Services\Charge Sheets\StandardDocumentChargeSheetFinder.pas',
  StandardDocumentChargeSheetOverlappingPerformingService in '..\Domain\Documents\Common\Services\Charge Sheets\StandardDocumentChargeSheetOverlappingPerformingService.pas',
  StandardDocumentFullNameCompilationService in '..\Domain\Documents\Common\Services\Formalization\StandardDocumentFullNameCompilationService.pas',
  DocumentFullNameCompilationService in '..\Domain\Documents\Common\Services\Formalization\Interfaces\DocumentFullNameCompilationService.pas',
  DocumentResponsibleFinder in '..\Domain\Documents\Common\Services\Formalization\Interfaces\DocumentResponsibleFinder.pas',
  AbstractDocumentNumeratorRegistry in '..\Domain\Documents\Common\Services\Numerators\AbstractDocumentNumeratorRegistry.pas',
  StandardDocumentNumerator in '..\Domain\Documents\Common\Services\Numerators\StandardDocumentNumerator.pas',
  DocumentNumerator in '..\Domain\Documents\Common\Services\Numerators\Interfaces\DocumentNumerator.pas',
  DocumentNumeratorRegistry in '..\Domain\Documents\Common\Services\Numerators\Interfaces\DocumentNumeratorRegistry.pas',
  StandardCreatingNecessaryDataForDocumentPerformingService in '..\Domain\Documents\Common\Services\Performing\StandardCreatingNecessaryDataForDocumentPerformingService.pas',
  CreatingNecessaryDataForDocumentPerformingService in '..\Domain\Documents\Common\Services\Performing\Interfaces\CreatingNecessaryDataForDocumentPerformingService.pas',
  StandardDocumentRegistrationService in '..\Domain\Documents\Common\Services\Registration\StandardDocumentRegistrationService.pas',
  StandardCrossDepartmentIncomingDocumentRegistrationService in '..\Domain\Documents\Common\Services\Registration\StandardCrossDepartmentIncomingDocumentRegistrationService.pas',
  DocumentRegistrationService in '..\Domain\Documents\Common\Services\Registration\Interfaces\DocumentRegistrationService.pas',
  StandardApprovingDocumentSendingRule in '..\Domain\Documents\Common\Rules\Approving\StandardApprovingDocumentSendingRule.pas',
  StandardDocumentApproverListChangingRule in '..\Domain\Documents\Common\Rules\Approving\StandardDocumentApproverListChangingRule.pas',
  StandardDocumentApprovingPassingMarkingRule in '..\Domain\Documents\Common\Rules\Approving\StandardDocumentApprovingPassingMarkingRule.pas',
  StandardDocumentApprovingPerformingRule in '..\Domain\Documents\Common\Rules\Approving\StandardDocumentApprovingPerformingRule.pas',
  StandardDocumentApprovingRejectingPerformingRule in '..\Domain\Documents\Common\Rules\Approving\StandardDocumentApprovingRejectingPerformingRule.pas',
  DocumentApproverListChangingRule in '..\Domain\Documents\Common\Rules\Approving\Interfaces\DocumentApproverListChangingRule.pas',
  DocumentApprovingPerformingRule in '..\Domain\Documents\Common\Rules\Approving\Interfaces\DocumentApprovingPerformingRule.pas',
  DocumentApprovingRejectingPerformingRule in '..\Domain\Documents\Common\Rules\Approving\Interfaces\DocumentApprovingRejectingPerformingRule.pas',
  DocumentChargeSheetOverlappedPerformingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\Interfaces\DocumentChargeSheetOverlappedPerformingRule.pas',
  EmployeeDocumentChargeSheetWorkingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\Interfaces\EmployeeDocumentChargeSheetWorkingRule.pas',
  EmployeeDocumentChargeSheetWorkingRuleRegistry in '..\Domain\Documents\Common\Rules\Charge Sheets\Interfaces\EmployeeDocumentChargeSheetWorkingRuleRegistry.pas',
  EmployeeDocumentChargeSheetWorkingRules in '..\Domain\Documents\Common\Rules\Charge Sheets\EmployeeDocumentChargeSheetWorkingRules.pas',
  StandardDocumentChargeSheetChangingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardDocumentChargeSheetChangingRule.pas',
  StandardDocumentChargeSheetOverlappedPerformingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardDocumentChargeSheetOverlappedPerformingRule.pas',
  StandardDocumentChargeSheetPerformingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardDocumentChargeSheetPerformingRule.pas',
  StandardDocumentChargeSheetViewingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardDocumentChargeSheetViewingRule.pas',
  StandardEmployeeDocumentChargeSheetWorkingRule in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardEmployeeDocumentChargeSheetWorkingRule.pas',
  StandardEmployeeDocumentChargeSheetWorkingRuleRegistry in '..\Domain\Documents\Common\Rules\Charge Sheets\StandardEmployeeDocumentChargeSheetWorkingRuleRegistry.pas',
  StandardDocumentChargeListChangingRule in '..\Domain\Documents\Common\Rules\Charges\StandardDocumentChargeListChangingRule.pas',
  StandardDocumentChargePerformedMarkingRule in '..\Domain\Documents\Common\Rules\Charges\StandardDocumentChargePerformedMarkingRule.pas',
  DocumentChargeListChangingRule in '..\Domain\Documents\Common\Rules\Charges\Interfaces\DocumentChargeListChangingRule.pas',
  DocumentChargePerformedMarkingRule in '..\Domain\Documents\Common\Rules\Charges\Interfaces\DocumentChargePerformedMarkingRule.pas',
  EmployeeDocumentWorkingRules in '..\Domain\Documents\Common\Rules\Common\EmployeeDocumentWorkingRules.pas',
  StandardEmployeeDocumentWorkingRule in '..\Domain\Documents\Common\Rules\Common\StandardEmployeeDocumentWorkingRule.pas',
  StandardEmployeeDocumentWorkingRuleRegistry in '..\Domain\Documents\Common\Rules\Common\StandardEmployeeDocumentWorkingRuleRegistry.pas',
  EmployeeDocumentWorkingRule in '..\Domain\Documents\Common\Rules\Common\Interfaces\EmployeeDocumentWorkingRule.pas',
  EmployeeDocumentWorkingRuleRegistry in '..\Domain\Documents\Common\Rules\Common\Interfaces\EmployeeDocumentWorkingRuleRegistry.pas',
  StandardEmployeeDocumentEditingRule in '..\Domain\Documents\Common\Rules\Editing\StandardEmployeeDocumentEditingRule.pas',
  StandardPerformingDocumentSendingRule in '..\Domain\Documents\Common\Rules\Performing\StandardPerformingDocumentSendingRule.pas',
  StandardDocumentSignerListChangingRule in '..\Domain\Documents\Common\Rules\Signing\StandardDocumentSignerListChangingRule.pas',
  StandardEmployeeDocumentSigningPerformingRule in '..\Domain\Documents\Common\Rules\Signing\StandardEmployeeDocumentSigningPerformingRule.pas',
  StandardEmployeeDocumentSigningRejectingPerformingRule in '..\Domain\Documents\Common\Rules\Signing\StandardEmployeeDocumentSigningRejectingPerformingRule.pas',
  StandardSigningDocumentSendingRule in '..\Domain\Documents\Common\Rules\Signing\StandardSigningDocumentSendingRule.pas',
  DocumentSignerListChangingRule in '..\Domain\Documents\Common\Rules\Signing\Interfaces\DocumentSignerListChangingRule.pas',
  DocumentSigningPerformingRule in '..\Domain\Documents\Common\Rules\Signing\Interfaces\DocumentSigningPerformingRule.pas',
  DocumentSigningRejectingPerformingRule in '..\Domain\Documents\Common\Rules\Signing\Interfaces\DocumentSigningRejectingPerformingRule.pas',
  StandardEmployeeDocumentViewingRule in '..\Domain\Documents\Common\Rules\Viewing\StandardEmployeeDocumentViewingRule.pas',
  ZeosDocumentViewingAccountingService in '..\Application\Accounting\Docs\Zeos-Based\ZeosDocumentViewingAccountingService.pas',
  ZeosPostgresDocumentViewingAccountingService in '..\Application\Accounting\Docs\Zeos-Based\Postgres\ZeosPostgresDocumentViewingAccountingService.pas',
  ZeosPostgresIncomingDocumentViewingAccountingService in '..\Application\Accounting\Docs\Zeos-Based\Postgres\ZeosPostgresIncomingDocumentViewingAccountingService.pas',
  StandardDocumentChargeSheetControlAppService in '..\Application\Business Processes\Docs\Common\Charge Sheets\StandardDocumentChargeSheetControlAppService.pas',
  AbstractDocumentStorageService in '..\Application\Business Processes\Docs\Common\Storage\AbstractDocumentStorageService.pas',
  AbstractIncomingDocumentStorageService in '..\Application\Business Processes\Docs\Common\Storage\AbstractIncomingDocumentStorageService.pas',
  AbstractOutcomingDocumentStorageService in '..\Application\Business Processes\Docs\Common\Storage\AbstractOutcomingDocumentStorageService.pas',
  StandardDocumentApprovingControlAppService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingControlAppService.pas',
  StandardDocumentApprovingPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingPerformingService.pas',
  StandardDocumentApprovingRejectingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingRejectingService.pas',
  StandardDocumentApprovingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentApprovingService.pas',
  StandardDocumentPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentPerformingService.pas',
  StandardDocumentSigningRejectingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningRejectingService.pas',
  StandardDocumentSigningService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardDocumentSigningService.pas',
  StandardSendingDocumentToApprovingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToApprovingService.pas',
  StandardSendingDocumentToPerformingService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToPerformingService.pas',
  StandardSendingDocumentToSigningService in '..\Application\Business Processes\Docs\Common\Work Cycle\StandardSendingDocumentToSigningService.pas',
  AbstractDocumentChargeSheetNotifyingMessageBuilder in '..\Application\External\Messaging\Documents\Common\AbstractDocumentChargeSheetNotifyingMessageBuilder.pas',
  StandardDocumentChargeSheetCasesNotifier in '..\Application\External\Messaging\Documents\Common\StandardDocumentChargeSheetCasesNotifier.pas',
  AllEmployeesDocumentNotificationPolicy in '..\Application\External\Messaging\Documents\Common\Policies\AllEmployeesDocumentNotificationPolicy.pas',
  ForeignEmployeesDocumentNotificationPolicy in '..\Application\External\Messaging\Documents\Common\Policies\ForeignEmployeesDocumentNotificationPolicy.pas',
  NoneEmployeeDocumentNotificationPolicy in '..\Application\External\Messaging\Documents\Common\Policies\NoneEmployeeDocumentNotificationPolicy.pas',
  EmailDocumentChargeSheetNotifyingMessageBuilder1 in '..\Application\External\Messaging\Documents\Email\EmailDocumentChargeSheetNotifyingMessageBuilder1.pas',
  EmailDocumentChargeSheetNotifyingMessageBuilder2 in '..\Application\External\Messaging\Documents\Email\EmailDocumentChargeSheetNotifyingMessageBuilder2.pas',
  DocumentFileServiceClientUnit in '..\Application\External\Storage\DocumentFileServiceClientUnit.pas',
  StandardEmployeeDepartmentManagementService in '..\Application\Management\Employees\StandardEmployeeDepartmentManagementService.pas',
  BasedOnDataSetDocumentCreatingDefaultInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\BasedOnDataSetDocumentCreatingDefaultInfoReadService.pas',
  BasedOnDataSetDocumentInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\BasedOnDataSetDocumentInfoReadService.pas',
  ZeosDocumentCreatingDefaultInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\Zeos-Based\ZeosDocumentCreatingDefaultInfoReadService.pas',
  ZeosDocumentInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\Zeos-Based\ZeosDocumentInfoReadService.pas',
  ZeosPostgresDocumentInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\Zeos-Based\Postgres\ZeosPostgresDocumentInfoReadService.pas',
  ZeosPostgresIncomingDocumentInfoReadService in '..\Application\Presentation\Docs\DataSet-Based\Zeos-Based\Postgres\ZeosPostgresIncomingDocumentInfoReadService.pas',
  NotPerformedDocumentsReportDataZeosService in '..\Application\Reporting\Docs\Zeos-Based\NotPerformedDocumentsReportDataZeosService.pas',
  NotPerformedDocumentsReportDataZeosPostgresService in '..\Application\Reporting\Docs\Zeos-Based\Postgres\NotPerformedDocumentsReportDataZeosPostgresService.pas',
  AbstractEmployeeDocumentWorkStatisticsZeosService in '..\Application\Statistics\Docs\Zeos-Based\AbstractEmployeeDocumentWorkStatisticsZeosService.pas',
  EmployeeDocumentWorkStatisticsPostgresService in '..\Application\Statistics\Docs\Zeos-Based\Postgres\EmployeeDocumentWorkStatisticsPostgresService.pas',
  DBWorkingEmployeeUnit in '..\Application\Working Employee\DBWorkingEmployeeUnit.pas',
  IWorkingEmployeeUnit in '..\Application\Working Employee\IWorkingEmployeeUnit.pas',
  WorkingEmployeeUnit in '..\Application\Working Employee\WorkingEmployeeUnit.pas',
  ZeosPostgresWorkingEmployeeUnit in '..\Application\Working Employee\ZeosPostgresWorkingEmployeeUnit.pas',
  DocumentKindResolver in '..\Application\Common\Resolvers\Document Kinds\DocumentKindResolver.pas',
  NumericDocumentKindResolver in '..\Application\Common\Resolvers\Document Kinds\NumericDocumentKindResolver.pas',
  IncomingServiceNoteStorageService in '..\Application\Business Processes\Docs\Service Notes\Storage\IncomingServiceNoteStorageService.pas',
  ServiceNoteStorageService in '..\Application\Business Processes\Docs\Service Notes\Storage\ServiceNoteStorageService.pas',
  ServiceNoteDomainObjectsFromDTOMapper in '..\Application\Business Processes\Docs\Service Notes\Mappers\ServiceNoteDomainObjectsFromDTOMapper.pas',
  DocumentOperationService in '..\Application\Business Processes\Docs\Common\DocumentOperationService.pas',
  EmployeeDocumentOperationService in '..\Application\Business Processes\Docs\Common\EmployeeDocumentOperationService.pas',
  DocumentDomainObjectsFromDTOMapper in '..\Application\Business Processes\Docs\Common\Mappers\DocumentDomainObjectsFromDTOMapper.pas',
  DocumentCreatingDefaultInfoReadService in '..\Application\Presentation\Docs\Interfaces\DocumentCreatingDefaultInfoReadService.pas',
  DocumentInfoReadService in '..\Application\Presentation\Docs\Interfaces\DocumentInfoReadService.pas',
  DocumentCreatingDefaultInfoDataSetHolder in '..\Application\Presentation\Docs\Mappers\DocumentCreatingDefaultInfoDataSetHolder.pas',
  DocumentFullInfoDataSetHolder in '..\Application\Presentation\Docs\Mappers\DocumentFullInfoDataSetHolder.pas',
  DocumentFullInfoDTOFromDataSetMapper in '..\Application\Presentation\Docs\Mappers\DocumentFullInfoDTOFromDataSetMapper.pas',
  IncomingDocumentFullInfoDataSetHolder in '..\Application\Presentation\Docs\Mappers\IncomingDocumentFullInfoDataSetHolder.pas',
  IncomingDocumentFullInfoDTOFromDataSetMapper in '..\Application\Presentation\Docs\Mappers\IncomingDocumentFullInfoDTOFromDataSetMapper.pas',
  DataSetCloner in 'Data Interfaces\Cloners\DataSetCloner.pas',
  ZeosDataSetCloner in 'Data Interfaces\Cloners\ZeosDataSetCloner.pas',
  ZQueryCloner in 'Data Interfaces\Cloners\ZQueryCloner.pas',
  ZReadOnlyQueryCloner in 'Data Interfaces\Cloners\ZReadOnlyQueryCloner.pas',
  IncommingServiceNoteReceiversReferenceFilterFormStatePropertiesIniFile in 'Launching\Properties Storing\Documents\References\Service Notes\IncommingServiceNoteReceiversReferenceFilterFormStatePropertiesIniFile.pas',
  IncommingServiceNoteReceiversReferenceFormPropertiesIniFile in 'Launching\Properties Storing\Documents\References\Service Notes\IncommingServiceNoteReceiversReferenceFormPropertiesIniFile.pas',
  MainEmployeeIncommingServiceNotesReferenceFilterFormStatePropertiesIniFile in 'Launching\Properties Storing\Documents\References\Service Notes\MainEmployeeIncommingServiceNotesReferenceFilterFormStatePropertiesIniFile.pas',
  MainEmployeeIncommingServiceNotesReferenceFormPropertiesIniFile in 'Launching\Properties Storing\Documents\References\Service Notes\MainEmployeeIncommingServiceNotesReferenceFormPropertiesIniFile.pas',
  MainEmployeeDocumentsReferenceFilterFormStatePropertiesIniFile in 'Launching\Properties Storing\Documents\References\MainEmployeeDocumentsReferenceFilterFormStatePropertiesIniFile.pas',
  MainEmployeeDocumentsReferenceFormPropertiesIniFile in 'Launching\Properties Storing\Documents\References\MainEmployeeDocumentsReferenceFormPropertiesIniFile.pas',
  DocumentRecordsPanelSettingsFormPropertiesIniFile in 'Launching\Properties Storing\Documents\Settings\DocumentRecordsPanelSettingsFormPropertiesIniFile.pas',
  DocumentRecordsPanelSettingsFormPropertiesStorage in 'Launching\Properties Storing\Documents\Settings\DocumentRecordsPanelSettingsFormPropertiesStorage.pas',
  DocumentInformationFramePropertiesStorage in 'Launching\Properties Storing\Documents\Frames\DocumentInformationFramePropertiesStorage.pas',
  DocumentChargesFramePropertiesIniFile in 'Launching\Properties Storing\Documents\Frames\DocumentChargesFramePropertiesIniFile.pas',
  DocumentChargesFramePropertiesStorage in 'Launching\Properties Storing\Documents\Frames\DocumentChargesFramePropertiesStorage.pas',
  DocumentCardFramePropertiesIniFile in 'Launching\Properties Storing\Documents\Frames\Cards\DocumentCardFramePropertiesIniFile.pas',
  DocumentCardFramePropertiesStorage in 'Launching\Properties Storing\Documents\Frames\Cards\DocumentCardFramePropertiesStorage.pas',
  ApplicationMainFormPropertiesIniFile in 'Launching\Properties Storing\Common\ApplicationMainFormPropertiesIniFile.pas',
  ApplicationMainFormPropertiesStorage in 'Launching\Properties Storing\Common\ApplicationMainFormPropertiesStorage.pas',
  ApplicationPropertiesStorageRegistry in 'Launching\Properties Storing\ApplicationPropertiesStorageRegistry.pas',
  EmployeeDocumentNotificationPolicy in '..\Application\External\Messaging\Documents\Common\Policies\Interfaces\EmployeeDocumentNotificationPolicy.pas',
  DocumentOperationToolBarFrameUnit in 'Forms\Documents\Frames\DocumentOperationToolBarFrameUnit.pas' {DocumentOperationToolBarFrame: TFrame},
  ApproveableDocumentCardFrameUnit in 'Forms\Documents\Cards\Common\ApproveableDocumentCardFrameUnit.pas' {ApproveableDocumentCardFrame: TFrame},
  SignableDocumentCardFrameUnit in 'Forms\Documents\Cards\Common\SignableDocumentCardFrameUnit.pas' {SignableDocumentCardFrame: TFrame},
  IncomingDocumentChargePerformersReferenceFormUnit in 'Forms\Documents\References\Common\IncomingDocumentChargePerformersReferenceFormUnit.pas' {IncomingDocumentChargePerformersReferenceForm},
  DocumentDraftingRule in '..\Domain\Documents\Common\Rules\Drafting\Interfaces\DocumentDraftingRule.pas',
  StandardDocumentDraftingRule in '..\Domain\Documents\Common\Rules\Drafting\StandardDocumentDraftingRule.pas',
  EmployeeSetReadService in '..\Application\Presentation\Employees\References\Interfaces\EmployeeSetReadService.pas',
  EmployeeSetHolder in '..\Application\Presentation\Employees\References\Common\DataSet Holders\EmployeeSetHolder.pas',
  DepartmentDbSchema in '..\Application\Presentation\Employees\References\Based-On DB\Common\DepartmentDbSchema.pas',
  EmployeeDbSchema in '..\Application\Presentation\Employees\References\Based-On DB\Common\EmployeeDbSchema.pas',
  BasedOnDatabaseEmployeeSetReadService in '..\Application\Presentation\Employees\References\Based-On DB\BasedOnDatabaseEmployeeSetReadService.pas',
  EmployeeDocumentChargesWorkStatistics in '..\Application\Statistics\Docs\Charges\Interfaces\EmployeeDocumentChargesWorkStatistics.pas',
  EmployeeDocumentChargesWorkStatisticsService in '..\Application\Statistics\Docs\Charges\Interfaces\EmployeeDocumentChargesWorkStatisticsService.pas',
  EmployeeDocumentChargesWorkStatisticsZeosService in '..\Application\Statistics\Docs\Charges\Zeos-Based\EmployeeDocumentChargesWorkStatisticsZeosService.pas',
  EmployeeDocumentChargesWorkStatisticsPostgresService in '..\Application\Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeDocumentChargesWorkStatisticsPostgresService.pas',
  EmployeeIncomingServiceNoteChargesWorkStatisticsPostgresService in '..\Application\Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeIncomingServiceNoteChargesWorkStatisticsPostgresService.pas',
  EmployeeOutcomingServiceNoteChargesWorkStatisticsPostgresService in '..\Application\Statistics\Docs\Charges\Zeos-Based\Postgres\EmployeeOutcomingServiceNoteChargesWorkStatisticsPostgresService.pas',
  EmployeesAdminReferenceFormUnit in 'Forms\System Administration\Forms\References\Employees\EmployeesAdminReferenceFormUnit.pas' {EmployeesAdminReferenceForm},
  SystemAuthorizationService in '..\Application\System\Authorization\Interfaces\SystemAuthorizationService.pas',
  BasedOnDatabaseSystemAuthorizationService in '..\Application\System\Authorization\Based-On Databases\BasedOnDatabaseSystemAuthorizationService.pas',
  BasedOnZeosSystemAuthorizationService in '..\Application\System\Authorization\Based-On Databases\Based-On Zeos\BasedOnZeosSystemAuthorizationService.pas',
  SystemServiceRegistry in '..\Application\System\SystemServiceRegistry.pas',
  SystemAdminPrivilegeManageableObjects in '..\Application\System\Administration\DTOs\SystemAdminPrivilegeManageableObjects.pas',
  SystemAdminPrivileges in '..\Application\System\Administration\DTOs\SystemAdminPrivileges.pas',
  SystemAdministrationService in '..\Application\System\Administration\Interfaces\SystemAdministrationService.pas',
  StandardSystemAdministrationService in '..\Application\System\Administration\Standard\StandardSystemAdministrationService.pas',
  RoleDbSchema in '..\Application\Presentation\Employees\References\Based-On DB\Common\RoleDbSchema.pas',
  DocumentApprovingCycleViewModel in 'Forms\Documents\Frames\View Models\DocumentApprovingCycleViewModel.pas',
  DetachableDocumentCardFrameUnit in 'Forms\Documents\Cards\Common\DetachableDocumentCardFrameUnit.pas' {DetachableDocumentCardFrame: TFrame},
  PerformableDocumentCardFrameUnit in 'Forms\Documents\Cards\Common\PerformableDocumentCardFrameUnit.pas' {PerformableDocumentCardFrame: TFrame},
  DocumentApprovingListViewModel in 'Forms\Documents\Cards\Common\View Models\DocumentApprovingListViewModel.pas',
  DocumentApprovingListViewModelMapper in 'ViewModel Mappers\Documents\Cards\Common\DocumentApprovingListViewModelMapper.pas',
  DocumentApprovingListRecordSetHolder in 'DataSet Holders\Documents\Common\DocumentApprovingListRecordSetHolder.pas',
  KindedDocumentDataSetHoldersFactory in 'DataSet Holders\Documents\Factories\KindedDocumentDataSetHoldersFactory.pas',
  EmployeeStaff in '..\Domain\Employees\Entities\EmployeeStaff.pas',
  OutcomingDocumentRecordViewModelMapper in 'ViewModel Mappers\Documents\References\Common\OutcomingDocumentRecordViewModelMapper.pas',
  OutcomingDocumentRecordViewModel in 'Forms\Documents\References\Common\Employee\View Models\OutcomingDocumentRecordViewModel.pas',
  EmployeeDocumentTableRecord in 'Forms\Documents\References\Common\Employee\EmployeeDocumentTableRecord.pas',
  PadegImports in 'Reporting\Presenters\Print Forms\PadegImports.pas',
  unNotDocumentApprovingReasonInputForm in 'Forms\Documents\Frames\unNotDocumentApprovingReasonInputForm.pas' {NotDocumentApprovingReasonInputForm},
  LoginFrm in 'D:\Common Delphi Libs\DelphLib\LoginFrm.pas' {LoginForm},
  DBDataTableFormUnit in 'D:\Common Delphi Libs\u_59968 Delphi Modules\DBDataTableForm\DBDataTableFormUnit.pas' {DBDataTableForm},
  DocumentFlowBaseReferenceFormUnit in 'Forms\Common\References\DocumentFlowBaseReferenceFormUnit.pas' {DocumentFlowBaseReferenceForm},
  EmployeesReferenceFormUnit in 'Forms\Employees\References\EmployeesReferenceFormUnit.pas' {EmployeesReferenceForm},
  DocumentApproversReferenceFormUnit in 'Forms\Documents\References\Common\DocumentApproversReferenceFormUnit.pas' {DocumentApproversReferenceForm},
  DocumentApprovingCyclesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentApprovingCyclesReferenceFormUnit.pas' {DocumentApprovingCyclesReferenceForm},
  DocumentChargePerformersReferenceFormUnit in 'Forms\Documents\References\Common\DocumentChargePerformersReferenceFormUnit.pas' {DocumentChargePerformersReferenceForm},
  DocumentFilesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentFilesReferenceFormUnit.pas' {DocumentFilesReferenceForm},
  DocumentRelationsReferenceFormUnit in 'Forms\Documents\References\Common\DocumentRelationsReferenceFormUnit.pas' {DocumentRelationsReferenceForm},
  DocumentResponsiblesReferenceFormUnit in 'Forms\Documents\References\Common\DocumentResponsiblesReferenceFormUnit.pas' {DocumentResponsiblesReferenceForm},
  DocumentSignersReferenceFormUnit in 'Forms\Documents\References\Common\DocumentSignersReferenceFormUnit.pas' {DocumentSignersReferenceForm},
  EmployeeInternalDocumentsReferenceFormUnit in 'Forms\Documents\References\Common\Employee\EmployeeInternalDocumentsReferenceFormUnit.pas' {EmployeeInternalDocumentsReferenceForm},
  ApplicationDataModuleUnit in 'Data Interfaces\ApplicationDataModuleUnit.pas' {ApplicationDataModule: TDataModule},
  DocumentZeosViewDataSetsDataModuleUnit in 'Data Interfaces\DocumentZeosViewDataSetsDataModuleUnit.pas' {DocumentZeosViewDataSetsDataModule: TDataModule};

{$R *.res}

var ApplicationLauncher: TApplicationLauncher;
begin

  try

    ApplicationLauncher :=
      TApplicationLauncher.Create(
        TUIApplicationConfigurator.Create
      );

    ApplicationLauncher.Launch;

  finally

    FreeAndNil(ApplicationLauncher);
    
  end;

end.
