unit EmployeeRoleAssocTableDef;

interface

const
                    
  EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME = 'doc.employees_roles';
  EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_1= 'er1';
  EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_2 = 'er2';
  
  EMPLOYEES_ROLES_TABLE_ASSOCIATION_EMPLOYEE_ID_FIELD = 'employee_id';
  EMPLOYEES_ROLES_TABLE_ASSOCIATION_ROLE_ID_FIELD = 'role_id';

  EMPLOYEES_ROLES_TABLE_ASSOCIATION_EMPLOYEE_ID_FIELD_ALIAS_1 =
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_1 + '_' +
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_EMPLOYEE_ID_FIELD;

  EMPLOYEES_ROLES_TABLE_ASSOCIATION_ROLE_ID_FIELD_ALIAS_1 =
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_1 + '_' +
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_ROLE_ID_FIELD;

  EMPLOYEES_ROLES_TABLE_ASSOCIATION_EMPLOYEE_ID_FIELD_ALIAS_2 =
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_2 + '_' +
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_EMPLOYEE_ID_FIELD;

  EMPLOYEES_ROLES_TABLE_ASSOCIATION_ROLE_ID_FIELD_ALIAS_2 =
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_NAME_ALIAS_2 + '_' +
    EMPLOYEES_ROLES_TABLE_ASSOCIATION_ROLE_ID_FIELD;

implementation

end.
