unit EmployeeWorkGroupAssocTableDef;

interface

const

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME = 'doc.employees_employee_work_groups';

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_1 = 'eewg1';
  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_2 = 'eewg2';
  
  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_ID_FIELD = 'id';
  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_EMPLOYEE_ID_FIELD = 'employee_id';
  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_WORK_GROUP_ID_FIELD = 'work_group_id';

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_ID_FIELD_ALIAS_1 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_1 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_ID_FIELD;

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_EMPLOYEE_ID_FIELD_ALIAS_1 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_1 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_EMPLOYEE_ID_FIELD;

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_WORK_GROUP_ID_FIELD_ALIAS_1 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_1 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_WORK_GROUP_ID_FIELD;

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_ID_FIELD_ALIAS_2 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_2 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_ID_FIELD;

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_EMPLOYEE_ID_FIELD_ALIAS_2 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_2 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_EMPLOYEE_ID_FIELD;

  EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_WORK_GROUP_ID_FIELD_ALIAS_2 =
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_NAME_ALIAS_2 + '_' +
    EMPLOYEE_WORK_GROUPS_ASSOCIATION_TABLE_WORK_GROUP_ID_FIELD;

implementation

end.
